### ISSUE TITLE
Cosmetics not working

### ISSUE THREAD

**Issue by noobynuub** [Solar-Tweaks/Solar-Tweaks#1001]
Everything works except when i boot it up the cosmetics do not show up in the menu.

**Comment by HypedDomi** [comment]
Cosmetics wont work on cracked Accounts

**Comment by noobynuub** [comment]
im using an actual minecraft account

**Comment by HypedDomi** [comment]
Do you have the right Websocket? wss://socket.solartweaks.com

**Comment by noobynuub** [comment]
yes

**Comment by HypedDomi** [comment]
Start SolarTweaks and screenshot the main menu

**Comment by 770grappenmaker** [comment]
There might be a different error hindering solar engine from patching your game, please attach your logs
