### ISSUE TITLE
Not launching

### ISSUE THREAD

**Issue by Chon-Xena** [Solar-Tweaks/Solar-Tweaks#1003]
**Clicking the launch button but nothing happens.**

**To Reproduce**
1. Go to 'solar tweak launcher'
2. Click on 'Launch button on any version'

**Expected behavior**
It would launch the game in the selected version.

**Actual behavior**
The button turns purple for a while and stops at "Launching, checking engine" then the button goes back to green: "Launch 'version'" and it didn't launch

**Screenshots**
If applicable, add screenshots to help explain your problem.![

D**Environment (please complete the following information):**
 - OS: Windows 11
 - Launcher Version 4.3.3
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
![Solar  tweaks ](https://user-images.githubusercontent.com/128638054/227016594-aa4df891-ce2a-4637-94ad-d1cc5c044c00.png)

**Comment by HypedDomi** [comment]
Do you have Lunar installed?

**Comment by Chon-Xena** [comment]
Nvm I installed the new Java version 17 and fix the Java option environment variables, and somehow it worked.

**Comment by Chon-Xena** [comment]
Yes yes I did  install Lunar a  long time ago.
