### ISSUE TITLE
Solar launches lunar without crack support

### ISSUE THREAD

**Issue by ArchBtw8683** [Solar-Tweaks/Solar-Tweaks#1008]
I'm running Arch linux with temurin JRE installed and applied, every time I try and launch it'd give the "JRE not found" message, selecting JRE folder found in lunarclient/solartweaks or lunarclient/jres works, but solar launches lunar with none of solar's features working.

**Comment by muaz9837-ux** [comment]
Same issue.Pls help

**Comment by HypedDomi** [comment]
> I find solution

That doesn't help at all. You're on Windows, he is on Linux

**Comment by muaz9837-ux** [comment]
if he delete lunar client file, the problems was fixed

**Comment by muaz9837-ux** [comment]
Try this solution once

**Comment by Asicalug** [comment]
> I find solution

You don't need to move your mouse like this
