### ISSUE TITLE
How Can i self install GraavalVM? (If I Can)

### ISSUE THREAD

**Issue by cqyber** [Solar-Tweaks/Solar-Tweaks#1010]
I Know the installer inside of the launcher doesn't work, atleast for me but is there a way i can install it myself and use it as the launcher? heared its better for performance.

**Comment by HypedDomi** [comment]
Sure. Get the install link from here:
https://github.com/Solar-Tweaks/Solar-Tweaks/blob/e43d2756e5c9fe3cbc80c959f625b142b6e8bb84/src/components/Content/Settings.vue#L397-L501
