### ISSUE TITLE
Lunar client opens when opening with solar

### ISSUE THREAD

**Issue by MrMasked001** [Solar-Tweaks/Solar-Tweaks#1011]
**when I launch using the Solar tweaks it just runs Lunar**
I am sure of it as no modules work. I am using arch linux and know it as the title bar says Lunar client Not Solar Client
![Screenshot_2023-03-26-15-10-47_1366x768](https://user-images.githubusercontent.com/74668157/227771920-2e32f084-1187-4414-8467-9a83e1e10f2b.png)

**Comment by HypedDomi** [comment]
Youre on legacy. Switch to the master branch
