### ISSUE TITLE
There is no sound  and i cant change language in this versions: 1.17.1 1.18.2 1.18.1

### ISSUE THREAD

**Issue by dani44hun** [Solar-Tweaks/Solar-Tweaks#1014]
When I turn on lunar client or any other client there is sound, but when I turn on solar tweaks there is no sound, and i cant change languages because the language list is empty. I don't know why, but it's probably because  they are bugs.

Mc version: 1.17.1, 1.18.2, 1.18.1
Win 10
Newest version of solar tweaks launcher

**Comment by dani44hun** [comment]
> When I turn on lunar client or any other client there is sound, but when I turn on solar tweaks there is no sound, and i cant change languages because the language list is empty.I don't know why, but it's probably a bugs.
> 
> Mc version: 1.17.1, 1.18.2, 1.18.1 Win 10 Newest version of solar tweaks launcher

**Comment by 770grappenmaker** [comment]
Disable skip checks, and make sure your game directories in settings are set to the same one as in the lunar client launcher, then try again. (And no, it is not a bug)

**Comment by 770grappenmaker** [comment]
This happens because we will not download Minecraft assets for you, since the Minecraft launcher is meant to do that. This is intentional, but it means Minecraft wont work properly if the game directory is set to one without Minecraft assets

**Comment by dani44hun** [comment]
Okay thats i think thats going to work :D
