### ISSUE TITLE
Emotes not Showing

### ISSUE THREAD

**Issue by LoadingBatu** [Solar-Tweaks/Solar-Tweaks#1021]
**Describe the bug**
Hi, I cant see Any Emotes from my Friend but my Other Friend can see the Emotes from my 1. Friend (They are Using Solar-Tweaks)

**To Reproduce**
1. Go to 'Emote Wheel'
2. Click on 'Any Emote'
3. Ask your Friend 'if he saw The Emo'
5. See error

**Expected behavior**
That i can See the The Emotes from Other Players

**Actual behaviour**
I cant see Any Emotes from other Players (Theyre Using Solar-Tweaks)

**Screenshots**

**Environment
 - OS: Windows
 - Launcher Version [eg. 4.3.3]
 - Engine Version [eg. 1.6] ()
 - Solar Stats Version (if applicable)

**Additional context**

**Comment by HypedDomi** [comment]
1. You need to be on the same Websocket: `wss://socket.solartweaks.com`
2. Wont work for cracked players

**Comment by 770grappenmaker** [comment]
If you are not both on the same WS, it will not work, also SolarSocket is technically a seperate project. Normal Lunar Client users wont see the emotes anyway
