### ISSUE TITLE
flickring problem

### ISSUE THREAD

**Issue by KYSON99** [Solar-Tweaks/Solar-Tweaks#1022]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by HypedDomi** [comment]
Please add more info like logs, a video or images

**Comment by qualk** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Actual behaviour** Description of what is actually happening.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Environment (please complete the following information):**
> 
> * OS: [e.g. Windows]
> * Launcher Version [eg. 4.0.1]
> * Engine Version [eg. 1.6] (If you can't find this, leave blank)
> * Solar Stats Version (if applicable)
> 
> **Additional context** Add any other context about the problem here. Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

Fill out the template man, that's what its for. You can't just expect us to see what your problem is with just "flickering problem".

**Comment by 770grappenmaker** [comment]
I had that in the past as well, reset the graphics settings of your gpu driver

**Comment by qualk** [comment]
> I had that in the past as well, reset the graphics settings of your gpu driver

that would be quite troublesome to do as that would remove people's settings. Is there another way, such as a specific cache that needs deletion (e.g. DirectX Shader Cache)?

**Comment by 770grappenmaker** [comment]
> > I had that in the past as well, reset the graphics settings of your gpu driver
> 
> 
> 
> that would be quite troublesome to do as that would remove people's settings. Is there another way, such as a specific cache that needs deletion (e.g. DirectX Shader Cache)?

Don't remember the specific option but it's only the 3D settings, which are good enough by default in 99% of the cases, messing with some of them can cause flickering
