### ISSUE TITLE
1.19.2 hurt camera dosent work

### ISSUE THREAD

**Issue by eacku05** [Solar-Tweaks/Solar-Tweaks#1026]
**Is your feature request related to a problem? Please describe.**
When i put the hurt camera multiplayer to 0, and launch in 1.19.2 it dosent work while when i launch in 1.8 it works

**Describe the solution you'd like**
I would like for it to work on 1.19.2

**Describe alternatives you've considered**
nothing worked

**Comment by qualk** [comment]
Yeah doesn't work on 1.8+, but you can use the NoHurtCam built into Lunar, they added a mod for it.
