### ISSUE TITLE
Language change not working.

### ISSUE THREAD

**Issue by its-Jaxx** [Solar-Tweaks/Solar-Tweaks#1033]
**Describe the bug**
Changing language doesn't actually change language.

**To Reproduce**
Click on book to change language
Select different language
Proceed through given steps
Restart client
Changes are reverted

**Expected behavior**
Language should change

**Actual behaviour**
Language reverted back and never changed at all.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 Pro (Version: 22H2) (Build: 19045.2728)
 - Launcher Version: 4.3.3

https://user-images.githubusercontent.com/96382604/229767400-23343748-ffc7-40ea-8622-304dbe9ff819.mp4

**Comment by HypedDomi** [comment]
The language is just for the Tutorial. We haven't translated the whole launcher so far
