### ISSUE TITLE
launcher doesn't work

### ISSUE THREAD

**Issue by NajtYT** [Solar-Tweaks/Solar-Tweaks#1035]
Check Natives Error: TypeError: Cannot read property 'artifacts' of undefined
    at Jt (app://./js/app.b5ebebce.js:1:46400)
    at async Bt (app://./js/app.b5ebebce.js:1:52705)
    at async Proxy.launchGame (app://./js/app.b5ebebce.js:1:54488)

**Comment by HypedDomi** [comment]
**Windows:**
Download [SolarPurge.bat](https://cdn.discordapp.com/attachments/979553959624728596/1028683669419855912/SolarPurge.bat) and run it as Administrator.
Then, reinstall Solar Tweaks using [this setup](https://github.com/Solar-Tweaks/Solar-Tweaks/releases/download/v4.3.3/Solar-Tweaks-Setup-4.3.3.exe)

**MacOS:**
Open up terminal, and run `rm -rf ~/Library/Application Support/solartweaks`

Then you can relaunch Solar Tweaks, and it should resolve your issues.
