### ISSUE TITLE
Not starting in Mac

### ISSUE THREAD

**Issue by ThorInsaan** [Solar-Tweaks/Solar-Tweaks#1036]
Game not starting in mac. I expected it to work but it didn't

**Comment by HypedDomi** [comment]
Send your logs
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4
