### ISSUE TITLE
[Enhancement] Health Indicators for other Players

### ISSUE THREAD

**Issue by dakemdi** [Solar-Tweaks/Solar-Tweaks#1039]
**nah its just pvp addon**
i wanna know the enemy health when im pvping

**add a health ındıcators mod like playerhealth ındıcators mod**
i just want to know enemy health with health ındıcator

**u can add anything like toro health ındıcators**
idk

****
![image](https://user-images.githubusercontent.com/123462180/230161836-0d98a933-7571-4a40-8626-679d0925dc04.png)
![image](https://user-images.githubusercontent.com/123462180/230161911-4f067ed7-9f6c-4a20-b4f4-e8b4e96c3ae2.png)
![image](https://user-images.githubusercontent.com/123462180/230161977-1fb9baed-7b0d-4244-8e5d-ae20eca9ea07.png)

**Comment by Waffles3438** [comment]
vape.gg

**Comment by 770grappenmaker** [comment]
cheat
