### ISSUE TITLE
My Minecraft wasn't working (wasn't opened) in solar tweaks

### ISSUE THREAD

**Issue by MakanNuggetz** [Solar-Tweaks/Solar-Tweaks#1051]
Hey, can you help me? i cannot play minecraft, because Solar Tweaks wasn't opening the game, i have watch many tutorial and even reading your website tutorial, but nor of them are working, Can you show me how? becuase i want to feel many FPS in my pc

**Comment by HypedDomi** [comment]
Please send your Logs and make sure you have installed Lunar Client
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4

**Comment by MakanNuggetz** [comment]
Can i just upload it here? i can't find the tab in server, here.
[`Here`](https://mega.nz/file/WAJV3AbJ#P69stQn5krdl-hWf7nFVaFteZerhljQdXtv1FO3pUL4)

**Comment by MakanNuggetz** [comment]
But that road me into another problem, my minecraft window isn't opening, but, only the Java is opened but java isn't opening Minecraft, in Official Lunar Client minecraft are opened like normally.

**Comment by HypedDomi** [comment]
Thats fine. But you need to enable Keep Launcher opened, otherwise we cant help you with the logs
