### ISSUE TITLE
Cracked account not working after enabling the cracked accounts on engine

### ISSUE THREAD

**Issue by oClucth** [Solar-Tweaks/Solar-Tweaks#1052]
Hey can u guys help me pls i cant use sloar tweaks because the cracked account in not working still after enabling it on engine

**Comment by HypedDomi** [comment]
1. Make sure youre on master branch and not on legacy
2. Send your Logs:
	1. Open Solar Tweaks and **enable** `Keep Launcher open`
	2. Try to reproduce the error
	3. Go to the About tab and click `Download Logs` then click `Open ST directory`
	4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4
