### ISSUE TITLE
Cosmetics Not Working

### ISSUE THREAD

**Issue by ScoreNoobXD** [Solar-Tweaks/Solar-Tweaks#1055]
the cosmetics are not working, (i enable and put a link in web socket and metadata enable)
when i lanch the lancher and click on cosmetics nothing happend

**Comment by Asicalug** [comment]
Are you on cracked?

**Comment by ScoreNoobXD** [comment]
> 

does it need cracked? or prem

**Comment by HypedDomi** [comment]
You need a Premium account. It wont work on cracked
