### ISSUE TITLE
1.8.9 sound issue. I don't hear any sound in 1.8.9

### ISSUE THREAD

**Issue by M0Osh** [Solar-Tweaks/Solar-Tweaks#1056]
I don't hear any sound in 1.8.9
I do hear sound at other version but not 1.8.9

**Comment by HypedDomi** [comment]
<img width="601" alt="image" src="https://user-images.githubusercontent.com/50876016/230874166-f5a394ed-c296-4f90-8600-50d1702e03a7.png">
