### ISSUE TITLE
Solar Tweaks "Fetch MetaData Error"

### ISSUE THREAD

**Issue by Sushan2589** [Solar-Tweaks/Solar-Tweaks#1058]
I don't know if its a big or a problem from my end but I am getting an unusual error while clicking on launch which is :- 
**[Fetch Metadata Error: AxiosError: Network Error
    at XMLHttpRequest.c.onerror (app://./js/chunk-vendors.05eebfbb.js:52:26734)
    at XMLHttpRequest.r (app://./js/chunk-vendors.05eebfbb.js:33:142922)]**

I downloaded the solar tweaks launcher, I _enabled cracked from engine went to settings downloaded jre and also turned on websocket with the url wss://socket.solartweaks.com that I saw on yt than I launched 1.8.9 and played, It was great. I closed the game and came next day opened Solar tweaks and clicked on launch 1.8.9 than it gives me this error_ and the launch button says 
**Launching......
Fetching Metadata and is stuck**

**Comment by HypedDomi** [comment]
Try launching Lunar first and then SolarTweaks
