### ISSUE TITLE
Stuck At Loading Screen after setup done(only show the solar tweaks logo)

### ISSUE THREAD

**Issue by JustDeyz** [Solar-Tweaks/Solar-Tweaks#1065]
**Describe the bug**
After i do the setup, the solar tweaks app opened but only show the solar tweaks logo

**To Reproduce**
1. Go to solar tweaks setup.exe
2. wait
3. when the setup done the apk showed up
4. then it stuck and only show the solar tweaks logo
5. See error

**Expected behavior**
the loading will be done and i can play Minecraft

**Actual behaviour**
it stuck at loading screen and show the logo

**Screenshots**
![image-5](https://user-images.githubusercontent.com/130642266/231687511-3b9d93e1-5686-47a7-a3c4-aab643f239e5.png)

**Environment (please complete the following information):**
 - OS: [Windows]
 - Launcher Version [eg. 4.3.3]
 - Engine Version 
 - Solar Stats Version (i dont know)

**Comment by HypedDomi** [comment]
Try restarting the launcher. If you still have the same error press CTRL SHIFT I and click in the new Popout Console. Screenshot the red Error

**Comment by JustDeyz** [comment]
![image](https://user-images.githubusercontent.com/130642266/232263750-c5d98bd6-d136-40fd-af74-58e037bdabf2.png)
this one?

**Comment by JustDeyz** [comment]
![image](https://user-images.githubusercontent.com/130642266/232263774-45cb494b-db8b-48e2-9d67-a830111b111a.png)

**Comment by HypedDomi** [comment]
You dont have Lunar installed. Install it and launch it one time and then you can start SolarTweaks

**Comment by HypedDomi** [comment]
Or try starting SolarTweaks ss Admin

**Comment by JustDeyz** [comment]
so... now i have Lunar Client, and i do launch it so many time but the solar tweaks still stuck at the loading screen

**Comment by HypedDomi** [comment]
Screenshot your Console again

**Comment by JustDeyz** [comment]
![image](https://user-images.githubusercontent.com/130642266/232328011-1baaa281-c066-4fcc-96dc-db10347209fb.png)
![image](https://user-images.githubusercontent.com/130642266/232328025-4559344b-1fd3-4a02-a036-aae9d7f63be3.png)

**Comment by HypedDomi** [comment]
You somehow fucked up your Account Permissions. You don't have Access to create new files in the .lunarclient folder

**Comment by JustDeyz** [comment]
umm.. okay... then what should i do?

**Comment by HypedDomi** [comment]
Try starting SolarTweaks as Admin
