### ISSUE TITLE
My cosmetics dont work and i have a premiune

### ISSUE THREAD

**Issue by Chickenmixreal** [Solar-Tweaks/Solar-Tweaks#1068]
The lunar cosmetics doesn't work for me I have premium and I use wss://socket.solartweaks.com
It shows all cosmetics in the fiels but not in game

**Comment by HypedDomi** [comment]
1. Why did you mark it as Enhancement?
2. Please fill out the form next time
3. Send the WebSocket URL you're using

**Comment by Chickenmixreal** [comment]
Its my first time using GitHub that's why I didn't knew and btw I used 

https://solarsocket.solartweaks.com/

**Comment by Chickenmixreal** [comment]
I used it still not working

**Comment by HypedDomi** [comment]
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4

**Comment by Chickenmixreal** [comment]
I can't send cuz the verify doesn't work for me

**Comment by HypedDomi** [comment]
fixing in dc
