### ISSUE TITLE
Cosmetics, emotes not showing up?

### ISSUE THREAD

**Issue by mesked** [Solar-Tweaks/Solar-Tweaks#1072]
I downloaded solar tweaks but the cosmetics and emotes are just not showing up?

Could anyone help me fix this please, thanks!

**Comment by HypedDomi** [comment]
You need to use our WebSocket: `wss://socket.solartweaks.com`
Open our Launcher, then press Engine and scroll down to WebSocket and click Options. Paste the link there

If you're using cracked, then it won't work
