### ISSUE TITLE
Don't start

### ISSUE THREAD

**Issue by DARKANTO** [Solar-Tweaks/Solar-Tweaks#1073]
hi i need the solar purge
it don't start and it won't let me change the version

**Comment by DARKANTO** [comment]
Fetch Metadata Error: AxiosError: Network Error
    at XMLHttpRequest.c.onerror (app://./js/chunk-vendors.05eebfbb.js:52:26734)
    at XMLHttpRequest.r (app://./js/chunk-vendors.05eebfbb.js:33:142922)
    
    
    this is the error

**Comment by HypedDomi** [comment]
Something happened with your Network Connection. That's why it threw the Error.
[SolarPurge](https://cdn.discordapp.com/attachments/979553959624728596/1028683669419855912/SolarPurge.bat) cant fix this. Try launching Lunar first and then SolarTweaks
