### ISSUE TITLE
[Enhancement] Ability to add own Mods to Forge

### ISSUE THREAD

**Issue by its-Jaxx** [Solar-Tweaks/Solar-Tweaks#1075]
How do I go about to add custom mods to Solar-Tweaks? I've tried running with forge as well as skipping checks. But neither seems to do the trick.

**Comment by HypedDomi** [comment]
You can't add your own Mods when you use Lunar. But i make this an Enhancement Thread. Maybe we will add it in the Future

**Comment by Waffles3438** [comment]
If you want custom mods use Weave.
Note: Forge mods will not work, you must use mods available in their discord or create your own with Weave.
https://discord.gg/sHkUN6YygP

**Comment by sharifjameel90** [comment]
Hello you can modify forge mods to work on Lunar by using Weave Api, What is Weave? weave helps to add own mods to lunar client. If you want to Learn more check their GitHub

**Comment by 770grappenmaker** [comment]
> You can't add your own Mods when you use Lunar. But i make this an Enhancement Thread. Maybe we will add it in the Future

I tried supporting it but in any way you do it, integration is sucky no matter what and probably not a good idea.
