### ISSUE TITLE
[Enhancement] Shulkertooltips for 1.19+

### ISSUE THREAD

**Issue by zEw0** [Solar-Tweaks/Solar-Tweaks#1076]
**Is your feature request related to a problem? Please describe.**
Yes, I am tired of not being able to see whats inside my shulker box.

**Describe the solution you'd like**
Add shulkertooltips into Solar-Tweaks

**Additional context**
![image](https://user-images.githubusercontent.com/78274504/232483949-cd54a583-265c-41f2-8be4-ab1aa5a754db.png)

**Comment by 770grappenmaker** [comment]
This is usually considered a cheat.
