### ISSUE TITLE
JVM not starting on macOS 

### ISSUE THREAD

**Issue by Sweethellcat** [Solar-Tweaks/Solar-Tweaks#1078]
When i click on launch it loands then shows starting JVM then it goes back to launch 1.8.9

**Comment by HypedDomi** [comment]
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4
