### ISSUE TITLE
Audio not working....

### ISSUE THREAD

**Issue by sbghfff** [Solar-Tweaks/Solar-Tweaks#1079]
when i launch any version there is no audio even though there is no problem with my headphones pls fixx this or suggest a fix
Thanks

**Comment by HypedDomi** [comment]
Do you have Lunar installed?

**Comment by TheJakobus** [comment]
I got the same problem on Mac

**Comment by HypedDomi** [comment]
> I got the same problem on Mac

Then answer the question instead of saying that you have the same problem. That doesnt help us

**Comment by MertGumus81** [comment]
I have the same problem on Linux, no I don't have Lunar installed

**Comment by HypedDomi** [comment]
Install Lunar

**Comment by MertGumus81** [comment]
It worked, thanks
