### ISSUE TITLE
Cracked account doesn't work on multiplayer 

### ISSUE THREAD

**Issue by norbsdev0** [Solar-Tweaks/Solar-Tweaks#1088]
**Describe the bug**
The cracked account doesn't work on multiplayer for some reason. 

**To Reproduce**
I don't think this can be reproduced as I don't know what happened.
Most likely different launcher interference?

**Expected behavior**

**Actual behaviour**
When you launch the game and go to multiplayer, it gives you the login to microsoft screen.

**Environment (please complete the following information):**
 - OS: MacOS Apple Silicon M2
 - Launcher Version: Latest
 - Engine Version: Unknown

**Additional context**
I've checked logs and nothing came up which is pretty weird

**Comment by GrayBed** [comment]
Yeah i got that too, im waiting till they fix it

**Comment by sxlcoe** [comment]
me too...

**Comment by GrizzlyMann-YT** [comment]
me too

**Comment by HypedDomi** [comment]
https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1100
