### ISSUE TITLE
Cracked account not working 

### ISSUE THREAD

**Issue by JustUseSolar** [Solar-Tweaks/Solar-Tweaks#1089]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by AayushBeura** [comment]
It works just like Lunar Client. Doesn't work for Cracked Accounts !

**Comment by BlackHomoKiller** [comment]
can we contact solar tweaks on discord do they have a discord server??

**Comment by HDarknight** [comment]
Its about LunarClient copyright thing i guess also we can contact solartweaks on their discord server

**Comment by sxlcoe** [comment]
ok but what s the discord server?

**Comment by HypedDomi** [comment]
https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1100

**Comment by Hackerois** [comment]
Describe the bug
Cracked Account is not working

Actual behaviour
Description of what is actually happening.

Environment (please complete the following information):

OS: [e.g. Windows]
Launcher Version [v19]

**Comment by ScoreNoobXD** [comment]
Solar Tweaks, cracked account broken ATM admins will fix it this weekend!
Discord: https://discord.gg/solarsocket

**Comment by Hackerois** [comment]
is cracked account is working now on solar tweaks??
