### ISSUE TITLE
cracked account not working

### ISSUE THREAD

**Issue by Speedisop** [Solar-Tweaks/Solar-Tweaks#1092]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by HDarknight** [comment]
I think Lunarclient did this cuz they don't want to have NOT legit players so SolarTweaks removed this option it is sad but we can't do anything.

**Comment by HypedDomi** [comment]
https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1100

**Comment by andrejco0000** [comment]
i have a problem when i try to go in multiplayer or singleplayer it shows me that i have to migrate a microsoft account can someone tell me how to fix this problem

**Comment by Devashishrj** [comment]
Me too
