### ISSUE TITLE
Cant use cracked account 

### ISSUE THREAD

**Issue by Divyansh6375** [Solar-Tweaks/Solar-Tweaks#1094]
Cant use cracked account even after I enable use cracked account It open like normally and whenever I click single player or multiplayer it just says sign in at microsoft

**Comment by HypedDomi** [comment]
https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1100

**Comment by Divyansh6375** [comment]
Tell something

**Comment by HypedDomi** [comment]
> Tell something

Every Info you need is in the issue i mentioned
