### ISSUE TITLE
Cracked account option on solartweaks not working?

### ISSUE THREAD

**Issue by HDarknight** [Solar-Tweaks/Solar-Tweaks#1095]
Today somany users said they can't play on solartweaks cuz it is not working for cracked users. i have two guesses, one is maybe it's about Lunar copyright stuff and the second one is maybe SolarTweaks is adding something like skin system to this option i don't know. it is sad but you can also contact them in their discord server. :D

**Comment by AayushBeura** [comment]
can you stick in the discord link :p

**Comment by HypedDomi** [comment]
https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1100
