### ISSUE TITLE
cracked account dont work on singleplayer and multiplayer on solartweaks

### ISSUE THREAD

**Issue by savzyt** [Solar-Tweaks/Solar-Tweaks#1096]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by Darkenian** [comment]
its my first time tryna get solartweaks and this is one of the worst first impressions ever

**Comment by andrejco0000** [comment]
I have a problem when i click multiplayer or singleplayer it show that i have to migrate a microsoft account but cracked account is on how do i fix this problem.

**Comment by HypedDomi** [comment]
https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1100
