### ISSUE TITLE
Cracked account not working

### ISSUE THREAD

**Issue by Frab21** [Solar-Tweaks/Solar-Tweaks#1097]
### Discussed in https://github.com/orgs/Solar-Tweaks/discussions/1090

<div type='discussions-op-text'>

<sup>Originally posted by **JustUseSolar** April 22, 2023</sup>
The cracked account i s no longer working </div>

**Comment by HypedDomi** [comment]
https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1100
