### ISSUE TITLE
Cracked account is not working?

### ISSUE THREAD

**Issue by Seraphiable** [Solar-Tweaks/Solar-Tweaks#1099]
I do not understand why cracked account in Solar Tweaks is not working. I have tried multiple time and it have not worked

**Comment by andrejco0000** [comment]
I have a problem when i click multiplayer or singleplayer it show that i have to migrate a microsoft account but cracked account is on how do i fix this problem.

**Comment by HypedDomi** [comment]
https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1100
