### ISSUE TITLE
Lauching Solartweaks Cracked Launch Premium LC

### ISSUE THREAD

**Issue by SKMasterOP** [Solar-Tweaks/Solar-Tweaks#1106]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AnxietyToggled** [comment]
Yeah when i go download Zulu again since it got deleted randomly and Zulu didnt then when i try other JRE it works but when i load it in, in cracked it says i need premium for solar tweaks/lunar client

**Comment by HypedDomi** [comment]
#1100
