### ISSUE TITLE
Can't play as cracked 

### ISSUE THREAD

**Issue by KaustubhOnToaster** [Solar-Tweaks/Solar-Tweaks#1110]
from yesterday I couldnt login into CRACKED servers even after confirming my ign was the same I used to register.
Today I cant even click on single/multi player and asks me to login.
Devs, pwease fix dis

**Comment by n1kst4r192345** [comment]
same bro i also cant

**Comment by LihanRadit** [comment]
me also

**Comment by AnxietyToggled** [comment]
their fixing it but im getting impatient i have to sweat in bridge >:(

**Comment by LihanRadit** [comment]
nope i am playing other games  till it fixes

**Comment by HypedDomi** [comment]
#1100

**Comment by KYSON99** [comment]
#1100 be patient
