### ISSUE TITLE
Cracked account not working

### ISSUE THREAD

**Issue by drake997ita** [Solar-Tweaks/Solar-Tweaks#1111]
hi, I start your client with the cracked account but as soon as I enter the game it tells me that I have to log in with microsoft. Please help me to solve this problem, thanks
-drake997ita

**Comment by LihanRadit** [comment]
me also. The Devs r working on it. I think They will release 4.3.4

**Comment by LihanRadit** [comment]
You can Check This
https://github.com/Solar-Tweaks/Solar-Tweaks

**Comment by drake997ita** [comment]
oke, thanks

**Comment by drake997ita** [comment]
> 

oke thanks

**Comment by drake997ita** [comment]
> You can Check This https://github.com/Solar-Tweaks/Solar-Tweaks
it doesn't work anyway

**Comment by LihanRadit** [comment]
yes but it shows a picture down there is written version 4.3.4 but the letest is 4.3.3 i think they r fixing it. It will be fixed soon.

**Comment by HypedDomi** [comment]
#1100
