### ISSUE TITLE
NOT DOWNLOADING ANY FRICKIN JRE BRO :((  (ZULU,GRAALVM,TEMURIN)

### ISSUE THREAD

**Issue by SmokeV4** [Solar-Tweaks/Solar-Tweaks#1112]
**Not downloading any JRE**
When I go to engine and try to download zulu, graalVM or Temurin, it does not work and if it does work then when i click launch it gets stuck on checking LC assets and then goes back to launch 1.8.9 and does not do anything. I tried reinstalling JAVA and Solartweaks, I also tried reinstalling lunar then installing solar tweaks again

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Download zulu'
4. It does not work

**Expected behavior**
It should have been downloading any of the JRE but it does not for some odd eason

**Environment (please complete the following information):**
 - OS: [Windows]
 - Launcher Version [eg. 4.3.3]

**Additional context**
It just does not work

**Comment by AnxietyToggled** [comment]
yeah it is the same bug as the solar client not going not being cracked

**Comment by HypedDomi** [comment]
> yeah it is the same bug as the solar client not going not being cracked

No? That are 2 diff Processes

**Comment by HypedDomi** [comment]
@SmokeV4 Can you send me your logs? Also keep in mind that the download takes a while based on your Internet speed
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4

**Comment by SmokeV4** [comment]
![image](https://user-images.githubusercontent.com/129429788/233849858-47b19ad2-5456-4273-8cf4-0c46fd00f4ae.png)
Done

**Comment by SmokeV4** [comment]
> @SmokeV4 Can you send me your logs? Also keep in mind that the download takes a while based on your Internet speed
> 
> 1. Open Solar Tweaks and **enable** `Keep Launcher open`
> 2. Try to reproduce the error
> 3. Go to the About tab and click `Download Logs` then click `Open ST directory`
> 4. Drag and drop the `logs.zip` file into discord
> 
>  SolarTweaks_-_Logs.mp4

DONE 
![image](https://user-images.githubusercontent.com/129429788/233849866-75e3a3ee-958a-4a8c-b45e-5ad655e07f87.png)

**Comment by SmokeV4** [comment]
> @SmokeV4 Can you send me your logs? Also keep in mind that the download takes a while based on your Internet speed
> 
> 1. Open Solar Tweaks and **enable** `Keep Launcher open`
> 2. Try to reproduce the error
> 3. Go to the About tab and click `Download Logs` then click `Open ST directory`
> 4. Drag and drop the `logs.zip` file into discord
> 
>  SolarTweaks_-_Logs.mp4

also share how u got the clean macOS theme :D

**Comment by HypedDomi** [comment]
> > @SmokeV4 Can you send me your logs? Also keep in mind that the download takes a while based on your Internet speed
> > 
> > 1. Open Solar Tweaks and **enable** `Keep Launcher open`
> > 2. Try to reproduce the error
> > 3. Go to the About tab and click `Download Logs` then click `Open ST directory`
> > 4. Drag and drop the `logs.zip` file into discord
> > 
> > SolarTweaks_-_Logs.mp4
> 
> also share how u got the clean macOS theme :D

WDYM? Its normal macOS?

**Comment by SmokeV4** [comment]
> > > @SmokeV4 Can you send me your logs? Also keep in mind that the download takes a while based on your Internet speed
> > > 
> > > 1. Open Solar Tweaks and **enable** `Keep Launcher open`
> > > 2. Try to reproduce the error
> > > 3. Go to the About tab and click `Download Logs` then click `Open ST directory`
> > > 4. Drag and drop the `logs.zip` file into discord
> > > 
> > > SolarTweaks_-_Logs.mp4
> > 
> > 
> > also share how u got the clean macOS theme :D
> 
> WDYM? Its normal macOS?

Dude i sent the log on my ticket-xlauncher pls HELP ME :(
