### ISSUE TITLE
Glint Issues

### ISSUE THREAD

**Issue by Quotions** [Solar-Tweaks/Solar-Tweaks#1113]
**Describing the bug**:
_My tool glint is not showing, even if have turned it ON in the solar settings, it does not show the glint inside a gui only shows outside ( like seeing a player with enchanted armor)_

**To Reproduce**:
_I don't know how this happened actually, Try maybe turn it OFF in the lunar settings and then ON again and open your inventory to see if it has a glint._

**Actual behaviour**:
_No tools glint_

**Screenshots**
![image](https://user-images.githubusercontent.com/131556546/233846666-87a7cb13-f2ce-4c1a-8e7d-87a4f52bc7a2.png)
_ Like this screenshot for example_

**Environment:**
 - OS: Windows 10
 - Launcher Version : Lunar client 1.19.2+ (v2.5.1-2316)
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Comment by HypedDomi** [comment]
![image](https://user-images.githubusercontent.com/50876016/233870267-2d4a7a26-4409-4977-8257-4bbb5557f5a3.png)

Cant reproduce. Try updating your Lunar and Solar. If the error still occurs feel free to join our [Discord Server](https://discord.gg/solarsocket) and make a ticket or send your logs here

1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4
