### ISSUE TITLE
My bug or problem is that when I start the game it asks me for an account (If I have activated the option for non-premium users)

### ISSUE THREAD

**Issue by zarpinxd** [Solar-Tweaks/Solar-Tweaks#1116]
My bug or problem is that when I start the game it asks me for an account (If I have activated the option for non-premium users)

the steps i do

1 Open the launcher

2 Click Launch 1.7.10

3 Opens correctly

4 When I press multiplayer, it asks me for an account (I have the non-premium user option active)

expected behavior
Don't ask me for an account to play multiplayer

actual behavior
It asks me for a premium account to play multiplayer

Screenshots
![Captura de pantalla 2023-04-23 203322](https://user-images.githubusercontent.com/131625365/233872313-a818efd2-e3c2-425b-affa-4d64bf3ed8e7.png)
![Captura de pantalla 2023-04-23 203248
![Captura de pantalla 2023-04-23 203057](https://user-images.githubusercontent.com/131625365/233872321-c11c3127-10ad-4a35-92be-407cc793eeb1.png)
](https://user-images.githubusercontent.com/131625365/233872319-eead4c41-01c3-434c-b0ce-61243da38ecb.png)

Operating system: Windows 10
Launcher version: 4.3.3
Patcher version:
Solar stats version: I don't know where that is

**Comment by zarpinxd** [comment]
![Captura de pantalla 2023-04-23 203057](https://user-images.githubusercontent.com/131625365/233872523-fafca080-7731-4c12-9bed-edc2402a83a6.png)

**Comment by HypedDomi** [comment]
#1100

**Comment by zarpinxd** [comment]
Is it solved?
