### ISSUE TITLE
cracked account dosent work

### ISSUE THREAD

**Issue by senpai64444** [Solar-Tweaks/Solar-Tweaks#1117]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by mallusrgreatv2** [comment]
#1100

**Comment by senpai64444** [comment]
hyped domi when i t will fix

**Comment by senpai64444** [comment]
> #1100

when it will fix/

**Comment by HypedDomi** [comment]
Read #1100

**Comment by senpai64444** [comment]
> Read #1100

i have readen but fix time

**Comment by HypedDomi** [comment]
There is None. No ETA

**Comment by senpai64444** [comment]
> There is None. No ETA

means

**Comment by HypedDomi** [comment]
Google it
