### ISSUE TITLE
add heart indector and mods in solar tweks

### ISSUE THREAD

**Issue by senpai64444** [Solar-Tweaks/Solar-Tweaks#1118]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LihanRadit** [comment]
bro it is a bug. The Devs R making a new version 4.3.4. It will be realised soon! Just be patient.

**Comment by HypedDomi** [comment]
Duplicate of https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1039

**Comment by senpai64444** [comment]
> bro it is a bug. The Devs R making a new version 4.3.4. It will be realised soon! Just be patient.

when

**Comment by HypedDomi** [comment]
No ETA

**Comment by HypedDomi** [comment]
What you want is not what he means.
