### ISSUE TITLE
NOT DOWNLOADING ANY FRICKIN JRE BRO :(( U MARKED IT AS CLOSED WHEN IT IS NOT

### ISSUE THREAD

**Issue by SmokeV4** [Solar-Tweaks/Solar-Tweaks#1122]
Not downloading any JRE (IT DID NOT WORK U MARKED IT AS CLOSED BRUH) PLS HELP
When I go to engine and try to download zulu, graalVM or Temurin, it does not work and if it does work then when i click launch it gets stuck on checking LC assets and then goes back to launch 1.8.9 and does not do anything. I tried reinstalling JAVA and Solartweaks, I also tried reinstalling lunar then installing solar tweaks again

To Reproduce

Go to 'Settings'
Click on 'Download zulu'
It does not work
Expected behavior
It should have been downloading any of the JRE but it does not for some odd eason

Environment (please complete the following information):

OS: [Windows]
Launcher Version [eg. 4.3.3]
Additional context
It just does not work

**Comment by HypedDomi** [comment]
Stop creating issues when you already have an open Ticket in our Discord
