### ISSUE TITLE
Cracked Account, Overlays and much more is not working.

### ISSUE THREAD

**Issue by Antinity** [Solar-Tweaks/Solar-Tweaks#1123]
They probably got patched, sadge.
Sad for y'all now u gotta fix it, like please.

**Describe the bug**

**To Reproduce**
1. Go to 'Solar Tweaks'
2. Click on 'Engine'
3. Scroll down to 'Cracked Account' or 'Overlays'
4. Enable them.
5. Launch the game.
6. The cracked account does not work nor the overlays do.

**Expected behavior**

**Actual behaviour**
It should bypass the login wall and allow us to enter multiplayer/singleplayer gui and should allow us to use the overlays.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 11
 - Launcher Version: 4.3.3
 - Engine Version:
 - Solar Stats Version:

**Additional context**
it just doenst works no crash or anything pelase fix i beg u

**Comment by trollfacenan** [comment]
yea same issue

**Comment by HypedDomi** [comment]
#1100
