### ISSUE TITLE
1.8.9 crashing EVERY SINGLE TIME

### ISSUE THREAD

**Issue by teanea** [Solar-Tweaks/Solar-Tweaks#1129]
Any time i launch 1.8.9 it crashes my game, this only started happening after I launched 1.8.9 Lunar Client yesterday. Now every time i Launch Solar Tweaks 1.8.9 it crashes, 1.19.2 doesnt

**Comment by HypedDomi** [comment]
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4

**Comment by HypedDomi** [comment]
Moving this to https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1132
