### ISSUE TITLE
Launcher redesign??

### ISSUE THREAD

**Issue by Axecyy** [Solar-Tweaks/Solar-Tweaks#113]
Self explanatory.

**Comment by RichardDorian** [comment]
The top navigation bar is actually centered but now centered in the window, it's centered between the title and the shortcut/close. What _center_ do you prefeer?

**Comment by 770grappenmaker** [comment]
![image](https://user-images.githubusercontent.com/50543283/166662979-41e78000-fee9-4c34-b40c-48bc86001359.png)
Look, it definitely is centered between the logo and the shortcut and close buttons.
![image](https://user-images.githubusercontent.com/50543283/166663043-1a328cdc-9937-4a73-94ae-93dd6d1ae143.png)
The problem is though, it might not look centered since it is not on the center of the window

**Comment by Axecyy** [comment]
I prefer it to be centered in the absolute center of the window rather than between both shortcut / close and the logo.

**Comment by Axecyy** [comment]
Also you guys should 100% make a custom UI design instead of rely on lunar

**Comment by 770grappenmaker** [comment]
I agree with that last part

**Comment by Axecyy** [comment]
I could make some mockup for you guys

UI and HTML / CSS is my expertise

**Comment by 770grappenmaker** [comment]
Sure go ahead

**Comment by Axecyy** [comment]
![image](https://user-images.githubusercontent.com/98881627/167083407-efeb647b-9fc0-4724-81aa-72da8c1c4c27.png)

I'm obviously not finished judging by no icon navigation bar

By the way these are scroll-able 

![image](https://user-images.githubusercontent.com/98881627/167084134-ac9955a2-d3b5-4136-b435-10ea9a04bf1b.png)

![image](https://user-images.githubusercontent.com/98881627/167084705-57b87687-663f-4184-a458-4a15d36ac347.png)

![image](https://user-images.githubusercontent.com/98881627/167084881-61bf5e7b-dd19-44a2-9bb6-931f33ff7080.png)

I kinda was short on time so if there is something you don't like

I'll send about section in a second, I forgot about it

**Comment by Axecyy** [comment]
update on the about section:
its done.

![image](https://user-images.githubusercontent.com/98881627/167086536-38cbb1c2-9c92-425b-b6be-1cf2ad74c8fa.png)

And I just realized I need to make a patcher. This is painful

**Comment by Axecyy** [comment]
only 34 patcher modifications to go 🤣

**Comment by Axecyy** [comment]
![image](https://user-images.githubusercontent.com/98881627/167092748-6be3143a-1c4a-413d-8ecf-04331044a139.png)
Had to go for a bit, Just now starting work on patcher but I did finish the navbar.

**Comment by Axecyy** [comment]
![image](https://user-images.githubusercontent.com/98881627/167096167-1b162059-2b82-4005-aa73-b4a5ebde511b.png)

Finally.

Yeah so tell me what u dont like

**Comment by RichardDorian** [comment]
What software did you use to create this design? In my opnion the UI looks very cool and it's very clean

**Comment by Khonshulol** [comment]
Damn this looks sick

**Comment by Axecyy** [comment]
> What software did you use to create this design? In my opnion the UI looks very cool and it's very clean

Figma

**Comment by Axecyy** [comment]
> Damn this looks sick

Thanks

**Comment by Axecyy** [comment]
> ![image](https://user-images.githubusercontent.com/98881627/167096167-1b162059-2b82-4005-aa73-b4a5ebde511b.png)
> 
> Finally.
> 
> Yeah so tell me what u dont like

Btw about this I got lazy and decided only to make those things yea

**Comment by 770grappenmaker** [comment]
Woah do you think you can make that using html+css (in vue ig?)

**Comment by RichardDorian** [comment]
Can you give me the link of your figma project?

**Comment by Axecyy** [comment]
> Woah do you think you can make that using html+css (in vue ig?)

I mean I think I can lol

**Comment by RichardDorian** [comment]
That looks very sick! We're going to have a discussion internally but your design is very very interesting.

**Comment by Axecyy** [comment]
> That looks very sick! We're going to have a discussion internally but your design is very very interesting.

Have you decided on what to do yet?

**Comment by RichardDorian** [comment]
Yeah we are very interested. Can you give us your Discord tag (if you have one) so we can discuss there?

**Comment by Axecyy** [comment]
Axecy#4265
