### ISSUE TITLE
The issue i have with solar tweak from  3 days is that the cracked account option is not working,i enabled the feature and typed the cracked username but when i entre the game and click on multiplayer or single player, it asks for a premium mojang or microsoft account. This would'nt happen before but now i don't know whats causing it. Plz fix this issue quickly

### ISSUE THREAD

**Issue by Herohaider999** [Solar-Tweaks/Solar-Tweaks#1130]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by ayanvijai** [comment]
is the bug fixed now ?
