### ISSUE TITLE
Crashing on launch (1.8.9)

### ISSUE THREAD

**Issue by Euro-pol** [Solar-Tweaks/Solar-Tweaks#1132]
**Describe the bug**
Solar Tweaks crashes while loading Minecraft. It seems that the issue occurs after this [commit](https://github.com/Solar-Tweaks/Solar-Engine/commit/bfc881c182483bb9f8fb0f4880eddcec1545791c), since it didn't happen to me yesterday.  
Seems an issue with the bridge, since the exception before the crash is `java.lang.NoClassDefFoundError: Could not initialize class com.solartweaks.engine.bridge.BridgeManager`
**To Reproduce**
1. Launch Solar Tweaks on the latest version (1.8.9)
2. Client will be loading, and when the progress bar is done, crashes.

**Expected behavior**
Client should load normally.

**Actual behaviour**
Client crashes on the "last stage" of loading.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Launcher Version: 4.3.1

**Additional context**
I have the following tweaks on: Cape System (unmodified), No Hit Delay, Privacy, Windows Title  
![image](https://user-images.githubusercontent.com/52547763/234383805-12074940-8ea2-4b66-9ea0-107c4082ed46.png)

[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/11326103/launcher-latest.log)

[1.8.9-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/11326104/1.8.9-latest.log)

**Comment by HypedDomi** [comment]
Can you try this:

![image](https://user-images.githubusercontent.com/50876016/234394913-146f495f-ed87-4972-8591-510ffd60bcc8.png)

**Comment by Euro-pol** [comment]
not fixed sadly

**Comment by norbsdev0** [comment]
It's probably the window title according to your logs, try turning that off

**Comment by lakshay-byte** [comment]
i am also having the same issue on windows 10

**Comment by badger-py** [comment]
Yea I have the same issue on the Ubuntu 20.04 LTS.
But 1.19.2 works great

**Comment by Euro-pol** [comment]
# Temporary fix I found  
1. Enable "Skip Checks" in Solar settings  
2. Download [this](https://github.com/Solar-Tweaks/Solar-Engine/releases/tag/v2.1.1) engine version
3. Navigate to `~/.lunarclient/solartweaks/`  
4. Replace `solar-engine.jar` with the jar  you just downloaded.  

This fixed crashing for me. Keep in mind you won't have new features so we have to wait for a developer response

**Comment by Euro-pol** [comment]
changed issue title since people on windows are getting this too

**Comment by 770grappenmaker** [comment]
Allow me to explain. On linux (no, not on windows), and intel mac, Linux forcibly downgrades users, and I honestly don't know why. I am a windows user (the engine dev, by the way), therefore I cannot test it. I totally forgot about it last update. I will setup a VM and fix it ASAP, but for now I think the very temporary fix is to either downgrade (we are not going to downgrade the engine since then cracked users will whine) or to disable window title, then it will at least launch (still, a lot of things will break). My code assumes the newest version of lunar and will fail when it cannot find the newest stuff.

**Comment by Euro-pol** [comment]
:+1:

**Comment by 770grappenmaker** [comment]
Fixed, will be released in next update of solar engine

**Comment by 770grappenmaker** [comment]
I appreciate the thorough bug report btw, you'd be the first

**Comment by Euro-pol** [comment]
> Fixed, will be released in next update of solar engine

thanks!
