### ISSUE TITLE
i cant login it says add a mincraft account

### ISSUE THREAD

**Issue by vlrum** [Solar-Tweaks/Solar-Tweaks#1135]
**Describe the bug**
i cant log in into the multiplayer and sigleplayer it says log in with minecraft account
**To Reproduce**
1. Go to solor tweaks
2. Click on launch with cracked accounts
3. Scroll down to and select multiplayer 
4. See error it says login with minecraft account 

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by god-Griff** [comment]
have the same problem, anyone got a fix?

**Comment by sharanabc123** [comment]
same issue o you know how to fix it

**Comment by Sapphire-code** [comment]
It's a bug, it should be pushed out but nobody has an ETA of the release for the fix. Just gotta be patient I guess.

**Comment by Sapphire-code** [comment]
Ok, so I launched the solar tweaks client again and it seems to be working.

**Comment by Tanmay0830** [comment]
Still not working it asks for login

**Comment by BensaTV** [comment]
I can't add new accounts. whenever i put in the password the login window closes but no account gets added. I use normal accounts, not even cracked.

**Comment by HypedDomi** [comment]
> I can't add new accounts. whenever i put in the password the login window closes but no account gets added. I use normal accounts, not even cracked.

Add your Accounts with Lunar, not SolarTweaks

**Comment by HypedDomi** [comment]
> Still not working it asks for login

Try updating Lunar
