### ISSUE TITLE
i am unable to use cracked account :(

### ISSUE THREAD

**Issue by sharanabc123** [Solar-Tweaks/Solar-Tweaks#1136]
same issue o you know how to fix it

_Originally posted by @sharanabc123 in https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1135#issuecomment-1522960805_

**Comment by sharanabc123** [comment]
it is asking microsoft login

**Comment by HypedDomi** [comment]
Please try the steps in https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1138
Im also closing this, because https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1138 exists
