### ISSUE TITLE
Solar Tweaks Not Opening

### ISSUE THREAD

**Issue by out2sea88** [Solar-Tweaks/Solar-Tweaks#1140]
Hi I Need A bit of Help with my solar tweaks. when I try to Launch Minecraft with solar tweaks, it does the process but when the Process is done, the Game does not open Up. I don't know why this is happening. I am all ears for any suggestions. Please and thank you.

**Comment by HypedDomi** [comment]
Try this: https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1132#issuecomment-1523661115

**Comment by HypedDomi** [comment]
Im moving this to https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1132

**Comment by out2sea88** [comment]
Plus the client also Doesn't crash because the game doesn't open

**Comment by HypedDomi** [comment]
Same thing. I just don't want like 4 tickets to the same thing
