### ISSUE TITLE
Cosmetics and emotes are not showing in multiplayer

### ISSUE THREAD

**Issue by Herohaider999** [Solar-Tweaks/Solar-Tweaks#1143]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by HypedDomi** [comment]
Known. We publish the fix tmrw

**Comment by Herohaider999** [comment]
Ummm so is it fixed now?

**Comment by HypedDomi** [comment]
Not yet
