### ISSUE TITLE
Zulu is unsupported?

### ISSUE THREAD

**Issue by AnxietyToggled** [Solar-Tweaks/Solar-Tweaks#1144]
When I download it, It doesnt work but last time it worked? How do u fix this

**Comment by HypedDomi** [comment]
Wdym it doesnt work? The download or starting the game?

**Comment by AnxietyToggled** [comment]
no i meant its unsupported when i press download it doesnt download

**Comment by HypedDomi** [comment]
On which OS are you?

**Comment by AnxietyToggled** [comment]
What is an OS. im an 12 year old that only plays minecraft...

**Comment by AnxietyToggled** [comment]
this? 
![image](https://user-images.githubusercontent.com/131573416/235286527-34b3dba9-e0ac-44cd-85fa-8646487425e3.png)

**Comment by HypedDomi** [comment]
The download should work on Windows. It could be that your internet speed is slow. Does the loading indicator appear when you click download?

**Comment by Velocities-lab** [comment]
@HypedDomi Can you fix this bug as soon as possible cuz its very annoying not grinding games

**Comment by HypedDomi** [comment]
Well its hard to debug when i dont have any errors. And it works for like all Users so it’s probably a Error on your end. Do you see the Loading Indicator when you press Download?

**Comment by Velocities-lab** [comment]
> Well its hard to debug when i dont have any errors. And it works for like all Users so it’s probably a Error on your end. Do you see the Loading Indicator when you press Download?

yes and its not working for half of the users i see the comments in yt 
when i click the download it loads and then says "download" again 
If i redownload solar tweaks its the same problem

**Comment by HypedDomi** [comment]
> > Well its hard to debug when i dont have any errors. And it works for like all Users so it’s probably a Error on your end. Do you see the Loading Indicator when you press Download?
> 
> yes and its not working for half of the users i see the comments in yt when i click the download it loads and then says "download" again If i redownload solar tweaks its the same problem

Can you open your Console (CTRL SHIFT I then Console Tab) and screenshot any red error when youre clicking on download

**Comment by Velocities-lab** [comment]
> > > Well its hard to debug when i dont have any errors. And it works for like all Users so it’s probably a Error on your end. Do you see the Loading Indicator when you press Download?
> > 
> > 
> > yes and its not working for half of the users i see the comments in yt when i click the download it loads and then says "download" again If i redownload solar tweaks its the same problem
> 
> Can you open your Console (CTRL SHIFT I then Console Tab) and screenshot any red error when youre clicking on download

I didnt understand do you want me to take screen shot of the jre?

**Comment by HypedDomi** [comment]
I want that you take a screenshot if this:
![image](https://user-images.githubusercontent.com/50876016/235941963-24bd3284-9838-4548-8ae2-bccbfa6c0683.png)

**Comment by Velocities-lab** [comment]
![image](https://user-images.githubusercontent.com/132279511/236113732-282eb256-a9a1-462b-a80f-cfc4a854d596.png)

**Comment by CallMeSpark** [comment]
@Velocities-lab open the launcher then press CTRL SHIFT then console tab then click on download then it didn't download and shows download option again then send the console pic.

**Comment by Velocities-lab** [comment]
![image](https://user-images.githubusercontent.com/132279511/236224681-cbc8cf2c-8126-495d-97ca-10ceaa5ee94a.png)
![image](https://user-images.githubusercontent.com/132279511/236224752-fb546f82-0079-459e-b648-bc67977f601c.png)
![image](https://user-images.githubusercontent.com/132279511/236224827-f4b2e546-759e-4254-a2d5-288cfbd23d38.png)
![image](https://user-images.githubusercontent.com/132279511/236224872-776c1a4b-d19f-45d2-bd16-4d65dbda98f5.png)

**Comment by Velocities-lab** [comment]
i can clearly see in the 2nd screenshot i sent says "Failed to extract zulu"

**Comment by HypedDomi** [comment]
Yeah. Somehow the launcher don't have Permissions to create a new Folder. Can you try starting SolarTweaks as Admin?

**Comment by 770grappenmaker** [comment]
This can only happen if either of these things happened
- you messed with windows perms
- windows caches the fps wrong and you need a reboot

**Comment by CallMeSpark** [comment]
> Yeah. Somehow the launcher don't have Permissions to create a new Folder. Can you try starting SolarTweaks as Admin?

Not working....still same problem

**Comment by CallMeSpark** [comment]
> Yeah. Somehow the launcher don't have Permissions to create a new Folder. Can you try starting SolarTweaks as Admin?

Yeah it worked it didn't show Zulu downloaded option but the folder is created and i can play!
