### ISSUE TITLE
launcher asks for jar 

### ISSUE THREAD

**Issue by ShirefReda** [Solar-Tweaks/Solar-Tweaks#1148]
if i clicked download default jar it just stuck

![image](https://user-images.githubusercontent.com/91873517/235224441-ff040736-d52c-4853-bc2b-c7fde78f8305.png)

![image](https://user-images.githubusercontent.com/91873517/235224362-62ce7b0c-e457-47be-b607-132a314ace69.png)

**Comment by RichardDorian** [comment]
Definitely not an issue. Click `Download Default JRE`. If you need further help, please ask in Solar Socket's Discord Server [here](https://discord.gg/SolarSocket).
