### ISSUE TITLE
You can zoom out in solar tweaks, but not zoom in

### ISSUE THREAD

**Issue by dangamerx7** [Solar-Tweaks/Solar-Tweaks#115]
You cannot zoom **in** solar tweaks, but you can zoom **out**.

*To Reproduce*
1. Go to Solar Tweaks
2. Press Ctrl + 
3. Try to zoom in by pressing Ctrl  -
4. It does not work

*Expected behavior*
It is suppose to Zoom in when pressing Ctrl -
*Actual behaviour*
It is not zooming in.

*Screenshots*
![image](https://user-images.githubusercontent.com/67916789/166503917-8cfcee09-a41e-4f04-9f76-4553831e7585.png)

*Environment*
OS : Windows
Launcher Version : 4.0.2

**Comment by RichardDorian** [comment]
You are not supposed to zoom in the first place, how did you get the zoom out working?

**Comment by dangamerx7** [comment]
> You are not supposed to zoom in the first place, how did you get the zoom out working?

idk i just pressed Ctrl +

**Comment by dangamerx7** [comment]
> > You are not supposed to zoom in the first place, how did you get the zoom out working?
> 
> idk i just pressed Ctrl + .

i cant play solar client lmao now

**Comment by 770grappenmaker** [comment]
CTRL + plus should zoom in
CTRL + minus should zoom out
CTRL + zero (0) should zoom to 100 percent (default, normal, etc.)

**Comment by 770grappenmaker** [comment]
Ok, I just tested, apparently ctrl + plus got blocked, try pressing CTRL + 0, worked perfectly for me

**Comment by dangamerx7** [comment]
> Ok, I just tested, apparently ctrl + plus got blocked, try pressing CTRL + 0, worked perfectly for me

thank you. i hope you have a good day/night
