### ISSUE TITLE
When I start 1.8.9 it crashes every time after finalizing(video attached)

### ISSUE THREAD

**Issue by Vibhor2008** [Solar-Tweaks/Solar-Tweaks#1150]
**Describe the bug**
When I start 1.8.9 it crashes every time after showing finalizing and shows error code :- CRASH-f580e664-b28c-4e3d-b7b6-3ac79fccf938

**To Reproduce**
Start 1.8.9 like we do normally on solar tweaks.
**Expected behavior**
I expected it to work normally.

**Actual behaviour**
It is not opening and crashing evrytime with error code :- CRASH-f580e664-b28c-4e3d-b7b6-3ac79fccf938

**Screenshots**
I have attached a full video of the bug/error

**Environment (please complete the following information):**
 - OS: Windows 11 pro
 - Launcher Version: 4.3.3
 - Engine Version
 - Solar Stats Version

https://user-images.githubusercontent.com/89649830/235288989-8930fb09-a787-4155-99b7-acc4bf575d25.mp4

**Comment by Vibhor2008** [comment]
Plz repair it as soon as possible.

**Comment by Euro-pol** [comment]
#1132
