### ISSUE TITLE
Game never starts

### ISSUE THREAD

**Issue by demonite87x** [Solar-Tweaks/Solar-Tweaks#1153]
After i click the launch button the launcher hides itself but the game never loads, on task manager it gradually reduces its ram usage to the point where it just uses 90 mb. Trying to launch the console works but after a while it just crashes

Environment:
 - OS: Windows 11
 - Launcher Version: 4.3.3

**Comment by HypedDomi** [comment]
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4
