### ISSUE TITLE
Solar tweaks stuck on Checking Game Files (9)...

### ISSUE THREAD

**Issue by ScoreNoobXD** [Solar-Tweaks/Solar-Tweaks#1155]
when i try to open solar tweaks its stuck on checking game files 
![image](https://user-images.githubusercontent.com/130339835/235427186-4ba27977-0e71-4d14-a55b-16b55d810479.png)
pls fix

**Comment by HypedDomi** [comment]
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4
