### ISSUE TITLE
Zulu Download Buffed

### ISSUE THREAD

**Issue by Velocities-lab** [Solar-Tweaks/Solar-Tweaks#1157]
Please fix this fast as possible

**Comment by Velocities-lab** [comment]
Hello My jre zulu download is buffed it says "download" again and again when i try downloading it

**Comment by HypedDomi** [comment]
On which OS are you?

**Comment by Velocities-lab** [comment]
> On which OS are you?

Im on windows 10 and this is happening from yesturday morning

**Comment by Velocities-lab** [comment]
So what really happened is my solar tweaks was stuck at "starting jvm" so i redownloaded the zulu from jre and it just buffed now i cant launch solar tweaks

**Comment by CallMeSpark** [comment]
#1144

**Comment by Velocities-lab** [comment]
ik i did its still same i tried redownloading solar tweaks and lunar client and still the jre aint downloading

> Check #1144

and there is no solution in #1144

**Comment by CallMeSpark** [comment]
Hmm....same happening with me rn @Velocities-lab

**Comment by HypedDomi** [comment]
> ik i did its still same i tried redownloading solar tweaks and lunar client and still the jre aint downloading
> 
> > Check #1144
> 
> and there is no solution in #1144

Not yet. But it's the same issue. So I'll combine the issues. Please use #1144

**Comment by Velocities-lab** [comment]
ok

> > ik i did its still same i tried redownloading solar tweaks and lunar client and still the jre aint downloading
> > > Check #1144
> > 
> > 
> > and there is no solution in #1144
> 
> Not yet. But it's the same issue. So I'll combine the issues. Please use #1144
