### ISSUE TITLE
Launcher stuck in Splash

### ISSUE THREAD

**Issue by Bishal3211** [Solar-Tweaks/Solar-Tweaks#1165]
Hi I cannot launch solar tweaks

**To Reproduce**
1. Launch Solar Tweaks
3. See error

**Expected behavior**
I expected solar tweaks to launch like it would normally do.

**Actual behaviour**
Solar Tweaks is stucked in its logo.

**Screenshots**
![image](https://user-images.githubusercontent.com/68767968/235955728-680e9c58-ce22-4f04-b07d-d1cb390bc75f.png)

**Environment (please complete the following information):**
 - OS: [Windows 11]
 - Launcher Version [4.3.3]
 - Engine Version (idk)
 - Solar Stats Version (idk)

**Comment by HypedDomi** [comment]
Open Dev Tools (CTRL SHIFT I) and go to the Console Tab. Screenshot any red Error
