### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by redx1380** [Solar-Tweaks/Solar-Tweaks#1166]
**Describe the bug**
Audio is not working even when the logs.zip is put into git hub

**To Reproduce**
unexpected error

**Expected behavior**
After the logs.zip was removed it should have worked but is not working

**Actual behaviour**
The audio is not responding even when the steps in video was done.

**Screenshots**

**Environment (please complete the following information):**
 - OS:  Windows
 - Launcher Version [eg. 4.3.3]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)
[logs.zip](https://github.com/Solar-Tweaks/Solar-Tweaks/files/11395389/logs.zip)

**Comment by HypedDomi** [comment]
Sending the logs is not a Fix. It just helps us to debug the issue

**Comment by 770grappenmaker** [comment]
Audio not working means you need to launch normal lunar in the same game dir on the same version
