### ISSUE TITLE
Zulu dont work ???

### ISSUE THREAD

**Issue by THEPOTATOKINGQQ** [Solar-Tweaks/Solar-Tweaks#1168]
**Describe the bug**
Zulu in 1.8.9 and 1.19 dont work idk

**Comment by THEPOTATOKINGQQ** [comment]
idk because im triying to open and no idk please help

**Comment by HypedDomi** [comment]
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into GitHub

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4

**Comment by THEPOTATOKINGQQ** [comment]
ok

**Comment by HypedDomi** [comment]
Can you still send your logs

**Comment by Velocities-lab** [comment]
> 1. Open Solar Tweaks and **enable** `Keep Launcher open`
> 2. Try to reproduce the error
> 3. Go to the About tab and click `Download Logs` then click `Open ST directory`
> 4. Drag and drop the `logs.zip` file into GitHub
> 
>  SolarTweaks_-_Logs.mp4

i did not get you from the 3rd one

**Comment by HypedDomi** [comment]
Follow the Video then

**Comment by Velocities-lab** [comment]
Ok i did everything accpt i cant sent f request in discord so i am giving my username pls add me 
__𝓥𝓮𝓵☯𝓬𝓲𝓽𝓲𝓮𝓼__#1195

**Comment by HypedDomi** [comment]
Please send the file here. Other People can help then too
