### ISSUE TITLE
Vape V4 Overlay

### ISSUE THREAD

**Issue by Cyruslin001** [Solar-Tweaks/Solar-Tweaks#1169]
I just want to make it look like I'm using vape.

Adding a Vape V4 overlay that shows cheats like aimbot, click assist, velo, etc.
 
![image](https://user-images.githubusercontent.com/63165856/236338328-4ff2d76f-aa3b-487b-99e6-367249798a57.png)

**Comment by 770grappenmaker** [comment]
Solar Engine now has a modding api, in which you can pretty easily DIY!

**Comment by 770grappenmaker** [comment]
Either way I will not make this myself, feel free to ask about the modding api though
