### ISSUE TITLE
Everyone with same skin 

### ISSUE THREAD

**Issue by Tlxas** [Solar-Tweaks/Solar-Tweaks#1170]
I logged into Solar Tweaks tonight and noticed that everyone was using the same skin. I thought it was the outdated lunar or using skin changer but it wasn't that. I opened lunar and restarted Solar Tweaks, but it still with the bug, I uninstalled and reinstalled, had the same result. I don't know what it could be, if it's my computer or if it's buggy yet, I looked on the issues topics anyone else had this problem before reporting this bug.

Notes: I use windows 11 22H2.

updated drivers.

When I enter a server normal player's skin appears but around 0.5 seconds it returns to Steve's skin with a cat costume.

I use a cracked account and the cracked skin slot is empty, there is nothing.

Default WebSocket.

Maybe it's something on my pc, but to make sure I opened this topic. If you are sure that it is not a Solar error, I'm sorry, I just need to solve it.
 
Google translator.

Some images:
![image](https://user-images.githubusercontent.com/132628825/236360455-eb64046a-7d9c-4504-83de-4d6fa22ea3a2.png)
![image](https://user-images.githubusercontent.com/132628825/236360477-2a2e9f7c-564d-455c-bb18-b806c3d12c2c.png)
![image](https://user-images.githubusercontent.com/132628825/236360484-5c1b3140-f7b3-48f2-becb-e21a67284b90.png)
![image](https://user-images.githubusercontent.com/132628825/236360489-ae194d62-2656-4b3f-aa0d-c8729e16347b.png)
![image](https://user-images.githubusercontent.com/132628825/236360497-fd1bc170-d1ef-4193-87d6-c36efd10f3ac.png)
![image](https://user-images.githubusercontent.com/132628825/236360500-3ac1a7bb-44cb-4ece-9a9d-d384d6b5df31.png)
![image](https://user-images.githubusercontent.com/132628825/236360505-5beab54e-daa6-4c21-b768-b11d826d415b.png)

**Comment by Tlxas** [comment]
I put a name of a namemc player in the cracked skin tab and by coincidence the skin also went to other players.

Name: Bruhdows
![image](https://user-images.githubusercontent.com/132628825/236361993-4a9ca803-8884-4fe7-af2a-7d93629f8310.png)

**Comment by Drixxytec** [comment]
> I logged into Solar Tweaks tonight and noticed that everyone was using the same skin. I thought it was the outdated lunar or using skin changer but it wasn't that. I opened lunar and restarted Solar Tweaks, but it still with the bug, I uninstalled and reinstalled, had the same result. I don't know what it could be, if it's my computer or if it's buggy yet, I looked on the issues topics anyone else had this problem before reporting this bug.
> 
> Notes: I use windows 11 22H2.
> 
> updated drivers.
> 
> When I enter a server normal player's skin appears but around 0.5 seconds it returns to Steve's skin with a cat costume.
> 
> I use a cracked account and the cracked skin slot is empty, there is nothing.
> 
> Default WebSocket.
> 
> Maybe it's something on my pc, but to make sure I opened this topic. If you are sure that it is not a Solar error, I'm sorry, I just need to solve it.
> 
> Google translator.
> 
> Some images: ![image](https://user-images.githubusercontent.com/132628825/236360455-eb64046a-7d9c-4504-83de-4d6fa22ea3a2.png) ![image](https://user-images.githubusercontent.com/132628825/236360477-2a2e9f7c-564d-455c-bb18-b806c3d12c2c.png) ![image](https://user-images.githubusercontent.com/132628825/236360484-5c1b3140-f7b3-48f2-becb-e21a67284b90.png) ![image](https://user-images.githubusercontent.com/132628825/236360489-ae194d62-2656-4b3f-aa0d-c8729e16347b.png) ![image](https://user-images.githubusercontent.com/132628825/236360497-fd1bc170-d1ef-4193-87d6-c36efd10f3ac.png) ![image](https://user-images.githubusercontent.com/132628825/236360500-3ac1a7bb-44cb-4ece-9a9d-d384d6b5df31.png) ![image](https://user-images.githubusercontent.com/132628825/236360505-5beab54e-daa6-4c21-b768-b11d826d415b.png)

maybe that's a cracked solar tweaks error? oh and i saw you were playing on a brazilian server or portuguese
so oi mn XD

**Comment by Drixxytec** [comment]
actually probably you changed something you should not have

**Comment by elimanator** [comment]
yeah i am having the same problem and also that is the same skin that everybuddy use idk how to fix it

**Comment by elimanator** [comment]
> actually probably you changed something you should not have

no i think it is a bug it was fine yesterday but when i try it today everybuddy have same skin

**Comment by HypedDomi** [comment]
This is a Engine Issue. We may have a fix for it

**Comment by Drixxytec** [comment]
i think it got fixed

**Comment by elimanator** [comment]
> i think it got fixed

nop it didnt
