### ISSUE TITLE
Big Problem (lunar message.)

### ISSUE THREAD

**Issue by Drixxytec** [Solar-Tweaks/Solar-Tweaks#1173]
So lunar keeps saying to uninstall solar tweaks immediately
it says that Solar Tweaks is breaking the lunar client TOS so i am not sure
if i should delete it or **not?**

**Comment by HypedDomi** [comment]
That is up to you. We're currently talking with Lunar about this

**Comment by Drixxytec** [comment]
i wont delete it since solar tweaks is pretty much better with its tweaks
