### ISSUE TITLE
Everyone with same skin

### ISSUE THREAD

**Issue by elimanator** [Solar-Tweaks/Solar-Tweaks#1174]
When i started playing today everybuddy had the same skin. i dont know how to fix it. I tryed reinstalling lunar and solartweaks but it is tha same. It was fine when i was playing yesterday the bug came today. pls how to fix?

**Comment by Drixxytec** [comment]
hey elimanator someone already reported this nobody knows how to fix

**Comment by Drixxytec** [comment]
its **_confusing_**
