### ISSUE TITLE
[Enhancement] Make SolarTweaks a own Client

### ISSUE THREAD

**Issue by Drixxytec** [Solar-Tweaks/Solar-Tweaks#1175]
i'd request you guys make solar tweaks an actual like client client not really like an tweak for lunar
you guys should use the same assets but everything that has lunar on it becomes Solar
and basically you guys could make it so we the community could add fabric and forge mods to the client.

**Comment by HypedDomi** [comment]
That's pretty hard since we need to remake SolarTweaks from Scratch. And we only have 1 Java Dev atm. But we're looking into this

**Comment by Drixxytec** [comment]
:O

**Comment by Drixxytec** [comment]
> That's pretty hard since we need to remake SolarTweaks from Scratch. And we only have 1 Java Dev atm. But we're looking into this request

makes sense
