### ISSUE TITLE
Microsoft Account Not Working.

### ISSUE THREAD

**Issue by EvilClownIDK** [Solar-Tweaks/Solar-Tweaks#1176]
Hello Sir,
This report is this way:-
Sir, I have been trying for like an hour to sign in in Solar Tweaks but whenever I sing in a notification pops up and says that Signed in but it doesn't show on the top-left profile corner and whenever I click on Singleplayer or Multiplayer, it again asks to sign in. So, I request you to kindly tell me that what should I do?
Thankyou.

**Comment by HypedDomi** [comment]
Make sure youre on the latest Lunar Version:
1. Launch Lunar Client with the version you want to play on 
2. When it's fully loaded, close it
3. Launch Solar Tweaks on that version

And make sure that you dont have Cracked Accounts enabled
