### ISSUE TITLE
Lunar Detecting Solar Tweaks

### ISSUE THREAD

**Issue by ProJakob** [Solar-Tweaks/Solar-Tweaks#1179]
**Is your feature request related to a problem? Please describe.**
Lunar Client seems to be detecting Solar Tweaks and is sending an all Caps message with the Text "SOLAR TWEAKS IS IN VIOLATION OF LUNAR CLIENTS TOS. UNINSTALL IMMEDIATELY!"

**Describe the solution you'd like**
I dont know if there is a fix. But would be cool if there was a way to remove this.

**Describe alternatives you've considered**
Nothing really. Great work. Thank You!

**Edit**
This was found on 1.19.4-Sodium (Build v2.5.4-2318)
I'm using the default Lunar Socket.

**Additional context**
Screenshot of the Warning
![Screenshot of the Warning](https://user-images.githubusercontent.com/70058737/236471046-8648fbb5-3177-4048-a1b8-70b61b1b877e.png)

**Comment by 770grappenmaker** [comment]
We know. More info later.
