### ISSUE TITLE
mac support and options to downgrade lunar client

### ISSUE THREAD

**Issue by Applei7** [Solar-Tweaks/Solar-Tweaks#122]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 770grappenmaker** [comment]
1. Mac is supported, we solely haven't built 4.0.2 yet

**Comment by dtomvan** [comment]
Old versions of the Lunar Client launcher are available if you change the download link to the version you want.

If you mean the version of the client itself, you cannot get old versions after updating, because of the way Lunar Client "protects" downloads.

**Comment by Khonshulol** [comment]
There is no way to downgrade to an older version of lunar client cuz distributing it is illegal.
The Solar Tweaks Dev Team is working on adding support.
