### ISSUE TITLE
Resourcepack browser

### ISSUE THREAD

**Issue by Endstarky** [Solar-Tweaks/Solar-Tweaks#127]
**Is your feature request related to a problem? Please describe.**
Hi, a new feature idea I would like to share is that to make a mod or client addon which will browse resourcepack folder to another directory. As an example like I have my main clients resourcepacks in its' client folder now I would like to have a mod/addon which can browse a specific folder related to resourcepacks in anywhere in the computer because for myself copying and pasting those many resource packs(2.5 GB) to another place for the sake of playing but on another client is really a waste of storage.
I don't know about any mod that can do this type of things but hope you know or can create.

**Describe the solution you'd like**
Create a feature like stated above.

**Describe alternatives you've considered**

**Additional context**
Thank you 🙂! The implement of this feature would be really useful and unique to Solar tweaks !

**Comment by Axecyy** [comment]
Pretty sure the mod you're talking about is only available for fabric.

And that's the problem, Lunar does not use fabric (nor does Solar Tweaks).

I also don't remember what the mod is called (but I have used it before) but I'm very sure it's a fabric only mod.

**Comment by Endstarky** [comment]
> Pretty sure the mod you're talking about is only available for fabric.
> 
> And that's the problem, Lunar does not use fabric (nor does Solar Tweaks).
> 
> I also don't remember what the mod is called (but I have used it before) but I'm very sure it's a fabric only mod.

Is it possible for the devs to create one as I think it's still simple being myself not able to code.

**Comment by 770grappenmaker** [comment]
If anyone can send the fabric mod? I'm not entirely sure what the goal is here

**Comment by dtomvan** [comment]
On linux (I get that you are probably not on linux) you can link two directories, so both folders will share the same resource packs, without having to copy them.

On windows you may be able to use shortcuts, but I don't know enough about windows to know for sure if it'll work.

**Comment by Endstarky** [comment]
> On linux (I get that you are probably not on linux) you can link two directories, so both folders will share the same resource packs, without having to copy them.
> 
> On windows you may be able to use shortcuts, but I don't know enough about windows to know for sure if it'll work.

In solar tweaks setting I can brows directories for different versions but if I do so (browse to another clients directory)  then every launch it might break maybe

**Comment by Endstarky** [comment]
> If anyone can send the fabric mod? I'm not entirely sure what the goal is here

The goal is here to get an add on which can browse to another resourcepack directory so we don't need to copy paste resourcepack for every client. As for some of us those folders are huge like for myself it's 2.5 gb
