### ISSUE TITLE
solar tweaks does not do anyting

### ISSUE THREAD

**Issue by Ahmed21321** [Solar-Tweaks/Solar-Tweaks#128]
solar tweaks does not do anyting and when I launch it just launches lunar client
freelook does not work on hypixel and everyother mod on solart tweaks

**Comment by dtomvan** [comment]
Does the window title say "Lunar Client" or "Solar Tweaks"? Also, please provide your logs (in the launcher you can click on About -> Open solar tweaks folder) when submitting a bug report.

**Comment by MopigamesYT** [comment]
I have the same thing, the window says Modded by Solar Tweaks but a lot of mods are broken like freelook or the websocke
[1.8-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8647175/1.8-latest.log)
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8647176/launcher-latest.log)

**Comment by 770grappenmaker** [comment]
@MopigamesYT You somehow managed to break your configuration file, therefore it cannot be parsed. Try deleting your config.json inside of the st dir

**Comment by Ahmed21321** [comment]
OK here is my log files
[1.8-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8660403/1.8-latest.log)
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8660404/launcher-latest.log)

**Comment by Ahmed21321** [comment]
and the window says "Lunar Client"

**Comment by 770grappenmaker** [comment]
You enabled skip checks so it isn't downloading the patcher at all. Disable skip checks

**Comment by Ahmed21321** [comment]
should I reinstall solar tweaks ?

**Comment by 770grappenmaker** [comment]
Nah send the new logs

**Comment by Hardik1796** [comment]
i also have the same problem and my config.json is also broken like you said and my new logs after deleting the config file and running the solar tweaks is also sam
[1.8-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8694247/1.8-latest.log)
e

**Comment by Ahmed21321** [comment]
okay here is my new log files
[1.8-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8695112/1.8-latest.log)
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8695114/launcher-latest.log)

**Comment by Hardik1796** [comment]
i found something similar in yours and mine launcher log it says error could not connect to network but my network is working fine what about yours?

**Comment by 770grappenmaker** [comment]
I think you just don't have the patcher, because of #171

**Comment by Ahmed21321** [comment]
ah okay 
I will wait for the api
