### ISSUE TITLE
solar tweaks not working with my lunar

### ISSUE THREAD

**Issue by 6rave** [Solar-Tweaks/Solar-Tweaks#131]
i was just wondering whats happening to my solar tweaks client since it never really does launch solar tweaks (lunar client modded w/ solar tweaks). for instances, i have lunar client version 2026cf (christmas update), and it never ever launches. i use GraalVM as my JRE and aswell as its JVM arguments. ive deleted, and re-installed it many times, i was just wondering what the problem is. would appreciate a response, thanks.

_**edit: im willing to show logs if needed**_

**Comment by Khonshulol** [comment]
Can you please give me your pc specifications?
Also, you probably should update lunar client to its latest version as lunar did fix its bugs and stuff.
Couleur deprecated GraalVM from CTT becuase it has been causing issues recently.
Also, make sure to check your jvm arguments and try removing each term and restarting lunar. Some argument might be the issue. 
Also, if all of these dont work, then show the logs.

**Comment by 770grappenmaker** [comment]
Can you attach logs, and make sure you selected the `bin` folder of the jre?

**Comment by 6rave** [comment]
> Can you please give me your pc specifications? Also, you probably should update lunar client to its latest version as lunar did fix its bugs and stuff. Couleur deprecated GraalVM from CTT becuase it has been causing issues recently. Also, make sure to check your jvm arguments and try removing each term and restarting lunar. Some argument might be the issue. Also, if all of these dont work, then show the logs.

**_Edit: My PC specs are a Ryzen 3200g, GTX1050Ti (palit), single kit of 8gb cl16 3200mhz for my ram, 240gb SSD, 1 TB HDD_**

**Comment by 770grappenmaker** [comment]
Okay, multiple problems arise here:
1. You should disable Skip Checks
2. You should make sure your java version is 64 bit
3. Make sure you don't specify any -Xmx -Xms arguments in the jvm args (that is probably the root cause)

**Comment by 6rave** [comment]
> Okay, multiple problems arise here:
> 
> 1. You should disable Skip Checks
> 2. You should make sure your java version is 64 bit
> 3. Make sure you don't specify any -Xmx -Xms arguments in the jvm args (that is probably the root cause)

alright i've done 1 and 2 right, but for number 3, how exactly do i remove the "-Xmx" "-Xms" thingies? here is what I use (via GraalVM) 

![image](https://user-images.githubusercontent.com/105028564/167513989-9a1bd8dc-0779-4406-853a-46e84e1c27d3.png)

**Comment by 6rave** [comment]
@770grappenmaker still waiting for a response.

**Comment by 770grappenmaker** [comment]
Okay so that does not look like you are using solar tweaks are you? Remove -Xmx3g -Xms3g and attach logs (st directory)

**Comment by 6rave** [comment]
i removed the things u said. i have 3250 MB allocated to it, chose the bin file for my JRE (GraalVM), and this is the result.

![image](https://user-images.githubusercontent.com/105028564/168182348-521ccb91-ec6a-4a9b-8adc-2ee1b365e6bc.png)

here are the logs

[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8683024/launcher-latest.log)
[1.8-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8683025/1.8-latest.log)

**Comment by 770grappenmaker** [comment]
Enable keep launcher open and resend 1.8 logs after launch

**Comment by 6rave** [comment]
> Enable keep launcher open and resend 1.8 logs after launch

still crashed, but here are the new logs:

[1.8-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8696860/1.8-latest.log)
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8696861/launcher-latest.log)

**Comment by 6rave** [comment]
waiting for a response. @770grappenmaker

**Comment by 770grappenmaker** [comment]
That can only happen whine classes aren't the way solar patcher expects, and since it says "Lunar Client unknown" as the version, something is definitely not right. Are you using an old version of lunar?

**Comment by 770grappenmaker** [comment]
Oh I did send a response it just didn't save this. It says that the version is "unknown" which means you are on an older version of lunar client which was released before solar patcher was made, is this correct?

**Comment by 6rave** [comment]
> That can only happen whine classes aren't the way solar patcher expects, and since it says "Lunar Client unknown" as the version, something is definitely not right. Are you using an old version of lunar?

yes indeed i am using an old version of lunar client, as seen from the images and the statements ive sent above this conversation.

**Comment by 770grappenmaker** [comment]
I think after the christmas update lunar changed some things on their obfuscation and class structure/internals. Therefore solar patcher is incompatible since it doesnt expect the old version

**Comment by 770grappenmaker** [comment]
There are ways for me to make it compatible but i dont have the old jars and it is just a lot of work for barely anything right?

**Comment by 6rave** [comment]
> There are ways for me to make it compatible but i dont have the old jars and it is just a lot of work for barely anything right?

welp, seems like i can't do anything about it but hope that solar would support older versions of lunar soon. thank you very much for responding throughout this conversation, i may have not used solar tweaks, but all i gotta say is their response team is very good and considerate, thanks man. ;)
