### ISSUE TITLE
False Invalid JRE Detection

### ISSUE THREAD

**Issue by he3als** [Solar-Tweaks/Solar-Tweaks#134]
**Describe the bug**
I am trying to use my own custom JDK (GraalVM Enterprise) to use with Solar Tweaks, but it is saw as invalid, even though it works fine with LCLPy.

**To Reproduce**
1. Get GraalVM Enterprise Java 17 22.0.0.2 from Oracle
2. Try to launch the game with the JDK selected
3. Look at the message

**Expected behavior**
I expected it to work fine.

**Actual Behaviour**
Description of what is actually happening.

**Screenshots**

**Environment:**
 - OS: Windows 10 21H2
 - Launcher version: 4.0.2
 - Patcher version: Whatever is included with 4.0.2

**Note:**
I have tried to check if somehow spaces in the path of the JRE/JDK would mess up the detection, but that is not the case. If this can not be fixed, then maybe the checking could be customized to disable specific parts like checking the JRE/JDK?

**Comment by he3als** [comment]
Actually figured out that you need to select the 'bin' folder in your JDK folder. Maybe there could be a note or detection to fix this?

**Comment by 770grappenmaker** [comment]
There is a note
![image](https://user-images.githubusercontent.com/50543283/167206522-772140d4-bdae-442c-8029-799201dd086f.png)
in the selection screen, and it also gives a popup on the new version with an invalid jre

**Comment by he3als** [comment]
It should be more clear as most people do not look at the window title of the file picker. Maybe there could be a note in the 'Invalid JRE' message that it may be in valid due to the selected JRE folder not being `bin`.

**Comment by Khonshulol** [comment]
Yeah ig Richard will work on that

**Comment by 770grappenmaker** [comment]
IMO can be merged, awaiting approval of cy0ze
