### ISSUE TITLE
Incorrect Icon Scaling

### ISSUE THREAD

**Issue by he3als** [Solar-Tweaks/Solar-Tweaks#135]
**Describe the bug**
At least on Windows, the Solar Tweaks icon is scaled incorrectly and looks distorted in the taskbar, File Explorer, etc...

**To Reproduce**
1. Open Solar Tweaks on Windows
2. Look at your taskbar

**Expected behavior**
I expected the logo to look properly scaled like Lunar Client.

![image](https://user-images.githubusercontent.com/65787561/167187390-4b9a6a5c-fc8d-4d68-9aee-50116bd99b5f.png)

**Environment (please complete the following information):**
 - OS: Windows 10 21H2
 - Launcher version 4.0.2

**Comment by 770grappenmaker** [comment]
I don't really know why this happens but it is probably a minor scale issue indeed. Might want to rerender the svg...

**Comment by 770grappenmaker** [comment]
@RichardDorian

**Comment by Aetopia** [comment]
You need an icon which has multiple sizes.

**Comment by 770grappenmaker** [comment]
Should be an easy fix then

**Comment by 770grappenmaker** [comment]
Might redesign the whole thing so this will probably be fixed with that

**Comment by 770grappenmaker** [comment]
@RichardDorian can you fix?
