### ISSUE TITLE
Disabling Cosmetics

### ISSUE THREAD

**Issue by he3als** [Solar-Tweaks/Solar-Tweaks#140]
**Is your feature request related to a problem? Please describe.**
It would be more convenient to be able to disable downloading cosmetics and the initialization of cosmetics, which would avoid downloading unnecessary files and would slightly speed up startup time. I don't care about cosmetics and I do not have them enabled in game. Plus, I am not connected to a web-socket, so cosmetics would not work anyways.

**Describe the solution you'd like**
A checkbox in the launcher to disable downloading cosmetics, disable checking cosmetics and to set the `--texturesDir` JRE argument to nothing to not load cosmetics in game.

**Describe alternatives you've considered**
None.

**Comment by he3als** [comment]
I deleted the 'texture's' folder in '.lunarclient' to test out how Solar Tweaks downloads assets and it seems that it is just stuck checking Lunar Client assets. There is a 'textures' folder with textures inside of it, but it is still stuck on checking assets.

**Comment by 770grappenmaker** [comment]
I dont know why that happens but it is a common issue, reopening the launcher solves it. If you want to skip cosmetic file checks there is literally a skip checks checkbox

**Comment by he3als** [comment]
> I dont know why that happens but it is a common issue, reopening the launcher solves it. If you want to skip cosmetic file checks there is literally a skip checks checkbox

Is it possible to have the 'Skip Checks' button customisable to only skip assets checking? Also, maybe there could be an option to skip hash checking and instead just check file names? That could be a temporary fix.

**Comment by 770grappenmaker** [comment]
I mean, me as a more advanced user would like that, but it is so specific that imo it will only confuse people that don't know what they are doing and end up bricking their lunar

**Comment by he3als** [comment]
Yeah that makes sense. A simple button to disable cosmetics would probably be a good alternative then, which just sets the JVM argument for the cosmetics to directory to nothing and skips the checking of assets. This would speed up the startup slightly and temporarily fix the issue where people can not launch due to getting stuck on assets checking.

I think the main reason I made this issue was me mistaking that the assets checking is super slow, but I think it is just simply getting stuck. When it actually checks the assets, it is super fast. Also, when downloading assets, it is super fast (I can see that in File Explorer), but it still gets stuck.

**Comment by 770grappenmaker** [comment]
The issue of the downloader getting stuck is a known issue, somehow it is trying to wait for downloads to finish and gets stuck.

**Comment by 770grappenmaker** [comment]
I created an issue: #164
