### ISSUE TITLE
Command Line Arguments

### ISSUE THREAD

**Issue by he3als** [Solar-Tweaks/Solar-Tweaks#141]
**Is your feature request related to a problem? Please describe.**
The batch wrapper does not check for updates or check assets.

**Describe the solution you'd like**
The wrapper could be replaced with a shortcut to Solar Tweaks with command line arguments to launch what you want, instead of a batch script that bypasses the launcher completely. Some command line arguments could be:
```
-launch [1.7, 1.8, 1.12, 1.16, 1.17, 1.18] - Launches the Solar Tweaks and launches a specified version
-server [server ip] - In combination with the launch argument, it launches and joins a server with a JVM argument
-nogui - Launches Solar Tweaks without a GUI
-help - Displays this menu
```

**Describe alternatives you've considered**
I do not know.

**Comment by 770grappenmaker** [comment]
Sounds like a good idea to me

**Comment by 770grappenmaker** [comment]
By the way, small update: Solar Patcher has some interesting tooling which also runs faster than normal solar or lunar, and ye it is basically really easy to make a bash wrapper around that. The poorly written docs can be found here https://github.com/Solar-Tweaks/SolarPatcher/blob/main/lunar-util/README.md
