### ISSUE TITLE
Solar tweaks not lunching 

### ISSUE THREAD

**Issue by sraya12** [Solar-Tweaks/Solar-Tweaks#15]
For fix open solar tweaks go to settings than scroll down to java settings than click on install zulu and enable better launch then scroll down and enable launch in debug mode.

When all done launch your client when its done close it and disable in the settings launch in debug mode and launch agian

**Comment by NinjaDang** [comment]
Where is the better launch

**Comment by RichardDorian** [comment]
Hey, what is the issue? Here you provide a fix for an issue we ignore.

**Comment by 770grappenmaker** [comment]
Closing as invalid, reopen if you believe this is a mistake.
