### ISSUE TITLE
Settings and choose file button not working

### ISSUE THREAD

**Issue by colourfullyy** [Solar-Tweaks/Solar-Tweaks#15]
Hi, I tried building solar tweaks from source and after creating the .app and running it I ran into a problem, that none of the buttons work but the credits and discord buttons. As I was building it did say that there were 39 warnings for packages. Some extra information about my system, macos 12.0.1 & arm64. With node.js 17.0.1. Here's an example of the issue:

https://user-images.githubusercontent.com/66484409/143782471-596225f7-73a7-480f-af65-63117a93beb9.mov

I'd appreciate any help, thanks!

**Comment by RichardDorian** [comment]
Hello, our program is not intended to be run on a Linux operating system.

If you want you can adapt the version yourself.

**Comment by colourfullyy** [comment]
Ok, thank you I didn't realise that.
