### ISSUE TITLE
Stuck in launching

### ISSUE THREAD

**Issue by wolseh** [Solar-Tweaks/Solar-Tweaks#151]
whenever i try to open mc via solar tweaks, it's stuck in LAUNCHING... Starting JVM...

how do i fix this?

**Comment by Axecyy** [comment]
for windows, check ur jre downloader, both are good but temurin is faster lol

**Comment by 770grappenmaker** [comment]
Make sure you are on a new version as well

**Comment by wolseh** [comment]
okay thank you!
