### ISSUE TITLE
hit delay fix for 1.8

### ISSUE THREAD

**Issue by danknil** [Solar-Tweaks/Solar-Tweaks#165]
**Is your feature request related to a problem? Please describe.**
Bring back no hit delay as in 1.7 would be nice for 1.8 players, since it feels much more comfortable

**Describe the solution you'd like**
copy functional of this mod https://github.com/ghast/HitDelayFixMod

**Describe alternatives you've considered**

**Additional context**

**Comment by RichardDorian** [comment]
That is already a thing

**Comment by 770grappenmaker** [comment]
NoHitDelay module is what you are looking for
