### ISSUE TITLE
Solar Tweaks mods don't work

### ISSUE THREAD

**Issue by davidlol01** [Solar-Tweaks/Solar-Tweaks#177]
I downloaded the lastest version of Solar Tweaks and selected the mods that i needed and when i launch, and click on rshift i see that nothing has changed. It's normal lunar client. Freelook and autotext do not work even tho i selected it at the start.

**Comment by 770grappenmaker** [comment]
#171

**Comment by davidlol01** [comment]
Thanks for your reply.
