### ISSUE TITLE
JRE not working (mac)

### ISSUE THREAD

**Issue by StormDoesStuff** [Solar-Tweaks/Solar-Tweaks#184]
When I click to launch 1.8 I get a message like "the jre you selected was invalid or you need a new one."
And 'cause I'm on a Mac-OS I can't download the jre in 'settings' and when I open the "users/owner/.lunarclient/zulu" thing. It takes 
me to the "Documents" folder on mac and the only file in it is "Zoom," where all my saved meetings are. Please help, I really want to use Solar Tweaks..

**Comment by StormDoesStuff** [comment]
The new thing is "desktop.ini"

**Comment by StormDoesStuff** [comment]
Also whats the "blablabla" part?

**Comment by 770grappenmaker** [comment]
First find your home/user folder, then click .lunarclient, then jre, 1.8, then there is a directory with a weird name prefixed with "zulu", then click that one (it should be only one) then click bin and select that folder as your jre

**Comment by StormDoesStuff** [comment]
YO! THANKS

**Comment by 770grappenmaker** [comment]
client? if you dont want a module just disable it

**Comment by korbsy** [comment]
> 

bro how do i get zulu on mac?
 any link to download

**Comment by 770grappenmaker** [comment]
No download necessary, check above comments

**Comment by Sweqting** [comment]
I have done everything what says above but then the client is just stuck with "Checking LC Assets"
What do I do
<img width="1287" alt="Screen Shot 2022-05-25 at 9 25 56 am" src="https://user-images.githubusercontent.com/106203575/170147902-ad45ab17-8508-4a52-838d-d33613e568f4.png">
?

**Comment by ShadowKnight68** [comment]
i cant find the lunarclient file
i even tried looking in Application Support in library but theres still nothing in lunarclient or minecraft folder
pls help

**Comment by kevyboiwastaken** [comment]
I also have the problem with finding the .lunarclient file pls help i rly want to use solar tweaks pls

**Comment by Phoenix4111** [comment]
> I have done everything what says above but then the client is just stuck with "Checking LC Assets" What do I do <img alt="Screen Shot 2022-05-25 at 9 25 56 am" width="1287" src="https://user-images.githubusercontent.com/106203575/170147902-ad45ab17-8508-4a52-838d-d33613e568f4.png"> ?

I'm getting the same problem, can someone give us a hand. Thanks!

**Comment by 770grappenmaker** [comment]
> > I have done everything what says above but then the client is just stuck with "Checking LC Assets" What do I do <img alt="Screen Shot 2022-05-25 at 9 25 56 am" width="1287" src="https://user-images.githubusercontent.com/106203575/170147902-ad45ab17-8508-4a52-838d-d33613e568f4.png"> ?
> 
> 
> 
> I'm getting the same problem, can someone give us a hand. Thanks!

Please create a separate discussion for that.
