### ISSUE TITLE
Pixel Format Acceleration Fail

### ISSUE THREAD

**Issue by TokyoDrip** [Solar-Tweaks/Solar-Tweaks#188]
**Describe the bug**
Pixel Format not Accelerated
**To Reproduce**
1. Go to 'Home'
2. Click on 'Launch (1.8)'
3. Wait for launch
4. Game crashes

**Expected behavior**
Game supposed to launch

**Actual behaviour**
Game Doesn't launch
**Screenshots**
N/A
**Environment (please complete the following information):**
 - OS: Windows 10
 - Launcher version: 4.0.2
 - Patcher version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by 770grappenmaker** [comment]
Known issue, also happens on lcqt and also without solar patcher and only happens on integrated (old?) intel cards, is that your case as well? I couldn't fix this since my laptop has linux which apparently fixes it, it is really specific (windows only, intel only)

**Comment by TokyoDrip** [comment]
Yeah, is there a way to fix it?

**Comment by 770grappenmaker** [comment]
As far as I am aware not, and I can't test it out either. There is probably some extra dll that should be loaded. Do you know what process hacker is? Couldn't you launch normal lunar and send me the program arguments of he java process of lunar?

**Comment by TokyoDrip** [comment]
sure

**Comment by TokyoDrip** [comment]
how do I do that btw? is it the characters the popup when I hover my cursor over the java icon?

**Comment by 770grappenmaker** [comment]
Yes, but you can double click and copy program arguments which is easier than typing out the tooltip

**Comment by TokyoDrip** [comment]
When double click it opens properties

**Comment by bignuto** [comment]
C:\Users\MD\.lunarclient\jre\1.8\zulu16.30.15-ca-fx-jre16.0.1-win_x64\bin\javaw.exe --add-modules jdk.naming.dns --add-exports jdk.naming.dns/com.sun.jndi.dns=java.naming -Djna.boot.library.path=natives -Dlog4j2.formatMsgNoLookups=true --add-opens java.base/java.io=ALL-UNNAMED -Xms3072m -Xmx3072m -Djava.library.path=natives -XX:+DisableAttachMechanism -cp vpatcher-prod.jar;lunar-prod-optifine.jar;lunar-libs.jar;lunar-assets-prod-1-optifine.jar;lunar-assets-prod-2-optifine.jar;lunar-assets-prod-3-optifine.jar;preview_OptiFine_1.8.9_HD_U_M6_pre2 com.moonsworth.lunar.patcher.LunarMain --version 1.8 --accessToken 0 --assetIndex 1.8 --userProperties {} --gameDir C:\Users\MD\AppData\Roaming\.minecraft --texturesDir C:\Users\MD\.lunarclient\textures --launcherVersion 2.10.1 --hwid ---------------------------- --width 854 --height 480 --workingDirectory . --classpathDir .

**Comment by TokyoDrip** [comment]
?

**Comment by bignuto** [comment]
Those are the characters that pop up for me

**Comment by TokyoDrip** [comment]
did you type it out or did you copy it, if you copied it can you teach me how to

**Comment by TokyoDrip** [comment]
ok update, now i see a cmd that says no modules then crashes

**Comment by RichardDorian** [comment]
Hello, did you try using a jre from the jre downloader?

**Comment by TokyoDrip** [comment]
Yeah

**Comment by 770grappenmaker** [comment]
> ok update, now i see a cmd that says no modules then crashes

logs? https://github.com/Solar-Tweaks/SolarPatcher/wiki/Tutorial:-Sending-Logs

**Comment by bignuto** [comment]
> did you type it out or did you copy it, if you copied it can you teach me how to

right click javaw in exe in process hacker -> properties -> magnifying glass next to Command Line

**Comment by 770grappenmaker** [comment]
#277
