### ISSUE TITLE
JRE download is not showing up (windows)

### ISSUE THREAD

**Issue by Natna654** [Solar-Tweaks/Solar-Tweaks#192]
So i downloaded Solar Tweaks but suddeny i got msg error with JRE so i scrolled down to JRE downloader but i dont have any option there. 

![JREses](https://user-images.githubusercontent.com/105743367/168877740-208e4134-ef2f-4ff3-85eb-fc2c04b6e334.png)

So i would be very happy if someone had fix for this 
Thanks for quick response 
Natna

**Comment by 770grappenmaker** [comment]
Yeah we were experimenting with the api since we need to bring that back in order to make it work for new users. Though the updater doesn't work cuz we didn't backup those files
