### ISSUE TITLE
hits not registering on 1.12.2 while hitting in the air

### ISSUE THREAD

**Issue by C0LoRzz** [Solar-Tweaks/Solar-Tweaks#193]
**Describe the bug**
doesnt register the hit when i hit at the air which is really annoying for pvp, btw i didnt have this problem on lunar without solar
**To Reproduce**
1. Go into 1.12.2 on solar tweaks
2. Go into any world
3. Try to hit with anything in the air
**Expected behavior**
the hand swings and actually hits 
**Actual behaviour**
Description of what is actually happening.
not swinging and not hitting
**Screenshots**
its a video but it explains what is happening: https://youtu.be/fb5UfvB3UAY
**Environment (please complete the following information):**
 - OS: [e.g. Windows] Windows 
 - Launcher version [eg. 4.0.1] 4.0.2
 - Patcher version [eg. 1.6] (If you can't find this, leave blank) 1.6.1
 - Solar Stats version (if applicable) no

**Comment by 770grappenmaker** [comment]
This also happens or normal lunar client afaik

**Comment by 770grappenmaker** [comment]
At least that are the results of my testing

**Comment by 770grappenmaker** [comment]
If you still think it is a solar patcher bug, please enable "debug" in the config.json file, and attach full logs, and disable all modules as well. If from your findings a specific module is causing it pleaze share

**Comment by C0LoRzz** [comment]
> This also happens or normal lunar client afaik
it doesnt happen on mine

**Comment by C0LoRzz** [comment]
> If you still think it is a solar patcher bug, please enable "debug" in the config.json file, and attach full logs, and disable all modules as well. If from your findings a specific module is causing it pleaze share
the logs when i enabled my normal mods:[logs on cmd debug.txt](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8723404/logs.on.cmd.debug.txt) the hitting doesnt work 
from my testing, "Remove Hit Delay" mod causes this

**Comment by 770grappenmaker** [comment]
Okay, yeah that makes sense since it is trying to apply 1.7 legacy combat on 1.12 which obviously fails. I might try to fix that so it doesn't work on 1.12 but for now, just don't use the remove hit delay module
