### ISSUE TITLE
My game is crashing

### ISSUE THREAD

**Issue by NinjaDang** [Solar-Tweaks/Solar-Tweaks#20]
When i launch the game in 4.0.1 it crashes can someone tell me why

**Comment by Tiebe** [comment]
This is a terrible bug report. Please provide information about when it happened, what version you are running, and attach some logs

**Comment by RichardDorian** [comment]
> This is a terrible bug report. Please provide information about when it happened, what version you are running, and attach some logs

Thank you lol

**Comment by RichardDorian** [comment]
Can you provide more details? Maybe logs or a screenshot of the crash screen?

**Comment by risphs** [comment]
Could you provide some game info. I helped a friend who had issues with 1.7 but when he used 1.8 it worked flawlessly!

**Comment by 770grappenmaker** [comment]
Could you provide me with:
- Your `%USERPROFILE$\.lunarclient\solartweaks\config.json` file
- Game versions
- Logs (preferably debug mode logs)
- Steps to reproduce/context

**Comment by 770grappenmaker** [comment]
> This is a terrible bug report. Please provide information about when it happened, what version you are running, and attach some logs

Actually really weird because there are literally [templates for issues](https://github.com/Solar-Tweaks/Solar-Tweaks/blob/main/.github/ISSUE_TEMPLATE/bug_report.md), which have been used, because it has the bug tag.

**Comment by Tiebe** [comment]
> > This is a terrible bug report. Please provide information about when it happened, what version you are running, and attach some logs
> 
> Actually really weird because there are literally [templates for issues](https://github.com/Solar-Tweaks/Solar-Tweaks/blob/main/.github/ISSUE_TEMPLATE/bug_report.md), which have been used, because it has the bug tag.

Yeah, they submitted an empty bug report form, and they've now edited it

**Comment by NinjaDang** [comment]
Its version 1.8
