### ISSUE TITLE
V4

### ISSUE THREAD

**Issue by KBCats** [Solar-Tweaks/Solar-Tweaks#203]
**Is your feature request related to a problem? Please describe.**
When you try to inject V4 it crashes 

**Describe the solution you'd like**
It to be able to inject

**Comment by TokyoDrip** [comment]
disable window title

**Comment by 770grappenmaker** [comment]
tf is v4

**Comment by downloadyetter** [comment]
> tf is v4

vape v4 hacked client

**Comment by 770grappenmaker** [comment]
Oh like that. Well that's not a solar tweaks issue
