### ISSUE TITLE
How to reset the settings i selected in solar tweaks 

### ISSUE THREAD

**Issue by iHetox098** [Solar-Tweaks/Solar-Tweaks#21]
I first used nick hider and level head prefix but now I don't  want those settings and I'm not able to reset them how to reset them pls help

**Comment by iHetox098** [comment]
Pls help what to do i want to play on solar tweaks how.to reset the settings?

**Comment by RichardDorian** [comment]
Hello,

You can reset any patch/tweak/customization by launching official Lunar Client. This will overwrite all the files with new ones.
