### ISSUE TITLE
The tweaks are not applying

### ISSUE THREAD

**Issue by LuddePro05** [Solar-Tweaks/Solar-Tweaks#210]
**Describe the bug**
Everything is applied and ready but when the game launches none of the tweaks actually work ingame

**To Reproduce**
1. Go to 'ST Launcher'
2. Click on 'Launch 1.8'
4. See that for example the pinned servers are still there

**Expected behavior**
That the tweaks succesfully applied and is working
**Actual behaviour**
They dont

**Screenshots**
i dont think that is needed

**Environment (please complete the following information):**
 - OS: [Atlas OS 1803]
 - Launcher version [4.0.2]
 - Patcher version
 - Solar Stats version (if applicable)

**Comment by 770grappenmaker** [comment]
Lunar client updated, known issue
