### ISSUE TITLE
Lunar assets checking

### ISSUE THREAD

**Issue by 5rq** [Solar-Tweaks/Solar-Tweaks#212]
**Is your feature request related to a problem? Please describe.**
sometimes checking lunar assets slows down the launching process

**Describe the solution you'd like**
An option to skip checking lunar assets

**Describe alternatives you've considered**
I don't know of any alternatives that could fix this really

**Additional context**
Add an option to skip checking lunar assets when launching in the settings tab of the launcher

**Comment by 770grappenmaker** [comment]
Already exists
