### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by NoCax** [Solar-Tweaks/Solar-Tweaks#219]
Yesterday I used the websocket to get all the skins of the lunar client [Solar Tweaks - Cosmetics], and everything was fine. today I start the .bat and the user does not connect to the local host, the skins / ballets are not there. is it just my problem? or was it patched by the lunar?
![Immagine 2022-05-25 145448](https://user-images.githubusercontent.com/94179546/170267526-418d9281-8743-4a0c-8877-ca951466d8c6.png)

**Comment by ImJavaCode** [comment]
I'm experiencing the same problem. I launched the modded client in debug mode and found in the console printed `Detected usage of the Solar Tweaks launcher`, so maybe it got patched?
![](https://cdn.upload.systems/uploads/UCbMYxCl.png)
On the left there is the console and on the right a log from the unmodded Lunar: after the line "Launching" on the console you can see the message. I don't know if this is normal.

**Comment by CClamz** [comment]
Could be related to the recent update of Lunar but here's the discussion link that answers your concern, in the same manner as other patcher mod https://github.com/Solar-Tweaks/Solar-Tweaks/discussions/206

**Comment by NoCax** [comment]
> I'm experiencing the same problem. I launched the modded client in debug mode and found in the console printed `Detected usage of the Solar Tweaks launcher`, so maybe it got patched? ![](https://camo.githubusercontent.com/b71ed05489c8d29f41e9dec6c31297ff7a90776c2c20b61261664d6efde3a5e8/68747470733a2f2f63646e2e75706c6f61642e73797374656d732f75706c6f6164732f5543624d5978436c2e706e67) On the left there is the console and on the right a log from the unmodded Lunar: after the line "Launching" on the console you can see the message. I don't know if this is normal.

pretty sure

**Comment by 770grappenmaker** [comment]
![image](https://user-images.githubusercontent.com/50543283/170353677-18e8fac1-d692-47ff-85ba-67476eb63e54.png)
no, lunar isnt detecting us, I am actually logging it with the patcher (attached code screenshot is solarpatcher code)

**Comment by 770grappenmaker** [comment]
> Yesterday I used the websocket to get all the skins of the lunar client [Solar Tweaks - Cosmetics], and everything was fine. today I start the .bat and the user does not connect to the local host, the skins / ballets are not there. is it just my problem? or was it patched by the lunar? ![Immagine 2022-05-25 145448](https://user-images.githubusercontent.com/94179546/170267526-418d9281-8743-4a0c-8877-ca951466d8c6.png)

Who told you to setup a websocket on localhost? Either way, did you start the lunarsocket instance then? If you didn't, connecting to "localhost" will not work

**Comment by ImJavaCode** [comment]
> ![image](https://user-images.githubusercontent.com/50543283/170353677-18e8fac1-d692-47ff-85ba-67476eb63e54.png)
> no, lunar isnt detecting us, I am actually logging it with the patcher (attached code screenshot is solarpatcher code)

Sorry, my bad. I guess I jumped to conclusions too early. It is strange though, the socket stopped working out of the blue without any changes to my setup.

**Comment by NoCax** [comment]
> > Yesterday I used the websocket to get all the skins of the lunar client [Solar Tweaks - Cosmetics], and everything was fine. today I start the .bat and the user does not connect to the local host, the skins / ballets are not there. is it just my problem? or was it patched by the lunar? ![Immagine 2022-05-25 145448](https://user-images.githubusercontent.com/94179546/170267526-418d9281-8743-4a0c-8877-ca951466d8c6.png)
> 
> Who told you to setup a websocket on localhost? Either way, did you start the lunarsocket instance then? If you didn't, connecting to "localhost" will not work

I just saw a video and it worked, now it does not connect to localhost despite lunar socket is started.

**Comment by RichardDorian** [comment]
Why did you reopen the issue?
