### ISSUE TITLE
To slow

### ISSUE THREAD

**Issue by NPQuannn** [Solar-Tweaks/Solar-Tweaks#220]
It was too slow,my official lunar launch in 3 minutes but solar tweaks took more than 20 minutes?

**Comment by 770grappenmaker** [comment]
That is really really slow; i actually cannot believe it. Well, if you want to have a faster launch you can enable skip checks but it might break (which is kind of the point of the option).

From my experience:
dev script - 8 second launch (time to interactive from the moment i start the script) - 500 mb ram usage when idle
lunar official launcher - 35 second launch (from the moment i click launch to interactive) - 4 gb ram usage when idle
