### ISSUE TITLE
"Patcher not working"

### ISSUE THREAD

**Issue by Youtubah3315** [Solar-Tweaks/Solar-Tweaks#225]
Yes now its back :D

_Originally posted by @770grappenmaker in https://github.com/Solar-Tweaks/Solar-Tweaks/discussions/206#discussioncomment-2821563_

hey nothing is working for me rn like the patcher features

**Comment by 770grappenmaker** [comment]
Did you enable skip checks? You should not. Otherwise delete .lunarclient/solartweaks/config.json
