### ISSUE TITLE
Checking commit id

### ISSUE THREAD

**Issue by 20221415** [Solar-Tweaks/Solar-Tweaks#23]
My 'Solar Tweaks' doesn't load the Commit ID, there's no tutorial on the internet and I need to solve this problem.

( An error ocurred. We are sorry for the inconvenience, if you don't know why this is happening, please open a ticket in our Discord. )
(Discord link is invalid.)

**Comment by rolcsi05** [comment]
same issue here ! :I

**Comment by xZinio** [comment]
For me, the error just says "Wrong Lunar Version". Not sure how to fix this.

**Comment by RichardDorian** [comment]
Our server got terminated by Discord. We stopped providing mappings because we are working on Solar Tweaks V4 (which has no mappings). We still don't know when we are going to re open the discord server but I promise that we will soon.

**Comment by RichardDorian** [comment]
Yes
