### ISSUE TITLE
wont launch and vape lite wont inject

### ISSUE THREAD

**Issue by addaaaaadd** [Solar-Tweaks/Solar-Tweaks#232]
**wont launch and vape lite wont inject**

**Comment by addaaaaadd** [comment]
launching now just vape lite wont inject with out crashing

**Comment by SuchSunset** [comment]
use normal lunar then ???

**Comment by addaaaaadd** [comment]
but this has fps spoof

**Comment by addaaaaadd** [comment]
can you make this have forge in it
