### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by riceyyyy** [Solar-Tweaks/Solar-Tweaks#245]
![image](https://user-images.githubusercontent.com/106349069/170567083-61cb3690-91f2-4d84-8df1-bcfd2213ba3d.png)

I'm getting this error code when I launch. Any fixes?

**Comment by RichardDorian** [comment]
Can you please provide the version of Minecraft you're trying to play on as well as your launcher version.

**Comment by riceyyyy** [comment]
I’m trying to launch 1.8 and my launcher version is 4.0.2

**Comment by 770grappenmaker** [comment]
Would help if i had any logs: please follow these steps https://github.com/Solar-Tweaks/SolarPatcher/wiki/Tutorial:-Sending-Logs

**Comment by riceyyyy** [comment]
[1.8-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8792574/1.8-latest.log)
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8792575/launcher-latest.log)

here you go!

**Comment by 770grappenmaker** [comment]
I'm not sure but a lot of logs are missing, make sure you did close your game etc. and then send it

**Comment by riceyyyy** [comment]
that’s the thing. my game dosent open

**Comment by 770grappenmaker** [comment]
Oh right makes sense, can you try again? Did you enable keep launcher open so it'll actually log?

**Comment by salvatorecalo** [comment]
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8840482/launcher-latest.log)
[1.8-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8840483/1.8-latest.log)

I have also the same problem. I did as well as you 've said in the above message, it returns me this.

**Comment by 770grappenmaker** [comment]
@salvatorecalo default minecraft textures appear to be missing; make sure to run normal lunar client in the game directory you selected first to ensure proper serialization

**Comment by 770grappenmaker** [comment]
Closing because of OP inactivity
