### ISSUE TITLE
The patcher option tweaks that are enabled don't work in game . None of them

### ISSUE THREAD

**Issue by sonicflyingevil** [Solar-Tweaks/Solar-Tweaks#246]
**A clear and concise description of what the bug is.**
The patcher option tweaks arent working in game. None of them

**To Reproduce**

**Expected behavior**
I thought that if I enable no hit delay and custom level heads they would actually work in game.
**Actual behaviour**
None of the patcher options are working in game when enabled. This started happening yesterday night because before that it was working because I remember seeing the custom level heads + no hit delay + fps spoof.

**Screenshots**

**Environment (please complete the following information):**
 - OS - Windows
 - Launcher version - 4.0.2
 - Patcher version - I dont know what this means but it says  Launch 1.8 when I press on patcher tab
 - Solar Stats version (if applicable) - dont know what this means

**Additional context**er
So yeah the patcher options I enable dont work on hypixel, minemen or any other server and im not the only person with this issue as my friend also has the same problem.

**Comment by RichardDorian** [comment]
Can you please provide your `config.json` file. To get it go to the about tab and click `Open ST folder` then get the file called `config.json`.

**Comment by 770grappenmaker** [comment]
99 percent of the time when the patches dont work, it is caused by the config being invalid. To be sure however, please follow these steps https://github.com/Solar-Tweaks/SolarPatcher/wiki/Tutorial:-Sending-Logs
