### ISSUE TITLE
It tells me I have no Comsetics.

### ISSUE THREAD

**Issue by Luis2000yt** [Solar-Tweaks/Solar-Tweaks#247]
it tells me I have no Cosmetics but it says: Lunar Client (Modded by Solar Tweaks) any Ideas how to fix it?

![image](https://user-images.githubusercontent.com/106380105/170680172-7f399088-b29e-4b92-a1ae-e05684ed14ca.png)

**Comment by Luis2000yt** [comment]
Mods like Freelook on Hypixel work btw. its just the Cosmetics

**Comment by RichardDorian** [comment]
Solar Tweaks doesn't provide a way to get free cosmetics using the launcher.
