### ISSUE TITLE
Microsoft log in

### ISSUE THREAD

**Issue by MATTILGAMER** [Solar-Tweaks/Solar-Tweaks#251]
If i try to log in with microsoft on minecraft 1.18.2 it says open your launcher to continue. Even if i open the launcher it says that.

**To Reproduce**
go on version->1.18->launch 1.18
then you go on the icon on the top with the account login->You click the plus->and click microsoft log in 

It should open a window where i can log in but it doesn't

 - OS: Windows 11
 - Launcher version 4.0.2
 - Patcher version
 - Solar Stats version

**Comment by 5rq** [comment]
Make sure you open the official **lunar** launcher and **NOT** the solar launcher.

**Comment by 5rq** [comment]
I don't think Solar could do anything to make it not require the lunar launcher but I'm not to smart on the new Microsoft logins 😅

**Comment by 770grappenmaker** [comment]
Well we totally could do at least something, i know how to do the microsoft auth so might as well build it ingame instead of needing an unnecesary launcher?

**Comment by 770grappenmaker** [comment]
Kind of a wontfix situation id say
