### ISSUE TITLE
My game crashed before launching

### ISSUE THREAD

**Issue by ImRedLol** [Solar-Tweaks/Solar-Tweaks#258]
**To Reproduce**
I basically just launched the version 1.8.9.

**Expected behavior**
The game would launch without issues.

**Actual behaviour**
The game crashed.

**Screenshots**
![image](https://user-images.githubusercontent.com/106432798/170823544-0b27cecf-d328-4e73-9d43-22c6954ecd82.png)

**Environment (please complete the following information):**
 - OS: windows 10 64bit
 - Launcher version 4.0.2
 - Patcher version ---
 - Solar Stats version ---

**Additional context**
[1.8-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8791035/1.8-latest.log)
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8791036/launcher-latest.log)

**Comment by 770grappenmaker** [comment]
Known issue, for some reason solar doesnt work on integrated cards on windows. might need to investigate since a lot of people have this issue

**Comment by 770grappenmaker** [comment]
#277

**Comment by ImRedLol** [comment]
Thank you for the quick reply! Can you please notify me, when there will be
a fix, to this?

770grappenmaker ***@***.***> ezt írta (időpont: 2022. máj.
29., V 0:27):
