### ISSUE TITLE
Patcher doesn't work

### ISSUE THREAD

**Issue by YESSIR9153** [Solar-Tweaks/Solar-Tweaks#259]
Patcher (Cloaks+ and more) doesnt work idk why

**To Reproduce**
1. Go to 'Patcher'
2. Click on 'Cloaks+ Disabled to Enable it'
3. Run minecraft
4. Click on Lunar Cosmetics
5. Nothing There

i fixed JRE i was excited to have free emotes and more but its not working

**Screenshots**
https://prnt.sc/K2sHQ_XygduZ , https://prnt.sc/1FyhGQlC4Fsz , https://prnt.sc/NOAEcJ0VQt2A

**Environment (please complete the following information):**
 - OS: [MacOs Montery]
 - Launcher version [3.0.2]
 - Patcher version [idk] 
 - Solar Stats version i dont have it

**Comment by 770grappenmaker** [comment]
cloaks+ isnt supposed to give you free lunar cloaks and emotes, it is supposed to allow for usage with https://cloaksplus.com . if you do want free lunar stuff youll have to use lunarsocket or use a third party hosted one

**Comment by 5rq** [comment]
Cloaks+ isn't in Lunar Cosmetics, its an external program to add free 3rd party cosmetics to Lunar, you can find more information about Cloaks+ at their website [here](http://cloaksplus.com/)

**Comment by 770grappenmaker** [comment]
> Edit: didn't notice that 770 got here before me . _.

:D
