### ISSUE TITLE
jre

### ISSUE THREAD

**Issue by firefighter56** [Solar-Tweaks/Solar-Tweaks#264]
problem launching it, it says i need to select jre can you pls help me

**Comment by 770grappenmaker** [comment]
Use the jre downloader for an easy fix

**Comment by firefighter56** [comment]
can you link it

**Comment by 770grappenmaker** [comment]
It is literally built into the launcher

**Comment by shrindle** [comment]
sooo does it work on mac?

**Comment by ShadowKnight68** [comment]
i need the jre file zulu or temurin but i cant use the jre downloader cz im on mac

**Comment by 770grappenmaker** [comment]
No but on mac there are other ways
