### ISSUE TITLE
Different JRE Per Version of Minecraft

### ISSUE THREAD

**Issue by Banaando** [Solar-Tweaks/Solar-Tweaks#272]
**Is your feature request related to a problem? Please describe.**
When you open Minecraft with the default Lunar Client, it launches the game with distinct JREs for each version. However, Solar Tweaks only allows you to select one custom JRE and does not allow you to change it per version.

**Describe the solution you'd like**
Under the Java Executable tab in the Solar Tweaks launcher settings, you can choose a different JRE for each version of the game. Also, if this change were to be implemented, it may be a good idea to be able to customize the JVM arguments for each version of the game.

**Describe alternatives you've considered**
The user can select a checkbox that will make the launcher change the JRE automatically in the Java Executable settings.

**Additional context**
Could look like this:

![image](https://user-images.githubusercontent.com/67934979/170918457-8597ae15-7f24-4106-83ec-1de3ea2b7ca9.png)

**Comment by Banaando** [comment]
So there's no downside to using java 17 on versions older than 1.16?

**Comment by 770grappenmaker** [comment]
Not at all, it actually gives less ram usage and therefore better performance. jdk 17 is significantly better than jdk 16 for some reason
