### ISSUE TITLE
Toggle sprint texts don't work

### ISSUE THREAD

**Issue by SheeepSteww** [Solar-Tweaks/Solar-Tweaks#28]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher version [eg. 4.0.1]
 - Patcher version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by RichardDorian** [comment]
Please provide further details and actually fill the issue template please.

**Comment by 770grappenmaker** [comment]
Closing because of invalidity and inactivity: please reopen if you do still need assistance.
