### ISSUE TITLE
Patcher not working

### ISSUE THREAD

**Issue by gwibby** [Solar-Tweaks/Solar-Tweaks#302]
Patcher not working in game

1. Go to Patcher tab
2. Enable mods i would like
3. Click launch
4. None of the patcher settings work in game

Noneof the patcher settings work in game even though they are enabled

![image](https://user-images.githubusercontent.com/106786318/171761560-77a013e6-669d-4fa4-a7fe-8950e4e3ab8c.png)
![image](https://user-images.githubusercontent.com/106786318/171761594-b0954052-235a-4171-a764-f1b26f86771e.png)
![image](https://user-images.githubusercontent.com/106786318/171761634-46800355-b22e-4cc5-ba35-aee5347ec4e9.png)
![image](https://user-images.githubusercontent.com/106786318/171761658-61bd9051-661e-432b-bf7b-a590ba67fd43.png)
![image](https://user-images.githubusercontent.com/106786318/171761679-c954774f-707a-410b-bb56-6bf2238fa71b.png)
![image](https://user-images.githubusercontent.com/106786318/171761694-f5f5f8a6-6eca-43e8-82eb-a452c956afad.png)
![image](https://user-images.githubusercontent.com/106786318/171761716-88547776-993f-4f61-845f-1f59fe22f389.png)
![image](https://user-images.githubusercontent.com/106786318/171761732-9cb52dd8-d118-49e1-a345-caf590cfc82c.png)

In ST folder:
![image](https://user-images.githubusercontent.com/106786318/171761765-418ebf0a-aebf-4347-af37-1c11c1cc61ce.png)

 - Windows 10
 - 4.0.2
 - Not sure what patcher version
 - Not sure what Solar Stats is or how to find it

**Comment by 770grappenmaker** [comment]
Pretty sure skip checks is enabled. Don't do that

**Comment by gwibby** [comment]
When I uncheck skip checks it just stays on checking lc assets for a long time

**Comment by gwibby** [comment]
Update:
The game now launches if I uncheck skip checks and some of the patcher options work(which i can see):
- fps
- cloaks+
- level head
- remove hashing
, however others do not for example:
- nick hider
- websocket
- lunar overlays
- cloth cloaks

**Comment by 770grappenmaker** [comment]
What doesn't work of those mods? Can you provide logs? https://github.com/Solar-Tweaks/SolarPatcher/wiki/Tutorial:-Sending-Logs

**Comment by gwibby** [comment]
[1.8-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8836821/1.8-latest.log)
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8836822/launcher-latest.log)
These are the logs ^
The following mods don't work:
- nick hider (it doesn't show what I have typed in solar tweaks only what I have typed in lunar client which is my own minecraft name)
- websocket (I used a lunar socket which should give me all of the cosmetics and cloth cloaks but only people using that specific websocket can see it)
- lunar overlays (next to the level head there is no longer the lunar icon and I am not sure if it has changed to the overlay in the texturepack that I am using)
- cloth cloaks (the cloak I have equipped from the cloaks+ mod do not have the cloth cloaks animation)
- with cloaks+ the head items that I got are not showing on my skin

Note* when I ran solar tweaks this time while keeping the launcher open to get the logs, my bitdefender antivirus triggered and said it blocked something from java.exe

**Comment by 770grappenmaker** [comment]
For nickhider: click reset in the nickhider mod, and then try setting an empty value and it'll reset to the name including the colors you might've added.
For websocket: it is impossible to show cosmetics through a third party socket on normal instances of lunar client.
I don't get your lunar overlays point
Cloaks plus cosmetics don't use the lunar cape system and therefore aren't cloth cloaks 
I'm not sure what you mean with "head items don't work", so please elaborate

**Comment by gwibby** [comment]
When you say nickhider mod do you mean the nickhider in solar tweak or in lunar
For the lunar overlays the little lunar icon next to your name which will change to a pink one with a little green plus if you have lunar plus, that little icon is no longer there and I am unable to see if the texture pack I am using which should change it to viprah's overlay works or not
When I say head items dont work I mean that they are not showing up on my skin even  though I have used the !cosmetic add command in the discord (head items means like the crown or antlers or ears, things like that)

**Comment by gwibby** [comment]
Update:
everything is working now except for the nick hider.
Cloaks plus has been triggering my antivirus so I have disabled it now.

**Comment by 770grappenmaker** [comment]
Do what I said for nickhider, in game

**Comment by gwibby** [comment]
When I click reset it doesn't change anything.

**Comment by 770grappenmaker** [comment]
You also have to enable "Hide my nick" and "Hide my real name" for it to work

**Comment by gwibby** [comment]
Thx it worked

only had to time to check now bcs exams lmao

thank you very much for helping me :D

**Comment by 770grappenmaker** [comment]
No problem!
