### ISSUE TITLE
Can't take clips while using Solar Tweaks

### ISSUE THREAD

**Issue by deepsorrows** [Solar-Tweaks/Solar-Tweaks#310]
Hello, I really like taking clips of cool moments in Minecraft and I mostly use Medal to clip with so when using Solar Tweaks I can't clip because Minecraft isn't appearing in the app do you guys have any solution for that ?

**Comment by 770grappenmaker** [comment]
I don't think normal lunar client is even appearing. Still you can probably manually select the game? Either way not a solar tweaks related issue

**Comment by deepsorrows** [comment]
Well then for some reason when using lunar I can clip but when using Solar
Tweaks I can't it's really weird.

**Comment by 770grappenmaker** [comment]
What isn't working then?

**Comment by Khonshulol** [comment]
It might be for the fact that solar tweaks might not be considered as a official registered app according to medal. Just use OBS or smth to record and then upload onto medal.

**Comment by Ashwinswamy19** [comment]
You can use OBS To clip things using the REPLAY BUFFER feature:

here's a good video on it: https://www.youtube.com/watch?v=6dwQECo-ZK8&t=63s

go to the clipping section

**Comment by 770grappenmaker** [comment]
If you need more help feel free to reopen
