### ISSUE TITLE
solar not launching

### ISSUE THREAD

**Issue by AnaIytics** [Solar-Tweaks/Solar-Tweaks#313]
hi im using the zulu jre and whenever i launch a version of solar it doesnt launch

**Comment by 770grappenmaker** [comment]
that isnt helpful. at least show logs.https://github.com/Solar-Tweaks/SolarPatcher/wiki/Tutorial:-Sending-Logs

**Comment by real-yeat** [comment]
> that isnt helpful. at least show logs.https://github.com/Solar-Tweaks/SolarPatcher/wiki/Tutorial:-Sending-Logs

https://pastebin.com/hY1id9Rx

**Comment by 770grappenmaker** [comment]
Did you follow the tutorial? those arent logs, that is your config

**Comment by real-yeat** [comment]
> Did you follow the tutorial? those arent logs, that is your config

My bad, it was like 1am and I only looked at the screenshots here are my logs tho
[1.7-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8846274/1.7-latest.log)
[1.8-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8846275/1.8-latest.log)
[1.18-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8846276/1.18-latest.log)
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8846277/launcher-latest.log)

**Comment by 770grappenmaker** [comment]
You didnt enable keep launcher open so logs dont work

**Comment by real-yeat** [comment]
> You didnt enable keep launcher open so logs dont work

when i turn keep launcher on its stuck on getting lc assets or sm

**Comment by real-yeat** [comment]
i changed it to hide launcher and it gives me this now
[1.18-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8848323/1.18-latest.log)
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8848324/launcher-latest.log)
[1.7-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8848325/1.7-latest.log)
[1.8-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8848326/1.8-latest.log)

**Comment by 770grappenmaker** [comment]
Your jvm arguments are invalid. Remove all of them.

**Comment by 770grappenmaker** [comment]
Also you might be on an old java version

**Comment by real-yeat** [comment]
> Also you might be on an old java version

naw just reinstalled java

**Comment by 770grappenmaker** [comment]
As in, your selected jre has to be at least java 16

**Comment by SPIKESGAMING** [comment]
my solar tweaks isnt launching too i tried like 14 times still nothing 
please help me

**Comment by AnaIytics** [comment]
> As in, your selected jre has to be at least java 16

forgot to reply back but i selected the bin folder again, and it didn't work it was stuck at launching jav or whatever
