### ISSUE TITLE
Don't launch 1.8

### ISSUE THREAD

**Issue by Verzzzzzzzzz** [Solar-Tweaks/Solar-Tweaks#315]
![unknown (12)](https://user-images.githubusercontent.com/106933772/172072834-741f0758-79b5-41d2-850d-0014bf63207e.png)

**Comment by Khonshulol** [comment]
Are you using an integrated graphics card?

**Comment by Khonshulol** [comment]
@Verzzzzzzzzz

**Comment by Verzzzzzzzzz** [comment]
no

**Comment by 770grappenmaker** [comment]
#277

**Comment by Verzzzzzzzzz** [comment]
I updated my driver and it didn't work


> #277

**Comment by 770grappenmaker** [comment]
Well, it is the official minecraft tutorial thing so if that doesn't help you i don't know what to tell you. Your computer probably is assigning your cpu for rendering which isn't supported by minecraft. You can probably override this behaviour.
