### ISSUE TITLE
Damage indicator 

### ISSUE THREAD

**Issue by shora11** [Solar-Tweaks/Solar-Tweaks#317]
It's a only suggestion for add a mod in the Solar-Tweaks, the mod is "Damage Indicator" the mod shows the enemy hp (it's a video to demonstrate the mod https://www.youtube.com/watch?v=5DAOT0WCliY&t=186s ) (and sorry for the bed english)

**Comment by redefault** [comment]
cheat

**Comment by Khonshulol** [comment]
Yeah thats a feature used in vape v4. We cant possibly use that in solar tweaks.

**Comment by 770grappenmaker** [comment]
As pointed out above, this feature would give solar tweaks users a clear unfair advantage so I won't add this.
