### ISSUE TITLE
My Mac did not find the JRE

### ISSUE THREAD

**Issue by CB444444** [Solar-Tweaks/Solar-Tweaks#319]
The bug is when ever I open solar tweaks and try to launch it it says selsect JRE.  I ahve seen many videos say that you just have to open .Lunarcliant but I dont have that folder.  someone please help me!!!

**Comment by Khonshulol** [comment]
@CB444444 
1. Enable hidden files
2. Find /Users/username/.lunarclient/jre/1.8/zulu-blabla/bin
3. Select it

**Comment by 770grappenmaker** [comment]
Did this resolve your issue? You can close it if it did.

**Comment by CB444444** [comment]
I was wondering can you send me a picsure of where to find the /users/username.lunarcliant/jre/1.8/zulu-blabla/bin
