### ISSUE TITLE
Custom Websocket wil not connect

### ISSUE THREAD

**Issue by CB444444** [Solar-Tweaks/Solar-Tweaks#321]
My custom websockeyt will not launch the cosmeticks.  It is just stuck on the Conetcing screen.  The custom websocket is ws://socket.solartweaks.com:8080/connect. I am also on Mac!

**Comment by CB444444** [comment]
Please help fast

**Comment by CB444444** [comment]
@everyone help me

**Comment by 770grappenmaker** [comment]
Not sure, that ip might not be correct. Either way, I won't grant support since this is not an official socket. Youll have to ask the staff there
