### ISSUE TITLE
Lunar Friends Menu Not Connecting / Loading

### ISSUE THREAD

**Issue by Ashwinswamy19** [Solar-Tweaks/Solar-Tweaks#325]
When i press the feature for lunar friends, it does not load and just says connecting...

I have lunar friends enabled and use it but it isnt loading
![image](https://user-images.githubusercontent.com/89256504/172230226-6dfaecdf-a05a-4597-9194-41511e1350a3.png)

**Comment by 770grappenmaker** [comment]
Disable the websocket module
