### ISSUE TITLE
Solar Tweaks is launching the normal version of Lunar

### ISSUE THREAD

**Issue by Astralrr** [Solar-Tweaks/Solar-Tweaks#331]
So uh, a couple of days ago Solar wont launch with its tweaks/patchers. Like it just launches the normal version of lunar. No websockets, No removed pin servers. Nothing

**Comment by 770grappenmaker** [comment]
Firat disable skip checks, your patcher is probably not up to date

**Comment by Astralrr** [comment]
> Firat disable skip checks, your patcher is probably not up to date

I've already disabled "Skip Checks". And how do i check if my patcher is up to date or not?

**Comment by 770grappenmaker** [comment]
Can you attach logs as described in the solar patcher wiki?

**Comment by Astralrr** [comment]
> Can you attach logs as described in the solar patcher wiki?

Here!
[1.8-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8883352/1.8-latest.log)
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/8883353/launcher-latest.log)

**Comment by 770grappenmaker** [comment]
As I expected. Delete .lunarclient/solartweaks/config.json
