### ISSUE TITLE
customize tab

### ISSUE THREAD

**Issue by ShinyaHir** [Solar-Tweaks/Solar-Tweaks#337]
i use linux and the customize tab doesnt show for me in the luauncher
![image](https://user-images.githubusercontent.com/82143619/173113580-1144d8fd-02f1-45ff-9a64-7babff3ff48a.png)
if it got updated how do i enable the free cosmetics

**Comment by 770grappenmaker** [comment]
It is the patcher tab. Free cosmetics isn't a module but can be achieved with a third party websocket.
