### ISSUE TITLE
Use different versions of texture packs

### ISSUE THREAD

**Issue by BigHair12345** [Solar-Tweaks/Solar-Tweaks#338]
I'm a 1.8.9 player and I want to use a higher version texture pack, but it's blocked by Lunar, so I want to ask if it is possible to develop a mod so that Lunar doesn't block it anymore, let me Can 1.9+ texture packs be used in 1.8.9, please?

**Comment by 770grappenmaker** [comment]
I'm not sure if it is even possible to use any kind of 1.9 pack on 1.8, can you test on vanilla?

**Comment by BigHair12345** [comment]
> I'm not sure if it is even possible to use any kind of 1.9 pack on 1.8, can you test on vanilla?
You can use any version of the texture pack in any version of vanilla Minecraft. For example: using 1.9 texture packs in 1.8.9, or everything else works, but not Lunar.
