### ISSUE TITLE
this might not be a bug it might just be my computer but i did everything and i dont have all the luner cloaks etc.

### ISSUE THREAD

**Issue by cobza** [Solar-Tweaks/Solar-Tweaks#340]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher version [eg. 4.0.1]
 - Patcher version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by 770grappenmaker** [comment]
Please elaborate. I have no clue what you mean. What is the issue?

**Comment by maccaxd** [comment]
ima having the same problem

**Comment by maccaxd** [comment]
i could use the clocks for  two day then it left and then i launched lunar and it crashed then when i went back on solar it work again for one day
and when im on solar tweaks it doesen't have any lunar sign

**Comment by 770grappenmaker** [comment]
Just don't use the websocket module, if that websocket breaks. We do not support any websocket, you must host it yourself or trust a third party. "Solar Socket" is not managed by us, and we absolutely do not grant any support for it.

**Comment by maccaxd** [comment]
amongb uds
