### ISSUE TITLE
When i try to use the cosmetics i got connecting message

### ISSUE THREAD

**Issue by neve360** [Solar-Tweaks/Solar-Tweaks#341]
**Describe the bug**
A message saying connecting and i can't use lunar cosmetics. 

**To Reproduce**
1. Press Shift
2. Lunar Cosmetics
3. See error

**Expected behavior**
I expected to have all the cosmetics

**Actual behaviour**
Connecting Message

**Screenshots**
https://prnt.sc/fSIPxsjyag86

**Environment (please complete the following information):**
 - OS: Windows 11 x64
 - Launcher version 4.0.2
 - Patcher version
 - Solar Stats version (if applicable)

**Additional context**
nothing

**Comment by 770grappenmaker** [comment]
This means the websocket url you selected is invalid.

**Comment by neve360** [comment]
what is the right websocket?

**Comment by MopigamesYT** [comment]
Simply don't use one if you wanna pay for your cosmetics, but you can use the solar socket from here: ws://socket.solartweaks.com:8080/connect

**Comment by neve360** [comment]
when i put that socket i still get connecting message. if i disable it i haven't any cosmetics if i leave blank i get still connecting message

**Comment by neve360** [comment]
i tried with another sockets but nothing i still get that CONNECTING... message

**Comment by MopigamesYT** [comment]
Try putting wss:// instead of ws://

If it doesn't work go to https://discord.gg/wWuZCSRcYe (the solar socket discord) for more help.

**Comment by 770grappenmaker** [comment]
Or just disable the websocket module...

**Comment by neve360** [comment]
To fix i used this: ws://socket.solartweaks.com:8080/connect

**Comment by maccaxd** [comment]
having same problem but nothing works

**Comment by maccaxd** [comment]
but im on 4.0.2

**Comment by maccaxd** [comment]
what fixed it for me was wss://socket.solartweaks.com
