### ISSUE TITLE
Solar Tweaks Mac.

### ISSUE THREAD

**Issue by GrewyGG** [Solar-Tweaks/Solar-Tweaks#348]
Where are the instructions for downloading Solar Tweaks on a Mac? Because I am on a mac too and I am also having issues with JRE being invalid and I am also a little unsure what to do as there are no instructions to download Solar Tweaks for people who are on Macs. I suggest there should be a video or screen recording of someone downloading Solar Tweaks on a Macbook.

**Comment by 420hr** [comment]
click select jre when it says there is anyone and then click on bin folder. Then the jre thing will work

**Comment by GrewyGG** [comment]
I dont understand. What do you mean be "when it says there is anyone"

**Comment by 770grappenmaker** [comment]
Good idea. For now, go to your home folder, enable hidden files, select .lunarclient, then jre, 1.8 (or 1.19 or something if you're planning to play on 1.16+), click through the folders until you find a bin folder and select that
