### ISSUE TITLE
My music and sounds aren't working on solar tweaks.

### ISSUE THREAD

**Issue by GrewyGG** [Solar-Tweaks/Solar-Tweaks#350]
For some reason my music and sounds will not work on solar tweaks as I cant hear anything.
I tried f3+t but it didn't change anything.
Thanks for your time.

**Comment by tfmee** [comment]
go on lunar and install the version you are playing there first

**Comment by GrewyGG** [comment]
I don't understand what do you mean

**Comment by GrewyGG** [comment]
Can you elaborate?

**Comment by PraMinGam** [comment]
> Can you elaborate?

he means to go on lunar and run the version you're trying to run on solar tweaks on lunar first.

**Comment by 770grappenmaker** [comment]
And in the same working dir. We don't initialize minecraft assets in the game dir you select so sound will not work.
