### ISSUE TITLE
launch it and its just clean lunar

### ISSUE THREAD

**Issue by Skolus** [Solar-Tweaks/Solar-Tweaks#352]
**Describe the bug**
lunar = not modded

**To Reproduce**
1. launch
2. is normal lunar

**Expected behavior**
is modded lunar

**Actual behaviour**
is not modded lunar

**Screenshots**

**Environment (please complete the following information):**
windows
why would I know
 - Patcher version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by 770grappenmaker** [comment]
https://github.com/Solar-Tweaks/SolarPatcher/wiki/Tutorial:-Sending-Logs attach your logs
