### ISSUE TITLE
Cracked accounts support / and shift + 2 and shift + 6 lwjgl fix on linux on legacy minecraft vers

### ISSUE THREAD

**Issue by HierarchyMan** [Solar-Tweaks/Solar-Tweaks#361]
my main reason for using solar tweaks was that it had a lot of customization
even more than lunar qt
but it lacks featurs like cracked accounts and lwjgl fix for legacy minecraft versions on linux
shift + 2 and shift + 6 returns null that makes changing to slots while shifting hard
and cracked accounts feature would make this launcher much more accesible and liked

**Comment by 770grappenmaker** [comment]
what's shift 2, shift 6 fix? Cracked accounts could be supported but right now I have exams so I won't be able to help you
