### ISSUE TITLE
JRE youselected was not found

### ISSUE THREAD

**Issue by bosszepro** [Solar-Tweaks/Solar-Tweaks#374]
**Describe the bug**
I got hsi when I click on start 
![image](https://user-images.githubusercontent.com/85964347/175562576-8dea91ef-14a1-4e61-9580-67d56d65eb23.png)

**To Reproduce**
1. Click on launch 1.8

**Actual behaviour**
A new window 
**Screenshots**

**Environment (please complete the following information):**
 - OS: WIN 11
 - Launcher version 4.0.2
 - Patcher version
 - Solar Stats version (if applicable)

**Comment by 770grappenmaker** [comment]
What did you select?

**Comment by CD64Real** [comment]
Having same problem on Win11
