### ISSUE TITLE
solar tweaks mods unable to launch and is instead launching lunar client

### ISSUE THREAD

**Issue by TRex1w** [Solar-Tweaks/Solar-Tweaks#380]
im launching solar tweaks in the solar tweaks launcher and it is telling me that config is invalid
version - 4.0.2
os - windows
![what hapened](https://user-images.githubusercontent.com/108221622/175812971-8714109b-0555-4730-9d61-1234914e3b31.PNG)

**Comment by 770grappenmaker** [comment]
That happens when your config is invalid as it suggests. Delete .lunarclient/solartweaks/config.json to fix
