### ISSUE TITLE
Particule

### ISSUE THREAD

**Issue by HypixelRBW** [Solar-Tweaks/Solar-Tweaks#381]
Redstone particle

Even if I enable all particles, restart my game or disable the lunar particles mod. I still don't see the redstone particles (very annoying in bedwars with tnt) so I think this bug comes from Solar Tweaks.

Thank you,

Gtkill

**Comment by 770grappenmaker** [comment]
Idrk what could be the cause of this but it is certainly not solar tweaks. it might be your "hypixel particle quality". try if you have the same issue on normal lunar as well

**Comment by HypixelRBW** [comment]
Merci mais je suis bête, mon problème est l'animation de la redstone.

**Comment by 770grappenmaker** [comment]
Yea, so try on normal lunar first before complaining it is solar tweaks' fault
