### ISSUE TITLE
Can't sign into Microsoft accounts

### ISSUE THREAD

**Issue by SonnyBoyyyy** [Solar-Tweaks/Solar-Tweaks#386]
**Describe the bug**

**To Reproduce**
1. install client
2. go onto client
3. open logging in menu and press "sign in with microsoft" 
4. and you will see you need to open launcher

**Expected behavior**
i can sign in

**Actual behaviour**
cant log in

**Screenshots**
![image](https://user-images.githubusercontent.com/108371271/176301521-df7b636d-9873-4d7e-8e78-154b7b0cc6f6.png)

**Environment (please complete the following information):**
 - OS: [WINDOWS]
 - Launcher version [1.8]
 - Patcher version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by 770grappenmaker** [comment]
Make sure you have the official launcher open when trying to log in
