### ISSUE TITLE
Solar Tweaks stuck on Checking LC Assets

### ISSUE THREAD

**Issue by HLQAQ** [Solar-Tweaks/Solar-Tweaks#39]
When I click launch, the loading stops at the stage shown in the image below. Can anyone help me?

<img width="1287" alt="Screen Shot 2022-04-28 at 1 00 16 PM" src="https://user-images.githubusercontent.com/102529556/165680001-d6627f45-83d7-4f66-ad26-2c7c23327846.png">

**Comment by HLQAQ** [comment]
Thanks for replying, I will try your solutions.

**Comment by RichardDorian** [comment]
You're welcome, if it worked please close the issue.

**Comment by 770grappenmaker** [comment]
Closing because I assume it got resolved; reopen if you think this is a mistake

**Comment by Sweqting** [comment]
I am on a mac and I have the same problem so I tried to use your solutions but it didnt work.
Got any other solutions
