### ISSUE TITLE
solar tweaks isnt launching

### ISSUE THREAD

**Issue by SPIKESGAMING** [Solar-Tweaks/Solar-Tweaks#394]
i tried to launch solar tweaks and i even on the keep the launcher on still the solar tweaks isnt launching please help me 
reply as quick as you can

**Comment by 770grappenmaker** [comment]
> reply as quick as you can
im a volunteer. calm down.
please attach logs as the solar patcher wiki describes

**Comment by SPIKESGAMING** [comment]
> > reply as quick as you can
> 
> im a volunteer. calm down.
> 
> please attach logs as the solar patcher wiki describes

ok so what am i supposed to do to launch it ;-;

**Comment by 770grappenmaker** [comment]
i said, attach logs as described by patcher wiki, so we can debug
