### ISSUE TITLE
Solar Tweaks Won't Update

### ISSUE THREAD

**Issue by DarxTweakin** [Solar-Tweaks/Solar-Tweaks#412]
When running Solar Tweaks it will not update to the latest Lunar update.

1. Open Solar 
2. Click on Launch 1.8

The launcher should automatically update the game after running Lunar Client's game.

**Environment (please complete the following information):**
 - OS: W11
 - Launcher version: 4.0.3 
 - Patcher version: (If you can't find this, leave blank)

**Comment by 770grappenmaker** [comment]
Not sure if solar should automatically update, did you enable skip checks?
