### ISSUE TITLE
Config Issue

### ISSUE THREAD

**Issue by ihaveWork** [Solar-Tweaks/Solar-Tweaks#413]
Hello i ahev tried to delted my config and then relanuch but it never fixes it.

![image_2022-07-08_133713699](https://user-images.githubusercontent.com/108952783/178051090-c5ff6afb-d40f-4ef2-935d-ca00b53419af.png)

**Comment by TakenMC** [comment]
go to %userprofile%\.lunarclient\solartweaks and backup and delete the config.json file
You could of had a spelling error which cause the crash

**Comment by ihaveWork** [comment]
I tried that but what do you mean by spelling error

**Comment by TakenMC** [comment]
launch lunar when it crashes go to the %userprofile%\.lunarclient\solartweaks
there should be q logs folder then go there and client latest log and post that log

**Comment by ihaveWork** [comment]
lanuch lunar or solar tweeks

**Comment by ihaveWork** [comment]
[1.8-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/9079692/1.8-latest.log)

**Comment by ihaveWork** [comment]
This is porblay a very easy fix and im just frickin dum

**Comment by TakenMC** [comment]
![image](https://user-images.githubusercontent.com/68560840/178160439-4a78744e-db3a-4e18-b778-46770d81e40e.png)
this one the launcher

**Comment by ihaveWork** [comment]
sorry

**Comment by ihaveWork** [comment]
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/9079787/launcher-latest.log)

**Comment by TakenMC** [comment]
wait it crashed then you sent it

**Comment by ihaveWork** [comment]
yes...

**Comment by ihaveWork** [comment]
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/9079796/launcher-latest.log)

**Comment by TakenMC** [comment]
send me the config.json in %userprofile%\.lunarclient\solartweaks

**Comment by ihaveWork** [comment]
you cant gitithub does not allow to send json files

**Comment by TakenMC** [comment]
rename it to .txt

**Comment by ihaveWork** [comment]
{
  "patcherVersion": "1.7",
  "debug": false,
  "enableAll": false,
  "nickhider": {
    "from": "You",
    "to": "Nicked",
    "isEnabled": false
  },
  "fps": {
    "pattern": "\u0001 %s",
    "from": "FPS",
    "to": "FPS",
    "isEnabled": false
  },
  "cps": {
    "pattern": "\u0001 %s",
    "from": "CPS",
    "to": "CPS",
    "isEnabled": false
  },
  "autoGG": {
    "from": "/achat gg",
    "to": "/achat gg",
    "isEnabled": true
  },
  "levelHead": {
    "pattern": "%s: ",
    "from": "Level",
    "to": "Hours",
    "isEnabled": true
  },
  "metadata": {
    "removeCalls": [
      "modSettings",
      "pinnedServers",
      "blogPosts"
    ],
    "isEnabled": true
  },
  "modpacketRemoval": {
    "isEnabled": false
  },
  "cloaksPlus": {
    "isEnabled": true
  },
  "windowName": {
    "from": "Lunar Client (\u0001-\u0001/\u0001)",
    "to": "LateWork",
    "isEnabled": true
  },
  "noHitDelay": {
    "isEnabled": false
  },
  "fpsSpoof": {
    "multiplier": "",
    "isEnabled": false
  },
  "customCommands": {
    "commands": {
      "qb": {
        "prefix": "/play duels_bridge_duel",
        "suffix": ""
      },
      "qbd": {
        "prefix": "/play duels_bridge_doubles",
        "suffix": ""
      },
      "db": {
        "prefix": "/duel ",
        "suffix": " bridge"
      },
      "bwp": {
        "prefix": "/play bedwars_practice",
        "suffix": ""
      }
    },
    "useHypixelCommands": true
  },
  "rpcUpdate": {
    "clientID": "920998351430901790",
    "icon": "logo",
    "iconText": "Solar Tweaks",
    "afkText": "AFK",
    "menuText": "In Menu",
    "singlePlayerText": "Playing Singleplayer",
    "versionText": "Minecraft",
    "displayActivity": true,
    "customServerMappings": {},
    "showIcon": true,
    "bigServerIcon": false,
    "isEnabled": true
  },
  "tasklistPrivacy": {
    "isEnabled": true
  },
  "hostslistPrivacy": {
    "isEnabled": true
  },
  "uncapReach": {
    "isEnabled": false
  },
  "removeFakeLevelhead": {
    "isEnabled": true
  },
  "removeHashing": {
    "className": "WMMWMWMMWMWWMWMWWWWWWWMMM",
    "method": {
      "name": "WWWWWNNNNWMWWWMWWMMMWMMWM",
      "descriptor": "(Ljava/lang/String;[BZ)Z",
      "owner": null,
      "access": null
    },
    "isEnabled": true
  },
  "debugPackets": {
    "isEnabled": false
  },
  "toggleSprintText": {
    "replacements": {
      "flying": "flying",
      "riding": "riding",
      "descending": "descending",
      "dismounting": "dismounting",
      "sneaking": "sneaking",
      "sprinting": "sprinting"
    },
    "method": {
      "name": "<clinit>",
      "descriptor": "()V",
      "owner": null,
      "access": 8
    },
    "isEnabled": false,
    "flying": "flying",
    "riding": "riding",
    "descending": "descending",
    "dismounting": "dismounting",
    "sneaking": "sneaking",
    "sprinting": "sprinting"
  },
  "reachText": {
    "pattern": "\u0001 %s",
    "from": "blocks",
    "to": "blocks",
    "isEnabled": false
  },
  "fixPings": {
    "isEnabled": false
  },
  "lunarOptions": {
    "isEnabled": true
  },
  "supportOverlays": {
    "isEnabled": true
  },
  "toggleSneakContainer": {
    "isEnabled": false
  },
  "pingText": {
    "pattern": "\u0001 %s",
    "from": "ms",
    "to": "ms",
    "isEnabled": false
  },
  "pingSpoof": {
    "pingValue": "100",
    "isEnabled": false
  },
  "clothCapes": {
    "isEnabled": true
  },
  "hurtCamShake": {
    "multiplier": 0.3,
    "isEnabled": false
  },
  "chatLimit": {
    "limit": 255,
    "isEnabled": false
  },
  "mumbleFix": {
    "isEnabled": false
  },
  "websocket": {
    "to": "wss://socket.solartweaks.com",
    "isEnabled": true
  },
  "enableWrapped": {
    "isEnabled": true
  },
  "customMods": {
    "textMods": []
  },
  "removeChatDelay": {
    "isEnabled": false
  },
  "allowCosmeticCombinations": {
    "isEnabled": false
  },
  "removeSplashBlur": {
    "isEnabled": false
  }
}

**Comment by ihaveWork** [comment]
does this work

**Comment by TakenMC** [comment]
delete that file and then try to launch the game

**Comment by TakenMC** [comment]
delete the config file and relaunch the solar tweaks launcher
you will need to change the settings on patcher

**Comment by TakenMC** [comment]
![image](https://user-images.githubusercontent.com/68560840/178161173-948a0793-40f9-45ae-9ff8-f34678048c81.png)
here and change it to what you want to

**Comment by ihaveWork** [comment]
ok

**Comment by ihaveWork** [comment]
im so dum i cant fix it

**Comment by TakenMC** [comment]
Press the windows key + r then type %userprofile%\.lunarclient\solartweaks
in that folder delete config.json
restart solartweaks launcher and it should work

**Comment by ihaveWork** [comment]
bro how does it still not work what should i do i tried doing that 3 times

**Comment by TakenMC** [comment]
oh then its a bug with the launcher and you need the devs to see

**Comment by ihaveWork** [comment]
rip

**Comment by ihaveWork** [comment]
how whould i get to talk with the devs

**Comment by TakenMC** [comment]
we need to wait for them to respond to this

**Comment by ihaveWork** [comment]
ok

**Comment by 770grappenmaker** [comment]
Please attach your log files so we can trace the issue

**Comment by ihaveWork** [comment]
Man you don't have to help me I gave up thanks for trying tho
