### ISSUE TITLE
Minecraft 1.8.9 Not Starting

### ISSUE THREAD

**Issue by rickycat29** [Solar-Tweaks/Solar-Tweaks#424]
when i start solar tweaks and use 1.8.9 version it says "starting jvm" and it crashes.
i tried uninstalling and reinstalling java and also removing version files from lunar folder (and then obv redownloading them from the lunar launcher) but it's not working.

video of what happens:
https://youtu.be/gSC-cBukq7w

**Comment by UncannyBoi** [comment]
I'm also currently experiencing the same issue. Can you turn on Debug mode in the Settings tab and look at the logs to see if it also matches the log that I have?
Logs can be found on the About tab, scroll down and there should be "Open ST folder"

**Comment by UncannyBoi** [comment]
oh yeah, after you turn on debug mode, try launching

**Comment by Lucas4b2x** [comment]
I have the same problem. 
In launcher logs it says : 
java.lang.ClassNotFoundException: com.moonsworth.lunar.genesis.Genesis

**Comment by UncannyBoi** [comment]
> 

have you tried updating Lunar Client itself? There was a recent update so you might be missing something.

**Comment by Lucas4b2x** [comment]
Yes

**Comment by UncannyBoi** [comment]
Lunar must've done something about it :/

**Comment by SaminYT** [comment]
LCQT works but the thing is all the version we install from real lunar client it dosent show there

**Comment by SaminYT** [comment]
it only shows 1.8.9

**Comment by ImJavaCode** [comment]
> Aight, confirm as Lunar doing something lmao

Yes, Lunar Client changed completely how the client is launched I think. I looked at the metadata from the lunar launch endpoint and there are lots of new jars that are being downloaded in a new directory: `C:\Users\%USERNAME%\.lunarclient\offline\multiver`.

I made a simple launcher in java that works, but when I try to add the SolarPatcher javaagent the patches do not work.
Maybe I did something wrong, but I hope that all the patches do not have to be rewritten

**Comment by rickycat29** [comment]
> > Aight, confirm as Lunar doing something lmao
> 
> Yes, Lunar Client changed completely how the client is launched I think. I looked at the metadata from the lunar launch endpoint and there are lots of new jars that are being downloaded in a new directory: `C:\Users\%USERNAME%\.lunarclient\offline\multiver`.
> 
> I made a simple launcher in java that works, but when I try to add the SolarPatcher javaagent the patches do not work. Maybe I did something wrong, but I hope that all the patches do not have to be rewritten.
> 
> EDIT: The launcher started working again for some reason after two days, so idk

it's working again for me too LMAO

**Comment by Runely999** [comment]
it's not working for me wtf

**Comment by Runely999** [comment]
it still not working

**Comment by khantknight** [comment]
also happened to me 
i do think lunar did it cuz it got a new update without an announcement

**Comment by khantknight** [comment]
(update toke very long)
