### ISSUE TITLE
Minecraft 1.8.9 not starting

### ISSUE THREAD

**Issue by Lucas4b2x** [Solar-Tweaks/Solar-Tweaks#427]
I click launch, the launcher close, but the game never start. 
I tried to reinstall, reset jre and jvm args, but the problem is still here. 
I also tried to delete config.json
In my latest launcher log there is a problem caused by java.lang.ClassNotFoundException: com.moonsworth.lunar.genesis.Genesis

**Comment by m4tizz** [comment]
Same idk how to fix it

**Comment by Tacki0n4** [comment]
I mean I fixed it by deleting lunar client

**Comment by UncannyBoi** [comment]
> I mean I fixed it by deleting lunar client and solar tweaks. Then reinstalling solar tweaks with no lunar

Already fixed by the way. You can now launch it fine without doing what you did.

**Comment by xyba1337** [comment]
Same, stuck on "Starting JVM"

**Comment by Runely999** [comment]
i still can't open wen i lunch why??

**Comment by DARKANTO** [comment]
hi i need the solar purge
it don't start and it won't let me change the version
