### ISSUE TITLE
Mod Support

### ISSUE THREAD

**Issue by rsoley** [Solar-Tweaks/Solar-Tweaks#429]
**Is your feature request related to a problem? Please describe.**
Im always frustrated seeing some of my favorite forge/fabric mods (even the ones I make) can not run in Lunar Client or Solar Tweaks.

**Describe the solution you'd like**
Add support for fabric/forge external mods

**Describe alternatives you've considered**
Forge Mod Loader instead of LC/ST

**Additional context**

**Comment by 770grappenmaker** [comment]
Simply put, impossible
