### ISSUE TITLE
.Dmg download

### ISSUE THREAD

**Issue by Wonkybob** [Solar-Tweaks/Solar-Tweaks#440]
**Is your feature request related to a problem? Please describe.**
I would like to be able to download a dmg because I am on Mac and thats what I did for version 4.02

**Describe the solution you'd like**
Add a .DMG download for version 4.03

**Describe alternatives you've considered**
Using normal lunar client
Thanks for reading! :)

**Comment by Yiru77** [comment]
same here need a dmg a Mac compiled version

**Comment by Husk-ees** [comment]
Just build it with node
