### ISSUE TITLE
Solar-Tweaks is stuck on checking subfolders

### ISSUE THREAD

**Issue by MyPrinceIsCool** [Solar-Tweaks/Solar-Tweaks#441]
**Describe the bug**
When loading Solar-Tweaks the launcher will say checking subfolders 3/3. It will continue to do this and never load the game. I have tried leaving the launcher running for an extended period of time and even on another device. I also tried different versions of the client and nothing helped.

**To Reproduce**
1. Go to 'Solar-Tweaks launcher'
2. Click on 'Launch 1.8 (or any other version)'
3. The game never opens

**Expected behavior**
If the client would work properly the game would load.

**Actual behaviour**
What happens is the game does not load.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 & 11
 - Launcher version 4.0.3
 - Patcher version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats version (if applicable)

**Additional context**
 The launcher has been working fine for as long as I've used it, but now does not.

**Comment by quashposh** [comment]
yeah i got the same issue idk why i tried re installing it and it didnt work

**Comment by quashposh** [comment]
they just said that solar tweaks was broken for some lunar thingy

**Comment by MyPrinceIsCool** [comment]
Thanks, I saw the video

**Comment by 770grappenmaker** [comment]
Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.

**Comment by xFloppa** [comment]
For fix this problem, you do change the version on the launcher, 1.8 to 1.18, don't launch the game, ok next step change the version 1.18 to 1.8

**Comment by Deku412** [comment]
help me please I tried to open the solar tweaks but it tells me checking subfolders but it does not open could you help me please

**Comment by MyPrinceIsCool** [comment]
I don't have any association with Solar Tweaks and I do not have the
knowledge to understand and fix your problem
