### ISSUE TITLE
Patcher doesn't work and can't launch the client.

### ISSUE THREAD

**Issue by zhusun890** [Solar-Tweaks/Solar-Tweaks#443]
**Describe the bug**
Patcher doesn't work and can't launch the client.

**To Reproduce**
1. Go to 'Home'
2. Click on 'LAUNCH 1.8.9'
3. See error

**Expected behavior**
Patcher doesn't work and can't launch the client.

**Actual behaviour**
Patcher doesn't work and can't launch the client.

**Environment (please complete the following information):**
 - OS: Windows
 - Launcher version 4.0.3
 - Patcher version 1.7
 - Solar Stats version (if applicable)

**Additional context**
Probably be lunar client updating issue (It's version is 1.8.9-1e96e51/legacy, Moonsworth has just changed their branch from dev -> master to legacy dumbass lol)

Solar Patcher v1.7
Built Tue May 31 05:04:03 CST 2022
Attempting to read configuration from C:\Users\zhusun\.lunarclient\solartweaks\config.json
Loaded 23 finders from 7 containers!
Using modules CloaksPlus, ClothCapes, CustomCommands, CustomMods, FPSSpoof, HandleNotifications, HostslistPrivacy, LaunchRequestModule, Metadata, ModName, NoHitDelay, RPCUpdate, RemoveChatDelay, RuntimeData, SupportOverlays, TasklistPrivacy, UncapReach
Launching Lunar Client

Error: Couldn't find or load main class com.moonsworth.lunar.genesis.Genesis
Reason: java.lang.ClassNotFoundException: com.moonsworth.lunar.genesis.Genesis

**Comment by zhusun890** [comment]
This bug also contains on LC latest version, 1.8.9-881dd01/master.
I don't know what about 1.7 or higher version client.

**Comment by 770grappenmaker** [comment]
Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.
