### ISSUE TITLE
Solar Tweaks having issues to track launcher launching

### ISSUE THREAD

**Issue by joaom31** [Solar-Tweaks/Solar-Tweaks#446]
**Describe the bug**
Solar Tweaks doesn't open and fails to track launcher launching

**To Reproduce**
1. Go to 'Solar Tweaks Launcher'
2. Click on 'Launch 1.8.9'
3. Scroll down to 'WARN' (On launcher-latest with debug mode on)

**Expected behavior**
Open up Solar Tweaks and be able to play

**Actual behaviour**
Launcher failing to start and giving as error message: "[WARN] [launcher] Failed to track launcher launch, ignoring it, it's not important. Error: Request failed with status code 400"

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 11
 - Launcher version 4.0.3
 - Patcher version
 - Solar Stats version (if applicable)

**Additional context**
A couple hours ago it was working fine for me and when i decide to try opening it again it stops working.
I've tried uninstalling and reinstalling and doing other stuff to fix this issue and it hasnt helped me at all.

**Comment by joaom31** [comment]
I've also went into the 1.8.9-latest notepad and it says this:
Error: Could not find or load main class com.moonsworth.lunar.genesis.Genesis
Caused by: java.lang.ClassNotFoundException: com.moonsworth.lunar.genesis.Genesis

**Comment by 770grappenmaker** [comment]
Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.
