### ISSUE TITLE
Launching Issue

### ISSUE THREAD

**Issue by TitaniumP0G** [Solar-Tweaks/Solar-Tweaks#451]
![image](https://user-images.githubusercontent.com/109407150/179342632-8202fe60-bfd4-4b14-8fca-f1b1e88f59e2.png)

When launched, an error appears, and the reason for the error appears as shown in the screenshot above

I deleted the config file, but the same error keeps coming up

**Comment by 770grappenmaker** [comment]
Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.
