### ISSUE TITLE
Launch issue

### ISSUE THREAD

**Issue by iconicda** [Solar-Tweaks/Solar-Tweaks#456]
I just wanted to play mc so i launched soolar tweaks i clicked 1.7 was waiting some time and i says checking sufolders 3/3 and nothing more

**Comment by khantknight** [comment]
it also happened to me, when i launch other version than 1.8.9 it happened (but when i launch 1.8.9 it said 'starting JVM' and the launcher crashed)

**Comment by Reencarnaciones** [comment]
it also happened to me, when i launch other version than 1.8.9 it happened (but when i launch 1.8.9 it said 'starting JVM' and the launcher crashed)
khantknight that happened to me too

**Comment by Clumsy1203** [comment]
may i ask what version of solar u are using?

**Comment by Clumsy1203** [comment]
if u use 4.0+ then switch to 3.0+ for it to work

**Comment by Clumsy1203** [comment]
thats wat i did

**Comment by khantknight** [comment]
i dont know how to get the 3.0 version

**Comment by iconicda** [comment]
> 

idk u mean 3+ ram alocation or version of solar tweaks if u mean version send me link cause i cant find it and if u mean alocation i did and itt still not working

**Comment by 770grappenmaker** [comment]
Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.

**Comment by khantknight** [comment]
i was using 4.0, i will test if 3.0 works
but i dont know how to download it
