### ISSUE TITLE
Hi, Hello, Solara starts and nothing happens, the launcher turns off and nothing with Minecraft ... in the logs, every other launcher works properly, help

### ISSUE THREAD

**Issue by Fabianski69** [Solar-Tweaks/Solar-Tweaks#457]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 770grappenmaker** [comment]
Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.
