### ISSUE TITLE
launch issue please help

### ISSUE THREAD

**Issue by munkedad** [Solar-Tweaks/Solar-Tweaks#458]
**Describe the bug**
when i launch the game doesnt start and the launcher comes back i even tried with debug mode on but there the cmd just crashes kinda
**To Reproduce**
just click launch
**Expected behavior**
game starts normally
play the game
**Actual behaviour**
game cant start
Description of what is actually happening.
the cmd is crashing and the game wont launch
**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher version [eg. 4.0.1]
 - Patcher version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats version (if applicable)

**Additional context** please help
Add any other context about the problem here.  i have tried another jre, i have tried reinstalling the client and more.
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash.
https://github.com/Solar-Tweaks/Solar-Tweaks/files/9125761/launcher-latest.log

**Comment by 770grappenmaker** [comment]
Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.
