### ISSUE TITLE
Launch Issue

### ISSUE THREAD

**Issue by Grangerre** [Solar-Tweaks/Solar-Tweaks#461]
I Cant Launch Minecraft But When I See My Log Its says this:
Error: Could not find or load main class com.moonsworth.lunar.genesis.Genesis
Caused by: java.lang.ClassNotFoundException: com.moonsworth.lunar.genesis.Genesis
And this:

**Comment by FrikidiumGithub** [comment]
The solar tweaks development team are fixing the bugs, I think you'll have to wait
