### ISSUE TITLE
launching not opening 

### ISSUE THREAD

**Issue by Clumsy1203** [Solar-Tweaks/Solar-Tweaks#464]
ok first i go to solar 4.0.3 and click start 1.8.9 and bam it does all the process of starting. when i finally says 'Starting JVM', nothing happens the game doesnt even open anything not even a crash message. 

tried : changing presets, restarting computer and solar

pls help :(

**Comment by FrikidiumGithub** [comment]
The solar tweaks development team are fixing the bugs, I think you'll have to wait

**Comment by dtomvan** [comment]
For more explanation please read: https://github.com/orgs/Solar-Tweaks/discussions/460#discussioncomment-3163508

**Comment by Reencarnaciones** [comment]
ok first i go to solar 4.0.3 and click start 1.8.9 and bam it does all the process of starting. when i finally says 'Starting JVM', nothing happens the game doesnt even open anything not even a crash message.

tried : changing presets, restarting computer and solar

pls help me too

**Comment by dtomvan** [comment]
Same thing, Solar Tweaks got broken by Lunar, the Solar devs couldn't foresee this change and thus it is not something they are responsible for.

**Comment by PandaCompany-byte** [comment]
um I I'm having the same problem here, so is there anything we could try to get it to work?

**Comment by DylanZutner** [comment]
No its down currently
