### ISSUE TITLE
Solar Tweaks "Launching but not running anything.

### ISSUE THREAD

**Issue by Micah73** [Solar-Tweaks/Solar-Tweaks#470]
When I press the "Launch 1.8.9" Button it loads and after 3 seconds it goes back to the original green launch 1.8.9 button but the actualy client/game never pops up or launches.

**Comment by Luis2000yt** [comment]
I have the same Problem

**Comment by 770grappenmaker** [comment]
Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.
