### ISSUE TITLE
Immediately closing the launcher upon "Starting JVM"

### ISSUE THREAD

**Issue by goosq** [Solar-Tweaks/Solar-Tweaks#471]
**Describe the bug**
Game doesn't even launch

**To Reproduce**
1. Go to 'Solar Tweaks client'
2. Click on 'Launch 1.8.9'
3. See "Starting JVM"
4. Launcher immediately closes and game doesn't open.

**Expected behavior**
The game opens and the launcher stays open (depends on settings, I have it set to keep open).

**Actual behaviour**
Launcher immediately closes and game doesn't open

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - Launcher version [4.0.3]
 - Patcher version []
 - Solar Stats version (n/a)

**Comment by Beatrut** [comment]
https://user-images.githubusercontent.com/109489212/179429682-32daf62b-1ce3-42e5-bbcd-f3096ea1ed05.mp4

This is what happens

**Comment by 770grappenmaker** [comment]
Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.
