### ISSUE TITLE
Lunar not launching after loading

### ISSUE THREAD

**Issue by elauqzz** [Solar-Tweaks/Solar-Tweaks#472]
### Describe the bug

The launcher runs perfectly, but when i try to start the game it just doesn't start it, it doesn't get stuck at any step, it loads like normal but then it doesn't launch the game when it should

### To Reproduce

1. Start Solar Tweaks
2. Try to launch the game
3. Wait for it to load

### Expected behavior

Lunar Client launching normally with Solar Tweaks.

### Actual behaviour

Game not launching and launcher just staying there with the green button

### Screenshots

n/a

### Environment (please complete the following information):
 - OS: Windows
 - Launcher version: 4.0.3 (latest)
 - Patcher version: 

##### Add any other context about the problem here.  
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)
launcher logs [launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/9128547/launcher-latest.log)
game logs [1.8.9-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/9128546/1.8.9-latest.log)

**Comment by 770grappenmaker** [comment]
Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.
