### ISSUE TITLE
wont launch

### ISSUE THREAD

**Issue by Publl07** [Solar-Tweaks/Solar-Tweaks#473]
**Describe the bug**
seems like everyone is having trouble so i hope its just a bug with the launcher as a whole but with me (and with very few people ive seen) my launcher is stuck on "launching... checking subfolders 3/3" and i dont know how to fix it because i havent seen anyone else with the problem. patcher settings on (everything else off): freelook, overlays, discord rpc, remove hit delay (not sure what it does ngl just had it on for testing and didnt feel like turning it off), window title, remove hashing, adjust hurt cam, and remove lunar chat cooldown. launcher settings i have: 4000mb allocated, close launcher after launch, skip checks turned off, no jre applied. i am on windows 10.
![image](https://user-images.githubusercontent.com/105193154/179438880-f8c79e96-2b90-424d-a3c6-583c377f72ba.png)
![image](https://user-images.githubusercontent.com/105193154/179438921-485621fd-9565-4dd8-ba15-a3df93f48968.png)

**Comment by xyba1337** [comment]
For me, it goes through the entire process then the launcher closes, but the game doesn't open.
Will there be a fix soon?

**Comment by Ashwinswamy19** [comment]
yep ive got the same problem and dont know how to fix it

**Comment by 02luky** [comment]
the game doest open i hope u guys can fix this

**Comment by quugisonfire** [comment]
same bro already made a report

**Comment by 770grappenmaker** [comment]
Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.
