### ISSUE TITLE
I have no idea how to dowload solar tweaks for mac i really need help and I have also heard about JRE stuffing up so i might need some help with that too I think they need to add a tutorial for mac to download solar tweaks

### ISSUE THREAD

**Issue by crapedee3** [Solar-Tweaks/Solar-Tweaks#474]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Husk-ees** [comment]
Join the discord that might help
