### ISSUE TITLE
HOW TO FIX SOLAR

### ISSUE THREAD

**Issue by cooooops** [Solar-Tweaks/Solar-Tweaks#477]
So basically its stuck on 3/3 subfolders loading trying to load (its on mac)
And some people said to get version 3 instead of 4 but how do I get that?
Could someone help please.
Thanks :)

**Comment by Adrirgamer** [comment]
Every bug with solar tweaks is due to the new lunar update, so Solar is down.
The dev are probably working as hard as they can but lunar is making their life impossible.
They almost tripled launch time just to make solar tweaks not useable.

**Comment by cooooops** [comment]
oh k are they purposely trying to make it not useable?

**Comment by GitZurah** [comment]
yes, they are

**Comment by 770grappenmaker** [comment]
> No they arent purposely breaking it its because of Genesis.
> they are using Genesis now because its way easier for them to have more compatibility

In my opinion, implementing a feature that makes the UX worse isn’t justified if it makes it easier for the dev, I call that lazy. They intentionally make all class patching more complicated though, which doesn’t make sense to me and the only explanation is to make the life of devs like me harder (for example, lunar-util just got worthless…)
