### ISSUE TITLE
Solor client Launches but minecraft never opens

### ISSUE THREAD

**Issue by quugisonfire** [Solar-Tweaks/Solar-Tweaks#485]
**Describe the bug**
when i press launch it will go through starting process then says starting jvm Laucher closes then nothing happens i waited like 5 minutes and still nothing happend.

**To Reproduce**
1. Press green button
2. Wait...
3. Launcher closes
4. nothing happens...

**Expected behavior**
For minecraft to launch at least 1 min after Launcher closes.

**Actual behaviour**
Launcher closes but nothing ever happens after that.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: Windows 10
 - Launcher version 4.0.3
 - Patcher version 
 - Solar Stats version n/a

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by DylanZutner** [comment]
Same with me i think lunar is trying to make solar unuseable

**Comment by 770grappenmaker** [comment]
Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.
