### ISSUE TITLE
Launcher Crashes On Starting JVM

### ISSUE THREAD

**Issue by DylanZutner** [Solar-Tweaks/Solar-Tweaks#486]
https://user-images.githubusercontent.com/92005964/180097101-fcf36c57-5dfa-401b-86c9-7f6f21119cb9.mp4

**Comment by joaom31** [comment]
Solar tweaks is down

**Comment by 770grappenmaker** [comment]
Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.

**Comment by DylanZutner** [comment]
thank you for answering
