### ISSUE TITLE
staring jvm bug

### ISSUE THREAD

**Issue by MATTILGAMER** [Solar-Tweaks/Solar-Tweaks#487]
https://user-images.githubusercontent.com/106397461/180180510-e261c5f2-f229-4596-ac9b-deed539714a0.mp4

**Comment by MATTILGAMER** [comment]
java.lang.ClassNotFoundException: com.moonsworth.lunar.genesis.Genesis

**Comment by joaom31** [comment]
Solar Tweaks is down

**Comment by 770grappenmaker** [comment]
Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.
