### ISSUE TITLE
Vape V4 doesn't work on Solar Tweaks with custom title bar on.

### ISSUE THREAD

**Issue by iBon-Bon** [Solar-Tweaks/Solar-Tweaks#49]
Basically just crashes the game when injected whenever custom title bar is on.

**To Reproduce**
1. Inject Vape v4 with custom title bar on

**Expected behavior**
for vape to work normally

**Actual behaviour**
crashes the game

**Comment by iBon-Bon** [comment]
nevermind it doesn't even work with custom title bar off

**Comment by 770grappenmaker** [comment]
Bruh, why would you want to inject vape? If it crashes the game then please try attaching some logs or provide more context, i have literally no clue what is happening.

**Comment by RichardDorian** [comment]
Closing the issue, we are not vape support bro. A solution we can maybe provide to you: stop cheating. Have a good day
