### ISSUE TITLE
I dunno

### ISSUE THREAD

**Issue by crapedee3** [Solar-Tweaks/Solar-Tweaks#490]
So when i click on the zulu folder bin then it say checking subfolders and it just sits like that forever

**Comment by crapedee3** [comment]
pls help

**Comment by RatchanonDev** [comment]
Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while the dev fix this.

**Comment by crapedee3** [comment]
ok but im on mac 4.0.1

**Comment by crapedee3** [comment]
so yeah.... that doesnt rlly help
