### ISSUE TITLE
mc not launching

### ISSUE THREAD

**Issue by Corey-IO** [Solar-Tweaks/Solar-Tweaks#491]
whenever i open mc with solar tweaks it closes the launcher but doesnt open the actual game. it doesnt give a crash code or even open the launcher again, it just takes me to my home screen.

**Comment by Z1xus** [comment]
Here's what one of the maintainers replied:
> Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.

**Comment by Corey-IO** [comment]
> Here's what one of the maintainers replied:
> 
> > Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.

ohhh makes sence

**Comment by Corey-IO** [comment]
> Here's what one of the maintainers replied:
> 
> > Solar Tweaks currently doesn’t work because of a breaking change by lunar. Please be patient while we fix this.

were do i find updates on solar tweaks?

**Comment by RichardDorian** [comment]
The auto updater will do the job, don't worry about it. If you are on another platform that Windows you'll have to update manually. You can get the updated binaries on the Release page of this repository when they'll be available.
