### ISSUE TITLE
can't get past launching

### ISSUE THREAD

**Issue by shicurt230** [Solar-Tweaks/Solar-Tweaks#495]
**Describe the bug**
can't get past launching says it's "checking subfolders 3/3" and doesn't move past that, if i try to skip checking it stops at starting jvm and doesn't do anything

**To Reproduce**
i don't know if you can

**Expected behavior**
for the game to start

**Actual behaviour**
it's getting stuck

**ScreenShots**
![image_2022-07-24_212028595](https://user-images.githubusercontent.com/109930497/180675624-9529df6c-a007-49a7-961b-76f3ae651a08.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Launcher version 4.0.3
 - Patcher version 1.7.1
 - Solar Stats version (i don't have this)

**Comment by GirthyPablo** [comment]
Try going on lunar and letting it update and then go back to solar and try again

You shouldnt need to skip checks the second time around

**Comment by Ishxxn4** [comment]
> Try going on lunar and letting it update and then go back to solar and try again
> 
> You shouldnt need to skip checks the second time around

It still has not worked.
I have the same issues as the post (same version also)
