### ISSUE TITLE
It's still not working(Solar tweaks launching)

### ISSUE THREAD

**Issue by Leoleo037** [Solar-Tweaks/Solar-Tweaks#498]
I just downloaded the latest version of solar tweaks (V 4.0.3 ) and the change log said fixed launching problems but i downloaded it and it still dont work

![image](https://user-images.githubusercontent.com/109957554/180757168-cdc44bb8-324e-4db2-acad-befcbc89788e.png)

**Comment by joaom31** [comment]
the V 4.0.3 was put on github before all of this was happening.

You need to wait for Solar Tweaks to fix this bug in the next version which should release in these few days
