### ISSUE TITLE
i cannot launch it

### ISSUE THREAD

**Issue by sandwichlol** [Solar-Tweaks/Solar-Tweaks#503]
whenever I try to launch solar tweaks, it gets stuck on the patching game part of the launching.

Click launch.
(At least that is what it is for me)

**Expected behavior**
I expected it to launch normally and works but it always gets stuck on patching game

I am on windows.
The version is on 4.0.3

**Comment by Leoleo037** [comment]
Yeah me too

**Comment by Leoleo037** [comment]
mine says Starting JVM then closed and didnt launch

**Comment by Reencarnaciones** [comment]
that happened to me lol
