### ISSUE TITLE
MacOs Solar Tweaks JRE

### ISSUE THREAD

**Issue by Niraj-MC** [Solar-Tweaks/Solar-Tweaks#504]
Solar Tweaks is amazing. But, whenever I attempt to launch it an error says "The JRE you selected was not found or is invalid.

Please select a valid JRE in the settings page or download one using the JRE downloader". How do I fix this? Below is a screenshot of the error. Thank you!
![Screen Shot 2022-07-25 at 4 19 09 PM](https://user-images.githubusercontent.com/96322875/180890588-43d58e4f-b41a-42f5-81b7-5926406248a5.png)

**Comment by razoring** [comment]
I've made a fix, see below:
https://github.com/Solar-Tweaks/Solar-Tweaks/discussions/382

**Comment by Niraj-MC** [comment]
![Screen Shot 2022-07-27 at 12 25 09 PM](https://user-images.githubusercontent.com/96322875/181355471-bc81110b-0df7-4aa6-bddc-61f9f545c6c2.png)
its stuck on this

**Comment by Niraj-MC** [comment]
also i have no config folder in the said location

**Comment by banhmikepxucxich** [comment]
redownloading and deleting the solar tweaks folder in application support doesn't fix this issue and also why are there only builds for linux and windows in the latest release? i tried to build the app again but I stumbled on this error
<img width="385" alt="image" src="https://user-images.githubusercontent.com/62416957/182149993-87bf9ecd-6418-4a28-a409-26a6005e1991.png">
here's the stacktrace btw
```
at exithandler (node:child_process:406:5)
    at ChildProcess.errorhandler (node:child_process:418:5)
    at ChildProcess.emit (node:events:520:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
btw, `npm run serve` worked just fine

but I still get stuck on the checking subfolders part

the jre I'm using is lunar clients jre which is in
`<ur macos profile username>/.lunarclient/jre/1.8/<zulu macos version idk it updates>/bin/`
still got stuck on the checking subfolders 3/3 part still

**Comment by banhmikepxucxich** [comment]
the issue is still there when i tried to use azul's java 18 jre (I selected the bin folder)

**Comment by banhmikepxucxich** [comment]
from all my limited javascript knowledge i believe it got stuck at line 60 in [minecraft.js](https://github.com/Solar-Tweaks/Solar-Tweaks/blob/main/src/javascript/minecraft.js) I think it is because of the await check if folder exists.

**Comment by banhmikepxucxich** [comment]
launching with debug mode on doesnt do anything there also. i thought launching with skip checks would work but it would get stuck at starting jvm so that sucks even with the lunar jre I still cant get it to work

**Comment by Niraj-MC** [comment]
same
