### ISSUE TITLE
Auto text patcher not available for other servers

### ISSUE THREAD

**Issue by AccountIsStolen** [Solar-Tweaks/Solar-Tweaks#505]
Enabling Auto text only works with Hypixel where it is disabled, but it doesn't work for other servers like moxmc.net
Is there a solution where the features can be unblocked for all servers?
![image](https://user-images.githubusercontent.com/110089912/181191132-3ede6b43-611a-4107-a6a4-95769d3d7969.png)

**Comment by RichardDorian** [comment]
You can remove the classic per server mod blocking behavior by enabling the "Block mods packet" module.
