### ISSUE TITLE
When i click launch launching stop at Checking Subfolders

### ISSUE THREAD

**Issue by xgdszef** [Solar-Tweaks/Solar-Tweaks#506]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher version [eg. 4.0.1]
 - Patcher version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by Targetor** [comment]
I got the SAME Exact glitch, I believe it's caused by the Recent Lunar Client Update, You see Solar Tweak Relies on Lunar client inorder to do Anything with Solar Tweaks.

**Comment by wbaiyu** [comment]
I am on Mac, I stuck here. How should I do??

**Comment by NVGAT** [comment]
same here on windows 10

**Comment by xFloppa** [comment]
For fix this problem, you do change the version on the launcher, 1.8 to 1.18, don't launch the game, ok next step change the version 1.18 to 1.8

**Comment by INFERNUS370** [comment]
Go to '...'
Click on '....'
Scroll down to '....'
See error
you didnt write anyrhing
