### ISSUE TITLE
Solar tweaks stuck on checking lc assets

### ISSUE THREAD

**Issue by Trxykybe** [Solar-Tweaks/Solar-Tweaks#507]
everytime i try launch it its stuck on checking lc assets

**Comment by joaom31** [comment]
Solar Tweaks is down due to a lunar update. Just be patient until they release a new update

**Comment by RilaMakes** [comment]
> Solar Tweaks is down due to a lunar update. Just be patient until they release a new update

It is still happening, "Checking LC Assets" how do i fix it?
