### ISSUE TITLE
After "Starting JVM" it just resets back to "Launch 1.8.9"

### ISSUE THREAD

**Issue by zihoi** [Solar-Tweaks/Solar-Tweaks#508]
(I made a github account just for this lmao) So I was using Solar Socket for the first time to try the cosmetics and stuff, but beforehand I had already launched lunar 1.8.9 so I inserted the websocket in the patcher menu, launched 1.8.9 and expected the game to launch. But to my surprise after "Starting JVM" it just reseted back to "Launch 1.8.9" at first I thought that was normal because this was the first time I've used Solar Tweaks, but then after 5-6 minutes of waiting, no Minecraft popped up so I was confused and changed the JRE to Zulu thinking that it would fix it (It clearly didn't) sooo then I went here to report it. (Not sure if this would go to discussion or bug report so mb if I'm in the wrong place) (Video + Logs btw)

[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/9206303/launcher-latest.log)
[1.8.9-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/9206295/1.8.9-latest.log)
[1.8-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/9206296/1.8-latest.log)
https://user-images.githubusercontent.com/110153820/181441409-60d97bf2-903d-4698-8cba-fa726920e435.mp4

**Comment by joaom31** [comment]
Solar Tweaks is down due to a lunar update. Just be patient until they release a new update

**Comment by ItzMarni** [comment]
> 

Any eta?

**Comment by RealBabyMsp2k** [comment]
not yet

**Comment by zihoi** [comment]
Alright thanks [joaom31](https://github.com/joaom31)
