### ISSUE TITLE
stuck at starting jvm ( I use Mac and tried everything I could )

### ISSUE THREAD

**Issue by yourlocalcoolguy** [Solar-Tweaks/Solar-Tweaks#509]
my first problem when I downloaded solar tweaks was that I was stuck at checking subfolders, but I solve that by using skip everything from the settings, but now I'm stuck at starting jvm. I hope I can solve this because there is many mods that i wish I could try in solar tweaks.

**Comment by XDRmc** [comment]
I'm having the same issue on windows. trying to fix but to no sucsess.

**Comment by Tnixc** [comment]
I also have this problem

**Comment by GazeIsGabe** [comment]
same here

**Comment by Tnixc** [comment]
guys just use lunar-client-qt

**Comment by xFloppa** [comment]
For fix this problem, you do change the version on the launcher, 1.8 to 1.18, don't launch the game, ok next step change the version 1.18 to 1.8
