### ISSUE TITLE
Cracked accounts support

### ISSUE THREAD

**Issue by NichuNaizam** [Solar-Tweaks/Solar-Tweaks#510]
**Is your feature request related to a problem? Please describe.**
This is about cracked accounts support
For people who dont have real minecraft or microsoft (as of migration) they use cracked accounts
like tlauncher

**Describe the solution you'd like**
An agent which allows to login as a offline user in the lunar client

**Additional context**
This would help people without actual minecraft in having the true lunar client experience

**Comment by cipherwithadot** [comment]
sick

**Comment by Dn030** [comment]
Cy0ze leaked some solar-tweaks v5 screenshots and there is a module where you can get put in agents. But if you do create such an agent or get it from a repo you wont be able to use cosmetics or other things even with the solar socket (web socket)

**Comment by cipherwithadot** [comment]
:O

**Comment by NichuNaizam** [comment]
> Cy0ze leaked some solar-tweaks v5 screenshots and there is a module where you can get put in agents. But if you do create such an agent or get it from a repo you wont be able to use cosmetics or other things even with the solar socket (web socket)

we can use the cracked account agent of lunar client qt
it would work right? if we can put on custom agents

Also why cant we use Solar Socket if we put in custom agents
curious about that
