### ISSUE TITLE
Easymc.io integration

### ISSUE THREAD

**Issue by DanceOfEternity** [Solar-Tweaks/Solar-Tweaks#511]
**Is your feature request related to a problem? Please describe.**
I think it would be better to have an integration for easymc.io because there are many people who do not have a premium account, and the features offered by easymc are better than other alt services such as being able to use the account you use again, in short, with the integration of easymc.io, people who do not have a premium account can use premium.

**Comment by VJChatur** [comment]
ye

**Comment by VJChatur** [comment]
can u tell me where to find the progress of the solar tweaks update if u know
