### ISSUE TITLE
Solar Tweaks won't build on macos and gets stuck on checking subfolders

### ISSUE THREAD

**Issue by banhmikepxucxich** [Solar-Tweaks/Solar-Tweaks#517]
ngl solar tweaks was perfect when i first downloaded it and but i get stuck on this screenshot
<img width="435" alt="image" src="https://user-images.githubusercontent.com/62416957/182156502-a784be9f-aa24-4746-a8bb-39b260897e54.png">
redownloading and deleting the solar tweaks folder in application support doesn't fix this issue and also why are there only builds for linux and windows in the latest release? i tried to build the app again but I stumbled on this error
<img width="385" alt="image" src="https://user-images.githubusercontent.com/62416957/182149993-87bf9ecd-6418-4a28-a409-26a6005e1991.png">
here's the stacktrace btw
```
at exithandler (node:child_process:406:5)
    at ChildProcess.errorhandler (node:child_process:418:5)
    at ChildProcess.emit (node:events:520:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
btw, `npm run serve` worked just fine

but I still get stuck on the checking subfolders part

the jre I'm using is lunar clients jre which is in
`<ur macos profile username>/.lunarclient/jre/1.8/<zulu macos version idk it updates>/bin/`
still got stuck on the checking subfolders 3/3 part still

the issue is still there when i tried to use azul's java 18 jre

from all my limited javascript knowledge i believe it got stuck at line 60 in [minecraft.js](https://github.com/Solar-Tweaks/Solar-Tweaks/blob/main/src/javascript/minecraft.js) I think it is because of the await check if folder exists.

launching with debug mode on doesnt do anything there also. i thought launching with skip checks would work but it would get stuck at starting jvm so that sucks even with the lunar jre I still cant get it to work

**Comment by Marioc4raft** [comment]
Same issue with windows

**Comment by Elementeee** [comment]
I'm having the same problem.

**Comment by yourlocalcoolguy** [comment]
its funny how people who made solar tweaks only show how to fix it in windows ( I use Mac too )

**Comment by NVGAT** [comment]
literally same thing on windows 10, idk if its a universal issue or if its just when u build from source

**Comment by xFloppa** [comment]
For fix this problem, you do change the version on the launcher, 1.8 to 1.18, don't launch the game, ok next step change the version 1.18 to 1.8

**Comment by banhmikepxucxich** [comment]
> For fix this problem, you do change the version on the launcher, 1.8 to 1.18, don't launch the game, ok next step change the version 1.18 to 1.8

What i am taking about is that it wont build on macos, the latest release doesnt have a macos build

**Comment by banhmikepxucxich** [comment]
> For fix this problem, you do change the version on the launcher, 1.8 to 1.18, don't launch the game, ok next step change the version 1.18 to 1.8

it still gets stuck on checking subfolders 3/3

**Comment by banhmikepxucxich** [comment]
> For fix this problem, you do change the version on the launcher, 1.8 to 1.18, don't launch the game, ok next step change the version 1.18 to 1.8

this won work because what it does is refreshing the launch 1.8 page, and what im talking about is on macos and the newer versions have prebuilt packages only for linux & windows
