### ISSUE TITLE
Launcher closing, the game not opening.

### ISSUE THREAD

**Issue by jenotsbo** [Solar-Tweaks/Solar-Tweaks#518]
Okay, so, when I'm in the launcher, everything is fine, works as usual. I launch the game, everything goes smoothly, but when the solar tweaks launcher closes, the game does not open at all. What might be the issue here?

**Comment by jenotsbo** [comment]
The solar tweaks launcher closes by itself, as if the game were to launch, and the ''solar tweaks'' launcher, going away, or being hidden, or whatever. But the game does not launch.

**Comment by Dn030** [comment]
Rad‘s Solar Tweaks fix on youtube should help you

**Comment by jenotsbo** [comment]
> Rad‘s Solar Tweaks fix on youtube should help you

Tried. Nothing worked.

**Comment by jenotsbo** [comment]
I've tried so many youtube tutorials, even shit I thought on my own would work. It kind of did, the game still didn't launch. But Rad's video just gives me an jre error.

**Comment by Dn030** [comment]
Try using the Debug Mode option and send me the log it outputs from the cmd, cause if you get a Pixel Acceleration error then youre on the same page as me honestly and we cant do anything about it until Cy0ze releases v5 (I have told him about the bug)
