### ISSUE TITLE
Launching, then says error.

### ISSUE THREAD

**Issue by Goggless** [Solar-Tweaks/Solar-Tweaks#519]
This is the error I am getting at the end of the .txt
`[WARN] [launcher] Failed to track launcher launch, ignoring it, it's not important. Error: Request failed with status code 400`

**Comment by swhnGH** [comment]
i got the same issue when launching st 1.8.9
[WARN] [launcher] Failed to track launcher launch, ignoring it, it's not important. Error: Request failed with status code 400
