### ISSUE TITLE
Lunar is not launcjing

### ISSUE THREAD

**Issue by c0ps0n** [Solar-Tweaks/Solar-Tweaks#522]
While launching lc it keeps aborting thios process. In logs i can see:
Error: Could not find or load main class com.moonsworth.lunar.genesis.Genesis
Caused by: java.lang.ClassNotFoundException: com.moonsworth.lunar.genesis.Genesis
I reinstalled and still nothing

**Comment by Ilikesolartweaks** [comment]
Same is happening to me
