### ISSUE TITLE
Unofficial workaround fixing failed Solar-Tweaks launch

### ISSUE THREAD

**Issue by wusung** [Solar-Tweaks/Solar-Tweaks#523]
## Purpose
The tutorial shows the workaround how to fix the failed Solar-Tweaks launch. This is an unofficial patch. This means that you WON'T be granted ANY official support. Use at your own discretion.

## Installation
1. Download [unofficial patch](https://github.com/wusung/Solar-Tweaks/releases/download/v4.0.3/Solar.Tweaks.Setup.4.0.4-B_unofficial.exe) installer.
1. Delete old solar-patcher.jar in `%HOMEPATH%\.lunarclient\solartweaks\solar-patcher.jar`.
1. Double click the downloaded installer in step 1.

## Launching
1. Before launching minecraft in Solar-Tweaks, you maybe have to login your minecraft account in Lunar client and start any version of minecraft at once.
1. In tab *Patcher*, `Change ping value` MUST be disabled. In this version, it cause lunar client fail to start.
  ![image](https://user-images.githubusercontent.com/5467467/183260011-5c5dbcb4-edd3-48e9-9abc-751ffa5394cf.png)

## Limitation
- Only for windows

**Comment by dtomvan** [comment]
@wusung You could PR, @RichardDorian will look at it and decide wether it would be merged in the official repo.

**Comment by wusung** [comment]
> @wusung You could PR, @RichardDorian will look at it and decide wether it would be merged in the official repo.

To make the official Solart-Tweaks works. There are two thing to do. 
- The latest version of SolarPatcher jar in https://github.com/Solar-Tweaks/SolarPatcher should be deployed to https://server.solartweaks.com/api/updater/?item=patcher&version=1.7.2 
- The updater.index should change to 1.7.2 in https://server.solartweaks.com/api/updater/index .It should like this.
   ```json
   {"ok":true,"index":{"stable":{"launcher":"4.0.3","patcher":"1.7.1","solarstats":"1.0.0"}}}
   ```

**Comment by wusung** [comment]
v4.0.4 had fixed the issue.
