### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by endrmen9487** [Solar-Tweaks/Solar-Tweaks#533]
I open my solar tweaks but game dont start I cant fix this config error please help me thank you :)
(My English is very bad)
![螢幕擷取畫面 2022-08-10 161059](https://user-images.githubusercontent.com/110974938/183872786-4372b633-a3ee-418a-ba4c-12b8f41b4b4b.png)

**Comment by Ilikesolartweaks** [comment]
![image](https://user-images.githubusercontent.com/110793882/184070291-ecd82a92-fec1-4669-9db6-9b6eb9f8b44a.png)
try this maybe
