### ISSUE TITLE
my mc doesnt launch after clicking launch button

### ISSUE THREAD

**Issue by lithron** [Solar-Tweaks/Solar-Tweaks#534]
my mc doesn't launch after clicking the launch button

1.click launch button and wait

**Expected behavior**
mc launches

**Actual behavior**
launcher closes but nothing happens after

**Environment (please complete the following information):**
 - OS: Windows 11
 - Launcher version 4.0.3
 - Solar Stats version (i dunno what this is)
[1.8.9-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/9300381/1.8.9-latest.log)

**Comment by hridyan** [comment]
Same
But Windows 10

**Comment by Ilikesolartweaks** [comment]
same but w10

**Comment by jsun969** [comment]
same but w10
