### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by unscxp** [Solar-Tweaks/Solar-Tweaks#540]
Whenever I try to launch Solar Tweaks This comes 

![image](https://user-images.githubusercontent.com/111187689/184498086-9c9b05fd-8dcb-4934-b9c9-f5e33cb199ec.png)

And Yes I already have tried to delete the config but whenver I delete it and try to launch the game again the same thing comes and the config reinstalls itself So Please anyone help Ive been having this error for 1 month now

**Comment by cecatjustanoob** [comment]
I have this situation too
but i can't solve it:(
