### ISSUE TITLE
Stuck on Checking subfolders 3/3

### ISSUE THREAD

**Issue by Ashwinswamy19** [Solar-Tweaks/Solar-Tweaks#541]
it doesnt launch

**Comment by SatisfiedSushi** [comment]
same for me here idk whats going on

**Comment by Marioc4raft** [comment]
x3

**Comment by Idontuseswords** [comment]
x4

**Comment by xFloppa** [comment]
For fix this problem, you do change the version on the launcher, 1.8 to 1.18, don't launch the game, ok next step change the version 1.18 to 1.8

**Comment by GooseBrother** [comment]
> For fix this problem, you do change the version on the launcher, 1.8 to 1.18, don't launch the game, ok next step change the version 1.18 to 1.8

I love you
