### ISSUE TITLE
Not launching

### ISSUE THREAD

**Issue by PichuDestroyer** [Solar-Tweaks/Solar-Tweaks#544]
When launching, it gets stuck on checking subfolders 3/3

**To Reproduce**

Launch normally

**Actual behaviour**Not launching

**Screenshots**

**Environment (please complete the following information):**
 - Windows
 - Launcher version: 4.0.3
 - Patcher version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by xFloppa** [comment]
For fix this problem, you do change the version on the launcher, 1.8 to 1.18, don't launch the game, ok next step change the version 1.18 to 1.8
