### ISSUE TITLE
Sound not working on 1.18.2

### ISSUE THREAD

**Issue by Dynvsty** [Solar-Tweaks/Solar-Tweaks#545]
**Describe the bug**
After launching 1.18.2 my game won't have any audio, or subtitles.

**To Reproduce**
1. Go to the launcher
2. Click on 1.18.2
3. Click launch game
4. No sound

**Expected behavior**
I expect to hear music and sounds

**Actual behaviour**
No audio for anything in game

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows
 - Launcher version: 4.0.4B
 - Patcher version: 1.7

**Additional context**
I have tried: Running the program as administrator, launching lunar client in the same directory, F3 T, Changing audio output device.
My audio and sound works on all other apps

**Comment by ItzPugz123** [comment]
i had the same problem on 1.17 as well

**Comment by Dynvsty** [comment]
Still no audio with the latest launcher

**Comment by 1337Bartek** [comment]
same

**Comment by xBela** [comment]
for me it doesnt even start on 1.18

**Comment by Dynvsty** [comment]
> for me it doesnt even start on 1.18

You have to launch 1.18 normal lunar first

**Comment by xBela** [comment]
> > for me it doesnt even start on 1.18
> 
> You have to launch 1.18 normal lunar first

ok thx but now the sound doesnt work on 1.18
