### ISSUE TITLE
Solar Launcher closes after starting 1.8.9, but the game just doesnt appear.

### ISSUE THREAD

**Issue by Crescendowo** [Solar-Tweaks/Solar-Tweaks#549]
**Describe the bug**
As I said before, the game wont start after the launcher closes. Nothing appears. Seriously, nothing. 

**To Reproduce**
1. I don't think i really have to describe this ;-;
2. still dont know
3. y you here
4. no i seriously dont know

**Expected behavior**
I expected the game to launch.

**Actual behaviour**
😭 omfg why do i have to do this so many times. 

**Screenshots**
Like, bro 💀... It just wont start

**Environment (please complete the following information):**
 - OS: [Windows]
 - Launcher version [eg. 4.0.3]
 - Patcher version [eg. 1.6] (If you can't find this, leave blank)

**Comment by CrazeXD** [comment]
Still happening now
Using the latest version on Windows 11

**Comment by DarkGamer209788** [comment]
Some logs would help. On your computer, press Win + R and type in .lunarclient . Press ok, then go to the solartweaks folder, then  the logs folder and upload those files here.

**Comment by xBela** [comment]
what files? my sound doesnt work aswell
