### ISSUE TITLE
Error: Spawn Java Eacces

### ISSUE THREAD

**Issue by DarkGamer209788** [Solar-Tweaks/Solar-Tweaks#570]
Solar tweaks launcher does not launch the game

**To Reproduce**

**Expected behavior**
Launch Lunar 1.8.9 with all the solar tweaks

**Actual behaviour**
Nothing launches, launcher is stuck on starting JVM.

**Environment (please complete the following information):**
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/9422982/launcher-latest.log)
 - OS: Windows 10
 - Launcher version 4.0.4B
 - Patcher version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats version (if applicable)

**Additional context**
1.8.9 Logs are blank as nothing launches
Redownloaded Zulu and solar tweaks many times

**Comment by wusung** [comment]
Update Solar-Tweaks to version v4.0.4, it'll probably fix your issue.

**Comment by DarkGamer209788** [comment]
Sorry for the late reply, but I did install 4.04. Not only that, I had the same problem happen to with the normal lunar client, and running it as admin solved it. I ran Solar tweaks as admin and that solved the problem. Thank you for your help.
