### ISSUE TITLE
game not launching

### ISSUE THREAD

**Issue by Xsedi** [Solar-Tweaks/Solar-Tweaks#577]
**Describe the bug**
after clicking launch the game just doesn't open

**To Reproduce**
1. Go to 'Patcher and change the settings'
2. Click on 'launch'
3. Launcher gets closed and nothing happens

**Expected behavior**
The game launches and works as normal or atleast gives an error message.

**Actual behaviour**
The game doesn't open at all

**Environment (please complete the following information):**
 - OS: Windows 10
 - Launcher version 4.0.4
 - Patcher version 
 - Solar Stats version (if applicable)

**Additional context**
[1.8.9-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/9439315/1.8.9-latest.log)
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/9439316/launcher-latest.log)

**Comment by wusung** [comment]
Remove `C:\Users\komputer\.lunarclient\offline\multiver\natives` folder before start 1.8.9 in Solar-Tweaks launcher.

**Comment by vypergit** [comment]
> 

It doesn't work just tried

**Comment by wusung** [comment]
> 1.8.9-latest.log

Would you mind uploading 1.8.9-latest.log again after the failed Solar-Tweaks launch?

**Comment by wusung** [comment]
> > 
> 
> It doesn't work just tried

Would you mind uploading 1.8.9-latest.log again after the failed Solar-Tweaks launch?
