### ISSUE TITLE
Crash when injecting vape v4 (Not supposed to)

### ISSUE THREAD

**Issue by moonpawn** [Solar-Tweaks/Solar-Tweaks#584]
**Describe the bug**
Crash when launching vape on it

**To Reproduce**
1. Go to solar tweaks and launch the game
2. Launch vape v4
3. When trying to inject, lunar crash
4. See error (Minecraft need forge on vape injector)

**Expected behavior**
Injecting normally, like it does on the real lunar client

**Actual behaviour**
Crashing, and it's from solar tweaks not vape since it launch with the lunar, without any problem

**Environment (please complete the following information):**
 - OS: Windows
 - Launcher version : Latest
 - Patcher version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats version (if applicable)

**Comment by Ashwinswamy19** [comment]
dont use vape and get good

**Comment by moonpawn** [comment]
> dont use vape and get good

Still not resolving my problem

**Comment by CSINT** [comment]
Turn off Window Title patch in patches, for lunar vape checks the version and the commit (1.8.9-a97868) to check if their mappings are up to date.
