### ISSUE TITLE
solar tweaks stuck on checking subfolders 

### ISSUE THREAD

**Issue by Opicsl** [Solar-Tweaks/Solar-Tweaks#585]
it says (checking subfolders 3/3) and then it just stays like that and never launches

**Comment by PichuDestroyer** [comment]
on which version if it is 1.8 then switch to 1.18(don't launch)then switch back to 1.8 then launch

**Comment by xBela** [comment]
for me it doesnt launch 1.18

**Comment by xLunarr** [comment]
Just switch the version to another one and then switch it back to the version you want to play.
Should work.

**Comment by oN00bs** [comment]
nope switching version not gonna work for me

**Comment by oN00bs** [comment]
pls help i have the same prob but ur solution not working
