### ISSUE TITLE
Solar Tweaks 1.8.9 not launching

### ISSUE THREAD

**Issue by 1Lightspeed1** [Solar-Tweaks/Solar-Tweaks#605]
I tried launching 1.8.9 on Solar Tweaks, but it has been checking the third subfolder for a long time now. Lunar Client works fine on 1.8.9, so that makes me believe that there is a problem with my copy of the launcher.
Here is what I see:
![image](https://user-images.githubusercontent.com/102192779/191128491-b8a7c11b-c3de-4592-8baa-3469452b5588.png)

1. Open Solar Tweaks.
2. Try launching 1.8.

What I expected: I expected the launcher to open the game after about a good 20 seconds and then I could play.
What's actually happening: The launcher takes its time checking the third subfolder.

Some additional information
 - OS: Windows
 - Launcher version: 4.0.4

**Comment by Aerolome** [comment]
Yeah, I mean, it's not launching. It just stays here on _Checking LC Assets..._

**Relevant info:**
**CPU:** Intel Core i5-11400F
**RAM:** Crucial Ballistix 2x8GB DDR4 3600MHz CL16
**GPU:** ASRock Radeon RX 6700 XT Challenger Pro
**OS:** Nobara Linux 36 (Thirty Six) x86_64
**Speedtest:** https://librespeed.org/results/?id=00zemgk (download 367Mbps, upload 34.7Mbps)

![image](https://user-images.githubusercontent.com/85581164/192111378-d1c5ac44-02c4-414f-8ed1-8a4aad6aaa75.png)

**Comment by DeltaJuice** [comment]
What was the fix for this, if u managed to fix it cus i have the same error as lightspeed its stuck on checking subfolders 3/3
