### ISSUE TITLE
Stuck on Starting JVM [mac] 1.8.9

### ISSUE THREAD

**Issue by oN00bs** [Solar-Tweaks/Solar-Tweaks#612]
**Describe the bug**
the launcher screen just stays on the starting jvm

**Expected behavior**

**Actual behaviour**
It just stay there for 20 mins then dissapers 

**Environment (please complete the following information):**
 - OS: Macbook Pro 
 - Launcher version 4.05

**Comment by oN00bs** [comment]
pls help

**Comment by xLunarr** [comment]
If you check v4.0.5 release changelog, it says that they have removed MacOS and Linux support.
![image](https://user-images.githubusercontent.com/83427897/193327692-a34fd3c3-cf40-499b-b2c5-3a687a16c505.png)
