### ISSUE TITLE
Solar Tweaks 1.8.9 stuck at "Patching Game..."

### ISSUE THREAD

**Issue by rickycat29** [Solar-Tweaks/Solar-Tweaks#618]
When i try launching 1.8.9 on solar it's stuck in the phase "patching game", i tried everything, but nothing's working.

_Screenshots:_

**Lastest Logs:** (https://user-images.githubusercontent.com/102383064/193335952-064d7ea5-d61e-4d62-ba40-ebc2730db237.png)
**Patcher:** (https://user-images.githubusercontent.com/102383064/193335955-7dbe80dd-a120-4b02-89d2-e1422d3fbc36.png)
**"Patching" error:** (https://user-images.githubusercontent.com/102383064/193335956-2d004973-64bb-484c-b545-357033b7265f.png)
**Solar Settings:** (https://user-images.githubusercontent.com/102383064/193335958-92144446-8531-4675-a77c-b0b1fc307244.png)

**Comment by RadNotRed** [comment]
Just attach the log files
