### ISSUE TITLE
stuck on "starting jvm" or "checking sub-folders"

### ISSUE THREAD

**Issue by TrueNightedge** [Solar-Tweaks/Solar-Tweaks#620]
when enabling the skip-checks solar tweaks is stuck on "starting jvm" and when not it's stuck on "checking sub-folders"
plz help.
![image](https://user-images.githubusercontent.com/105174287/193412578-6d072713-2062-4d2f-a596-0cf414e42ce9.png)

**Comment by RadNotRed** [comment]
If you are stuck on launching jre, launch Lunar Client Optifine, not forge, fabric, sodium, ect; then close Lunar and open Solar Tweaks and launch.
If launching 1.12+ and you get stuck, make sure you turn OFF skip checks

**Comment by TrueNightedge** [comment]
i already did that and it's not working

**Comment by RadNotRed** [comment]
https://cdn.discordapp.com/attachments/1025851503434530977/1025861086760673451/Solar_Purge.bat

then reinstall

**Comment by TrueNightedge** [comment]
alright what do i do now ?

**Comment by RadNotRed** [comment]
then just try launching lol

**Comment by TrueNightedge** [comment]
oke

**Comment by TrueNightedge** [comment]
![image](https://user-images.githubusercontent.com/105174287/193441749-0d430e95-553f-4b8e-94bd-1872b05a3aaf.png)
it's stuck on "checking sub-folders"
