### ISSUE TITLE
Mac M1 4.0.6 select jre

### ISSUE THREAD

**Issue by limy07** [Solar-Tweaks/Solar-Tweaks#625]
I am trying to launch 1.8.9 on solar tweaks with mac m1 air 2020, when trying to launch it says "the JRE you selected was not found or is invalid. Pleaase select a valid JRE in the settings page or download one using the JRE downloader. Make sure you selected the bin folder inside of the JRE." But I can't download the JRE from the settings page (jre downloader) because it is only avalible for windows. What can I do to fix this.

**Comment by oNullr** [comment]
you can try to download zulu from the official website and use it in solar tweaks
