### ISSUE TITLE
4.0.6 Solar Tweaks Stuck at "CHECKING LC ASSETS"

### ISSUE THREAD

**Issue by oNullr** [Solar-Tweaks/Solar-Tweaks#631]
**when i launch solar tweaks it will stuck at checking lc assets**

and also at the bottom there is some posts over there and the Physci's profile pic bugged out, I tried to use the old version of solar tweaks but it still didnt work
![image](https://user-images.githubusercontent.com/115331055/194683777-eb09ee56-80ab-4202-aeef-3c8a2642e6c9.png)
![image](https://user-images.githubusercontent.com/115331055/194683795-c98f8ba8-23a0-45b7-9549-296df2dc4425.png)

please fix it

**Comment by Tashlin999** [comment]
Yeah me too, i tried reinstalling both lunar and solartweaks, i tried deleting all of the assets and installing it back, but it still dont launch
![image](https://user-images.githubusercontent.com/115347075/194701130-5b81077d-9582-4e2f-a7b8-035c44ef2d7f.png)

**Comment by Tashlin999** [comment]
i figured it out guys, its pretty simple actually, u click on settings and look for this : 
![image](https://user-images.githubusercontent.com/115347075/194702141-6f84be37-9633-4d85-b855-d8b4e8610661.png)

then u enable it, and it should launch

**Comment by bornasin1311** [comment]
i did the skip checks thing but i dont get my cloaks or emotes

**Comment by oNullr** [comment]
ok let me try

**Comment by oNullr** [comment]
yo it worked thx
