### ISSUE TITLE
Sodium Support on Solar Tweaks

### ISSUE THREAD

**Issue by theghoulish76** [Solar-Tweaks/Solar-Tweaks#639]
I'm not exactly sure this is where I'm supposed to submit this but I'm doing it here anyway.

Ok, so basically, Lunar Client recently (like a month or two ago) started support for Sodium on their 1.16+ versions and it would be amazing if this was also added to Solar Tweaks because I've (and probably a lot of other users) found that Sodium manages to crank out more FPS when compared to Optifine and that's why I'd rather be using Sodium than Optifine when I'm on 1.16+. It really wouldn't matter if I had a beefy PC but when I'm on LC+OF on MCCI I get around 50fps and when I switch to Sodium on Fabric, I get around 110fps so it makes a huge difference for me.

Thanks

**Comment by RadNotRed** [comment]
v5
