### ISSUE TITLE
Sound and language

### ISSUE THREAD

**Issue by Lipinzz** [Solar-Tweaks/Solar-Tweaks#644]
**Describe the bug**

When I start Solar, my minecraft opens but I can't change the language and it has no sounds.

**To Reproduce**
1. Go to 'I open the Solar and It starts minecraft'
2. See error

**Expected behavior**
That other languages ​​appear to select, but none appear, and that when Solar starts and he opens minecraft that has normal sounds, because when I'm playing I don't hear anything.

**Actual behaviour**
Minecraft doesn't have any sounds and I can't change the language because it doesn't have languages ​​to select.

**Screenshots**
https://prnt.sc/spVsqHJKuKid

**Environment (please complete the following information):**
 - OS: Windows
 - Launcher version: 4.0.7
 - Patcher version: 1.8.9
 - Solar Stats version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by xEuranium** [comment]
Pretty sure this is an issue regarding Minecrafts handling of loading assets. This usually is fixed for me by making sure Solar is focused during the startup screen. You can also try to launch normal minecraft or lunar, and see if the issue persists.

**Comment by Lipinzz** [comment]
> Tenho certeza de que este é um problema em relação ao manuseio de ativos de carregamento do Minecraft. Isso geralmente é corrigido para mim, certificando-se de que o Solar esteja focado durante a tela de inicialização. Você também pode tentar iniciar minecraft normal ou lunar e ver se o problema persiste.

I managed to solve it, I just downloaded a program that removes the application completely and puts all its components together, leaves nothing on the computer, then I just installed it again
