### ISSUE TITLE
Stuck on "Checking LC assets" but i restarted its not stuck on there

### ISSUE THREAD

**Issue by FindMinecraftHotGirlSkin** [Solar-Tweaks/Solar-Tweaks#649]
is there a problem?

**Comment by xEuranium** [comment]
sigh. check [my latest post](https://github.com/Solar-Tweaks/Solar-Tweaks/discussions/654).

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
