### ISSUE TITLE
SOLAR TWEAKS IS STILL NOT LUANCHING ON MAC

### ISSUE THREAD

**Issue by 4nson** [Solar-Tweaks/Solar-Tweaks#652]
1. 1.8.9 will not launch with checks on (stuck on checking lc asests) and off (stuck on laucnhing jvm)
2. other versions like 1.7 launch but crashes right after
I have used all of the jre presets and manual installed them as well but yet to fix it. 
If you can make a purge tutorial or file for mac

version is 4.07 LATEST

**Comment by 4nson** [comment]
> sigh. check [my latest post](https://github.com/Solar-Tweaks/Solar-Tweaks/discussions/654).

I have tried basically everything on that disucssion and I have gotten nowhere, I have just only reached starting JVM while having skipped checks off but it still hasn't launched

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
