### ISSUE TITLE
Doesn't work on mac still. If you need it here's a video of whats happening

### ISSUE THREAD

**Issue by Keybaoord** [Solar-Tweaks/Solar-Tweaks#657]
The bug is happening when I launch it, here's a video showing precisely whats going down.
https://www.youtube.com/watch?v=i4Z1ioi-8-U&ab_channel=Combo%27s

**Comment by banhmikepxucxich** [comment]
im a mac user, and its working istg, uncheck skip checks before launching and see how it launches.

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
