### ISSUE TITLE
For some reason my Patcher settings arent saving

### ISSUE THREAD

**Issue by tenistia** [Solar-Tweaks/Solar-Tweaks#658]
**Describe the bug**
My patcher settings save in the launcher but dont ingame

**To Reproduce**
1. Go to solar tweaks launcher
2. Change the patcher settings
3. Start minecraft
4. None of settings saved

**Expected behavior**
It would save my patcher settings

**Actual behaviour**
Not saving

**Screenshots**
Idk if you need

**Environment (please complete the following information):**
 - OS: Windows 10
 - Launcher version: 4.0.7
 - Patcher version: Blank
 - Solar Stats version: I don't know what this is

**Additional context**
no

**Comment by tenistia** [comment]
Yes I've tried it. but when i launch it i dont have the cosmetics. and when
relaunching the launcher. the settings was reverted to default

**Comment by HypedDomi** [comment]
@tenistia Is this still relevant? If yes can you try updating (launcher and client)

**Comment by HypedDomi** [comment]
Closed due to inactivity
