### ISSUE TITLE
CRASH-c0214f93-947b-4b61-964f-5863b7153ecd

### ISSUE THREAD

**Issue by g1ar3** [Solar-Tweaks/Solar-Tweaks#661]
**Describe the bug**

**To Reproduce**
1. Launch Solar Tweaks

**Expected behavior**
It will launch solar tweaks.

**Actual behaviour**
Crashes (CRASH-c0214f93-947b-4b61-964f-5863b7153ecd)

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Launcher version 4.0.7
 - Patcher version 
 - Solar Stats version 

**
Additional context**

Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)
[1.8.9-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/9847577/1.8.9-latest.log)

**Comment by LeoNotClean** [comment]
You should update, also I recommend asking in #community-support in discord.gg/solarsocket

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
