### ISSUE TITLE
Error message before starting to launch

### ISSUE THREAD

**Issue by Random-user-lol** [Solar-Tweaks/Solar-Tweaks#662]
Whenever I try to launch it gives me this error message.
![Screenshot 2022-10-24 at 1 20 13 PM](https://user-images.githubusercontent.com/116539549/197453965-74196d3f-9b1d-4fb4-9f65-35239c34fe94.png)

It is telling me to open a folder in .Lunar client with the file "installation id"
So I opened the folder and there was no "installation id" file there
![Screenshot 2022-10-24 at 1 26 03 PM](https://user-images.githubusercontent.com/116539549/197454121-f5112d58-a854-4d89-bf35-0c376b8f116c.png)

Do I need to install this file?
And if so where can I find it

**Comment by Naibuu** [comment]
I might be wrong, but I think you might be required to re-install Lunar Client to regenerate that file.

**Comment by TBHGodPro** [comment]
You need to reinstall lunar, launch it on 1.8.9 optifine, and then it should work

**Comment by Random-user-lol** [comment]
Thanks!
I re-installed lunar then launched it and it worked :)
