### ISSUE TITLE
I get a SolarPatcher Error When i Launch Solar Tweaks

### ISSUE THREAD

**Issue by ZennyClient** [Solar-Tweaks/Solar-Tweaks#663]
When i Try Launch Every thing works but then this error pops up 
![image](https://user-images.githubusercontent.com/116591599/197598859-bd1e850d-1fd9-4f0d-8d77-b3f36273b1cd.png)

I've tried : Reinstalling solartweaks + launching lunar and closing it

I also tried deleting config.json as a youtube video showed but that didnt work.

**Comment by TBHGodPro** [comment]
Delete the config.json and turn off skip checks, also make sure you are on v4.0.8 (it will say what v version you are on at the bottom left of Solar Tweaks)

**Comment by ZennyClient** [comment]
Thank you :) It worked
