### ISSUE TITLE
diffrent patcher error

### ISSUE THREAD

**Issue by itaytheplay** [Solar-Tweaks/Solar-Tweaks#670]
![image](https://user-images.githubusercontent.com/116816405/198297110-9ba52574-a684-45e2-8e3b-9d3a4ba548e8.png)

**Comment by itaytheplay** [comment]
plz help

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
