### ISSUE TITLE
solarpatcher error

### ISSUE THREAD

**Issue by cecatjustanoob** [Solar-Tweaks/Solar-Tweaks#672]
when i launch solar it says: config appears to be invalid - please fix configuration issues (e.g. numeric values) or delete your config to fallback to default

I have deleted config.json and enabled skip checks but it keeps showing: config appears to be invalid - please fix configuration issues (e.g. numeric values) or delete your config to fallback to default
can some1 help me?

**Environment **
 - OS: [Windows]
 - Launcher version [4.0.8]
 - Patcher version [1.7.2 - PR] 
 - Solar Stats version (if applicable)

**Additional context**
none

**Comment by TBHGodPro** [comment]
Delete the `config.json` and disable skip checks

**Comment by Bluers** [comment]
i tried doing that and instead of not launching it launched without the patcher which ig is a improvment

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
