### ISSUE TITLE
Badlion Tweaks

### ISSUE THREAD

**Issue by zKoalh** [Solar-Tweaks/Solar-Tweaks#678]
make badlion tweaks please

**Comment by TBHGodPro** [comment]
no

**Comment by HappyKitek** [comment]
they will not make badlion tweaks cause its too hard and basicly impossible

**Comment by TBHGodPro** [comment]
Also we are based on Lunar Client only, not Badlion

**Comment by heyitscam** [comment]
![6369-unfortunate-loss](https://user-images.githubusercontent.com/111710350/200459982-3f51bda0-45dd-4f37-92c7-f90b2639ae54.png)
