### ISSUE TITLE
Solar tweaks problem on mac

### ISSUE THREAD

**Issue by Qsian** [Solar-Tweaks/Solar-Tweaks#683]
**Describe the bug**
I launched solar tweaks and it does open the game. it just crashes right after. there is no crash report or anything.

**Expected behavior**
Its expected to launch and playable

**Actual behaviour**
Closes right after.

**Environment (please complete the following information):**
 - OS: Mac
 - Launcher version: 4.0.8
 - Patcher version 
 - Solar Stats version (if applicable)

**Comment by civickz** [comment]
This happens to me as well

**Comment by heyitscam** [comment]
Use new version. Found via releases.

**Comment by Qsian** [comment]
I have tried the new version as well. It has the same problem.

**Comment by Qsian** [comment]
Yes thank you it works now.
