### ISSUE TITLE
Solar Tweaks Launches in a new directory.

### ISSUE THREAD

**Issue by banhmikepxucxich** [Solar-Tweaks/Solar-Tweaks#688]
this bug happened on macos and idek how
the directory its supposed to launch in is the default mc dir, but launches in library/application instead
god i wanna use no hurt cam

**Comment by TBHGodPro** [comment]
In settings tab, at Launch Directories, click Reset to Default

**Comment by TBHGodPro** [comment]
Also, it might say /library/application, but it is most likely getting cut off from showing the whole thing, if Reset to Default doesn't do anything, then it _is_ in the correct mc directory

**Comment by banhmikepxucxich** [comment]
> In settings tab, at Launch Directories, click Reset to Default

i thought it was default alr :skull:
eitherway it didnt work, it isnt the correct mc directory, i checked the dir alr, and launch directory is /users/urusername/library/application support/minecraft, and i think this is some kind of human bug

**Comment by banhmikepxucxich** [comment]
i had double checked the launch directory setting and it is set correctly to my default launch directory in lunar.

**Comment by banhmikepxucxich** [comment]
No idea, im probably dumbb because i launched in debug mode for a while ago, because of hte checking lc assets bug, and forgot to turn it off.

**Comment by banhmikepxucxich** [comment]
yes it worked after i unchecked launch in debug mode, tyy
