### ISSUE TITLE
Checking LC Assests

### ISSUE THREAD

**Issue by PipeDown88** [Solar-Tweaks/Solar-Tweaks#690]
Stuck on checking LC assests, ive tried all of the fixes listed here, https://github.com/Solar-Tweaks/Solar-Tweaks/wiki/Prerequisites and here https://github.com/Solar-Tweaks/Solar-Tweaks/discussions/654 but still with no fixes, I am unsure of what to do. 
![image](https://user-images.githubusercontent.com/118043813/201463150-88c50a0a-9b65-4806-b336-f41d922e07b6.png)
![image](https://user-images.githubusercontent.com/118043813/201463161-c00f979f-0ca8-48ea-8ffe-220a28f677f7.png)
 how can I go about fixing this?

**Comment by banhmikepxucxich** [comment]
you could skip checks but ill prob crash

**Comment by PipeDown88** [comment]
> you could skip checks but ill prob crash

yeah I tried that it just fails launch

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
