### ISSUE TITLE
Random FPS Drops for about 2-4 seconds every couple minutes

### ISSUE THREAD

**Issue by Hijxcked** [Solar-Tweaks/Solar-Tweaks#691]
Whenever I play on solar tweaks I go from running  800 fps then randomly drop to 0 for about 2-4 seconds, other people are experiencing the same problem 

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher version [eg. 4.0.1]
 - Patcher version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by Sloppynuts23** [comment]
what

**Comment by Sloppynuts23** [comment]
my frame keeps dropping no matter what i try to do

**Comment by Sloppynuts23** [comment]
i adjusted my settings and even tried turning off some of the lunar client settings

**Comment by 0h999** [comment]
happens to me extremely annoying

**Comment by SoraiSaki** [comment]
Created a comment just to respond to this, happens to me as well. I found that changing the overall quality of the game delays the freezing, but does not prevent it fully.
Its really annoying considering I pvp quite a bit, and I must say that its made me switch back to regular lunarclient.

I never did not have this issue, straight away when I downloaded it I was experiencing freezing
*on IMac (M1)

**Comment by Sloppynuts23** [comment]
yea me too im using mac m1

**Comment by SoraiSaki** [comment]
I dunno any other fixes, but ill keep using Solar every now and then untill I manage to find a fix.

**Comment by Sloppynuts23** [comment]
what is ur launcher version? im using 4.10 or something

**Comment by SoraiSaki** [comment]
I’m using latest but using older versions still cause the freezing

**Comment by Naibuu** [comment]
Using the latest build might fix your problems. As Solar Engine is replacing the good old Solar Patcher.

**Comment by SoraiSaki** [comment]
Ok, Ill try it later and post what happens. Thankyou :D

**Comment by UnaPepsi** [comment]
has happened to me, fixed by changing the jvm arguments
https://i.imgur.com/0Zsyinx.png
-XX:+DisableAttachMechanism

**Comment by SoraiSaki** [comment]
wait fr???? btw i tried the new update of solar tweaks and it was freezing more so ill try this rn and see if it fixes it!! thank you so much for this :D

**Comment by SoraiSaki** [comment]
> has happened to me, fixed by changing the jvm arguments https://i.imgur.com/0Zsyinx.png -XX:+DisableAttachMechanism

HOLY CRAP IT DOESNT FREEZE ANYMORE

**Comment by SoraiSaki** [comment]
THANKYOU
SMMMM

**Comment by Sloppynuts23** [comment]
am i suppose to delete all the arguments and replace it with -XX:+DisableAttachMechanism

**Comment by Sloppynuts23** [comment]
it clearly works but there is still a bit freeze 
anyways ty
