### ISSUE TITLE
Valid Config Error

### ISSUE THREAD

**Issue by FuushiBirbo** [Solar-Tweaks/Solar-Tweaks#693]
![image](https://user-images.githubusercontent.com/118225039/201778005-e58fdb41-0134-40e3-8049-4956525606c4.png)

Hello, Anyone knows how can i fix this issue. I searched over Youtube to but i cant find any solution.

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
