### ISSUE TITLE
Patches are not applying.

### ISSUE THREAD

**Issue by Sarreos** [Solar-Tweaks/Solar-Tweaks#7]
After selecting the features in the Patcher tab and launching the game, the patches are not applied.

**Comment by Sarreos** [comment]
I found the source of the problem. Solar Tweaks is not generating a config file for the Solar Patcher.

**Comment by Sarreos** [comment]
solar-patcher.jar is also not generated.

**Comment by Zone-Infinity** [comment]
> solar-patcher.jar is also not generated.

It is generated in my pc 
![image](https://user-images.githubusercontent.com/68643247/165345390-b9947eba-67ed-4fc5-b2c8-797b7b7d13d1.png)

**Comment by Zone-Infinity** [comment]
windows

**Comment by 770grappenmaker** [comment]
What files are in your ~/.lunarclient/solartweaks directory?

**Comment by Sarreos** [comment]
> What files are in your ~/.lunarclient/solartweaks directory?

Just logs folder

**Comment by 770grappenmaker** [comment]
Then something is going entirely wrong. Could you see if theres anything in devtools?

**Comment by Sarreos** [comment]
> Then something is going entirely wrong. Could you see if theres anything in devtools?

I don't really know how. If you could guide me how to do it I will check.

**Comment by dtomvan** [comment]
Ctrl-Shift-I

**Comment by dtomvan** [comment]
> > > What is your OS?
> > 
> > 
> > Windows
> 
> Well on Linux it's not working right now.

I think you need to specify the correct JRE, since the default is currently incorrect. That worked for me

**Comment by Sarreos** [comment]
> Then something is going entirely wrong. Could you see if theres anything in devtools?

Nothing except that it cannot read the config.json directory.

**Comment by Sarreos** [comment]
It seems like this part of code
``export async function checkPatcher() {
  logger.info('Checking patcher...');

  store.commit('setLaunchingState', {
    title: 'LAUNCHING...',
    message: 'CHECKING PATCHER...',
    icon: 'fa-solid fa-file',
  });

  const release = await axios
    .get(`${constants.API_URL}${constants.UPDATERS.INDEX}`)
    .catch((reason) => {
      logger.error('Failed to fetch updater index', reason);
    });

  const patcherPath = join(
    constants.DOTLUNARCLIENT,
    'solartweaks',
    'solar-patcher.jar'
  );``
Is not executed and it just skips to reading the config.

**Comment by Sarreos** [comment]
It seems like it was a one time problem. I deleted all the Solar Tweaks files and relaunched my game and both the solar-patcher.jar and config.json were downloaded.

**Comment by DeltaJuice** [comment]
![image](https://user-images.githubusercontent.com/89205116/165457452-6be462c7-f983-48f3-97c9-b06288af4446.png)
for me the files generated but it didnt update patcher in game|
For example 
![image](https://user-images.githubusercontent.com/89205116/165457615-b83f9725-1b6a-46b6-8ccb-f3340dfeb9cf.png)
here fps is changed to cps and its enabled but in game its still normal
![image](https://user-images.githubusercontent.com/89205116/165457781-1a07e1c8-9459-4300-8127-d45c5d8b985b.png)
few more tweaks haven't patched in game even though they are selected
