### ISSUE TITLE
I cant get a JRE for mac

### ISSUE THREAD

**Issue by JCrobotss1234** [Solar-Tweaks/Solar-Tweaks#701]
When I start it I get an error For JRE 
![Screenshot 2022-11-26 at 10 17 47 AM](https://user-images.githubusercontent.com/105172772/204096053-2f824144-0e51-498e-82ef-ebf2f3cb2a63.png)

**Comment by TBHGodPro** [comment]
Go to settings tab and click reset

**Comment by SE3-Dev** [comment]
![image](https://user-images.githubusercontent.com/118614815/205458550-251a0c44-fe16-44e1-8606-7be79702670f.png)

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
