### ISSUE TITLE
Solar Tweaks 4.2.0

### ISSUE THREAD

**Issue by oNullr** [Solar-Tweaks/Solar-Tweaks#709]
After I launch the Solar Tweaks 4.2.0 it'll say the client crashed and it just crashed

**Comment by TBHGodPro** [comment]
go to your settings in solar tweaks, scroll down, and click reset (the big blue button)

**Comment by HypedDomi** [comment]
To unclutter issues, we will close this issue. Please use
- https://github.com/Solar-Tweaks/Solar-Tweaks/issues/808
for more infos about the problem
