### ISSUE TITLE
Where did the "Patcher" tab go in 4.2.0?

### ISSUE THREAD

**Issue by Defflix** [Solar-Tweaks/Solar-Tweaks#712]
I first installed SolarTweaks 4.1.0, and version 4.2.0 was pushed out recently. When I updated, the "Patcher" tab was gone and replaced by an "Engine" tab with way fewer options. What happened to the Patcher tab, and where can I find the Patcher settings (in the launcher, not settings.json)?

**Comment by itayvalani** [comment]
its now in engine

**Comment by SE3-Dev** [comment]
It is renamed as "Engine"
![image](https://user-images.githubusercontent.com/118614815/205458266-edadb5cb-6b07-4f7d-a182-abf078052538.png)

**Comment by SE3-Dev** [comment]
Some of the options have been grouped into popup menus:
![image](https://user-images.githubusercontent.com/118614815/205458344-c619fd04-a0f2-4799-bb40-63e48ea77900.png)

**Comment by SE3-Dev** [comment]
But hit delay has been removed

**Comment by qualk** [comment]
@Defflix close the issue as it has been resolved.
