### ISSUE TITLE
There is no more "Patcher" and also i don't have the hitdelayfix in 1.8 anymore 

### ISSUE THREAD

**Issue by Dexyo-o** [Solar-Tweaks/Solar-Tweaks#715]
They have change the patcher to engine and many mod are left like the hitdelayfix why ? That was the reason why i was using Lunar Tweaks

**Comment by B4mb0u** [comment]
yes idk why they removed hitselect fix, it was so useful

**Comment by B4mb0u** [comment]
it doesn't even works anymore in the old version of solar engine

**Comment by skywlker420** [comment]
Anyone knows a st version that still works no hit delay? They completely screwed up removing no hit delay, im pretty sure that 90% of their users were using st bc of no hit delay option in 1.8

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
