### ISSUE TITLE
Disable built in discord rich present from Lunar

### ISSUE THREAD

**Issue by Boryte** [Solar-Tweaks/Solar-Tweaks#716]
**Is your feature request related to a problem? Please describe.**
Default Lunar client rich presence that you can't turn off.

**Describe the solution you'd like**
So ability to disable the rich presence of lunar completely

**Describe alternatives you've considered**
None

**Additional context**

**Comment by HypedDomi** [comment]
Added in the Patcher. Update to the latest launcher version then go to Engine and disable Discord Rich Presence
