### ISSUE TITLE
Solar Tweaks Launcher not applying tweaks.

### ISSUE THREAD

**Issue by hehe098** [Solar-Tweaks/Solar-Tweaks#719]
When using Solar Tweaks Launcher none of the tweaks i enable apply after launching.
I have tried using Solar Engine paired with LunarClientQT and all the tweaks work.

**To Reproduce**
1. Launch Solar Tweaks
2. Engine
3. Enable preferred tweaks
4. Launch 1.7.10

 - OS: Windows 10 22H2
 - Launcher Version: 4.2.0
 - Engine Version: 2.0.2

**Comment by HypedDomi** [comment]
Try the steps from our faq on discord. if they dont help create a ticket on our discord server
