### ISSUE TITLE
UPDATE CRASHES SOLAR AS SOON AS IT LAUNCHES

### ISSUE THREAD

**Issue by Murkshot** [Solar-Tweaks/Solar-Tweaks#721]
I installed the update first it said there was an issue with the patcher, so I updated the regular lunar client, and then Solar launched but immediately crashes, what can I do? Should I uninstall both solar and regular lunar and then re-install them again?

**Comment by 0PandaDEV** [comment]
i have the same problem

**Comment by qualk** [comment]
#709 https://github.com/Solar-Tweaks/Solar-Tweaks/issues/709#issuecomment-1333708469
> go to your settings in solar tweaks, scroll down, and click reset (the big blue button)
Please try the above solution.

**Comment by 0PandaDEV** [comment]
It's good already I fixed it myself just switch the JRE

**Comment by qualk** [comment]
> It's good already I fixed it myself just switch the JRE

Nice. Please close the issue then :)
