### ISSUE TITLE
Hit delay fix removed on update 4.2.0

### ISSUE THREAD

**Issue by teanea** [Solar-Tweaks/Solar-Tweaks#722]
I cannot find the mod anywhere, unless it is already applied by default when you check the Removed mod bans in the Metadata option. I tried to use 4.1.0 but its not working and I dont feel the smooth hit reg anymore, someone let us know.

**Comment by teanea** [comment]
Ok I found out if you use version 4.8.0 you can enable the option and solar tweaks does launch :)

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
