### ISSUE TITLE
Lag spike for 2-3 seconds every 2-3 mins

### ISSUE THREAD

**Issue by SE3-Dev** [Solar-Tweaks/Solar-Tweaks#723]
This was present in 4.10-4.2.0 MacOS, it can get very annoying in PvP or general fast paced gameplay. By the way I love solar tweaks, keep up the good work.

**Comment by UnaPepsi** [comment]
has happened to me, fixed by changing the jvm arguments
https://i.imgur.com/0Zsyinx.png
-XX:+DisableAttachMechanism

**Comment by SE3-Dev** [comment]
I will try that Thank u

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
