### ISSUE TITLE
Sudden high ping

### ISSUE THREAD

**Issue by LocChsNgu** [Solar-Tweaks/Solar-Tweaks#724]
So I played asian minemen everyday. My daily ping is 40-44ms. But when i install solar tweaks and run it, the ping goes up to 185ms by no reason. And only that server get ping spikes, no other server get the same situation like that

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
