### ISSUE TITLE
remove hit delay 1.8.9

### ISSUE THREAD

**Issue by auhustgammel** [Solar-Tweaks/Solar-Tweaks#725]
yo i used to use solar tweaks to remove the hitdelay in the 1.8 version of lunarclient. at some point solar tweaks didn't work anymore and the following release was not for mac. today i wanted to reinstall it bc there were new versions for mac too, but the key feature why i used this program is missing: the remove hitdelay feature. yeah it'd be nice if it could be readded but i will understand if this wont be possible due to solarpatcher failures or changes so yeah.

**Comment by Diamondy01** [comment]
Hello, I have also noticed this in the new release, and I came here to see if someone had made an open issue about this. I am definetly BUMP this

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
