### ISSUE TITLE
1.19.2 Won't load

### ISSUE THREAD

**Issue by drenchedbanana** [Solar-Tweaks/Solar-Tweaks#727]
In the 4.2.0 update, When i go to play 1.19.2 with solar tweaks the ''Mojang Studios'' loading screen, the progressbar goes almost full but suddently goes back to 0 and then it repeats.

**Comment by alecpezzuti** [comment]
Same, I tried the fixes for every launcher and client issue combined and reinstalled once, still nothing.

**Comment by alecpezzuti** [comment]
It will on 4.1.0 still.

**Comment by HypedDomi** [comment]
To unclutter issues, we will close this issue. Please use
- https://github.com/Solar-Tweaks/Solar-Tweaks/issues/808
for more infos about the problem
