### ISSUE TITLE
JVM not launching after all the checks

### ISSUE THREAD

**Issue by Genuineship** [Solar-Tweaks/Solar-Tweaks#729]
When I click "Launch 1.8.9" it does all the usual stuff like starting and launching jvm, but when it goes back to "Launch 1.8.9", nothing happens

**To Reproduce**
1. Go to Solar Tweaks Launcher
2. Click on 'Launch 1.8.9'
4. See "Launch 1.8.9" after everything is complete.

Im using MacOS, if that helps with the troubleshooting
<img width="1296" alt="Screenshot 2022-12-10 at 12 29 09 pm" src="https://user-images.githubusercontent.com/120230210/206821978-6483b0dc-d71a-4557-8bc7-63ff937ee2b0.png">

This is the image of solar tweaks launcher after i clicked launch, and after it says "Starting JVM"

**Comment by Genuineship** [comment]
UPDATE: ok yea im stupid so i forgot to reinstall the JRE, but now everytime Java opens, it crashes. Is there something i missed while configuring?

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
