### ISSUE TITLE
Checking LC assets

### ISSUE THREAD

**Issue by GamingIQ1** [Solar-Tweaks/Solar-Tweaks#731]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'solar tweaks'
2. Click on 'launch 1.8.9'

**Expected behavior**

**Actual behaviour**
I click launch and it says checking lc assets

**Screenshots**

**Environment (please complete the following information):**
 - OS: Macos [e.g. Windows]
 - Launcher Version [eg. 4.2]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by GamingIQ1** [comment]
also dont give me that thing that like fixes it it doesn't work

**Comment by TBHGodPro** [comment]
Can you describe it better?

**Comment by GamingIQ1** [comment]
i try launching and it says checking lc assets no matter what please help!

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
