### ISSUE TITLE
When I Go to Play 1.8 It just never launches

### ISSUE THREAD

**Issue by HackIsABozo** [Solar-Tweaks/Solar-Tweaks#734]
So i play 1.8 like launch and it never starts up

1. Go to 1.8 
2. Click on Play green this
3. And it just never luanches

Normally it would launch like normal

**Actual behaviour**
Description of what is actually happening.

 - WIndows
 - Launcher Version 4.20
 - 
 - Solar Stats Version 4.20

**Comment by HackIsABozo** [comment]
So when i go on solar tweaks and play 1.8 it just doesnt launch for some reason how do i fix please tell me

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
