### ISSUE TITLE
1.19.2 cracked account dont open

### ISSUE THREAD

**Issue by Ehjejr** [Solar-Tweaks/Solar-Tweaks#735]
if i open minecraft 1.19.2 the loading bar go to the max and suddently next get back to the start. i leave mc like this for like 30 minute and it still do like this pls help me

 - OS: Windows 10
 - Launcher Version 4.2.0.0

i jut wanna play vanilla whit lunar

**Comment by HypedDomi** [comment]
To unclutter issues, we will close this issue. Please use
- https://github.com/Solar-Tweaks/Solar-Tweaks/issues/808
for more infos about the problem
