### ISSUE TITLE
1.19(.0) missing from version select

### ISSUE THREAD

**Issue by IronBlaze101** [Solar-Tweaks/Solar-Tweaks#736]
**Describe the bug**
In the default Lunar client launcher when selecting 1.19.2 it allows you to use 1.19 instead (which i and i assume a ton of people prefer due to chat reporting not being implemented)

**To Reproduce**
just go to the version select and click on 1.19.2

**Expected behavior**
when the 1.19.2 menu is opened it shows a button to change to 1.19 instead of 1.19.2

**Actual behaviour**
the button is missing

**Screenshots**
https://i.imgur.com/aX1R0UX.png

**Environment (please complete the following information):**
 - OS: Windows 10 21H2
 - Launcher Version 4.2.0

**Comment by HypedDomi** [comment]
We dont support 1.19 atm
