### ISSUE TITLE
[Enhancement] Ability to use own mods/patches

### ISSUE THREAD

**Issue by Blazejou** [Solar-Tweaks/Solar-Tweaks#737]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to add my own mods, I have a few mods that I would want but well, I dont know how even if u can

**Describe alternatives you've considered**
none

**Additional context**
nothing , if a feature like this already exists, please tell me.

**Comment by Mispaged** [comment]
thats not possible
