### ISSUE TITLE
Client Always Crashes No matter what i do

### ISSUE THREAD

**Issue by Sushigamer6666** [Solar-Tweaks/Solar-Tweaks#741]
It just keeps saying that my client has crashed idk what to do
error code is CRASH-923a2386-f70a-4c90-ab7d-20b050b9d295

**Comment by HypedDomi** [comment]
To unclutter issues, we will close this issue. Please use
- https://github.com/Solar-Tweaks/Solar-Tweaks/issues/808
for more infos about the problem
