### ISSUE TITLE
Patch GameError

### ISSUE THREAD

**Issue by SomeGuyOnMC** [Solar-Tweaks/Solar-Tweaks#742]
It doesn't let me open the game because it shows "Cannot set property 'removeCalls' or undefined
im on solartweaks version 4.10

![Screenshot (158)](https://user-images.githubusercontent.com/120882889/208281734-354638a2-15ac-4b80-b165-ddf7e3b7d189.png)

**Comment by HypedDomi** [comment]
Update your Launcher to 4.2.0
