### ISSUE TITLE
stuck on solar tweaks logo

### ISSUE THREAD

**Issue by githubpub900** [Solar-Tweaks/Solar-Tweaks#745]
When I start Solar Tweaks, It freezes on the logo no matter how long I wait.

Idk if u can reproduce this lol, its problay computer depedant

I thought solar tweaks was gonna work normal.

But instead, it just freezes on the logo, Lunar Client works fine for me though.

Here is a screenshot:
![issue](https://user-images.githubusercontent.com/73917771/208314482-59bb06ff-be71-4d54-b52f-c21e46bf6e28.PNG)

 - OS: Windows
 - Launcher Version: 4.20
 - Engine Version: IDK
 - Solar Stats Version (if applicable): sry cant check

**Comment by Enochisgood** [comment]
Try deleting every File of solar tweaks on your computer , including solar tweaks its self , then re-install everything again if it doesn't work welp......

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
