### ISSUE TITLE
Can't start Minecraft.

### ISSUE THREAD

**Issue by Teepea** [Solar-Tweaks/Solar-Tweaks#748]
Now, I may just be being stupid here, but why when I try to launch solar tweaks, does it always say: 'CANNOT SET PROPERTY OF "remove calls" of undefined. Please help I just wanna play. XD

**Comment by hellofruks** [comment]
it happens for me in 4.10 when i update to 4.2.0 than its not happening anymore

**Comment by Baba1408** [comment]
I have the same thing, but I don't feel like updating :(

**Comment by HypedDomi** [comment]
We're not that active in GitHub. You get quicker support in our discord.

To your issue:
- Does the issue still occur?
- Try updating to the latest version (launcher and client)
- If yes, can you please send us your logs?

**Comment by HypedDomi** [comment]
Closed due to inactivity
