### ISSUE TITLE
I do not see any option or mods when i click the engine tab

### ISSUE THREAD

**Issue by onions22** [Solar-Tweaks/Solar-Tweaks#751]
Ok, so in youtube tutorials it says download and apply 'Temurin' then click on engine in order to recieve the option to put in websocket and other mods, however when i do the same, nothing is shown in the engine tab, no options to enable or disable,no mods no option to put in the websocket, nothing.Just blank. ive even tried to redownload about 10 times, downloaded zulu and applied it and yet nothing happens, its just empty.I think this is a issue for only a few people and ive seen 1 more person complaining about this in a youtube comment.I am using Windows 11 operating system.

**To Reproduce**
1. Go to settings, download Temurin and apply
2. Click on engine
3. Scroll down to nothing, i see no option
4. See error: there is nothing to see, and that is the error

**Expected behavior**
Options and mods to enable and disable, an option to put in websocket

**Actual behaviour**
i see nothing, no option to enable/disable nothing, its empty

**Screenshots**
When apply temurin:
<img width="943" alt="image" src="https://user-images.githubusercontent.com/121114483/208704056-e58d4b67-8e1d-45f1-9555-a85c3cb1a3fc.png"
Engine when temurin:
<img width="956" alt="image" src="https://user-images.githubusercontent.com/121114483/208704171-68550879-c377-4a9b-9d10-66246958209a.png">
When apply Zulu:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/121114483/208704285-a356c4b3-2a89-43b4-8659-62d8497566bc.png">
Engine when Zulu:
<img width="958" alt="image" src="https://user-images.githubusercontent.com/121114483/208704341-1300d0df-8dd2-4abe-bc70-fe8f4cf57bb6.png">

**Environment (please complete the following information):**
 - OS: Windows 11
 - Launcher Version 4.2.0
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Any other info required, please tell, i have quite a busy schedule with big exams coming up so might take me a day to respond

**Comment by WhyNoNames** [comment]
same problem but i use temurin
because my zulu wont install(download button wont do anything)

**Comment by HypedDomi** [comment]
Use a VPN. If the error still occurs, open a ticket on our Discord server
