### ISSUE TITLE
Solar Tweaks Engine is Blank.

### ISSUE THREAD

**Issue by ShriHariPolytex** [Solar-Tweaks/Solar-Tweaks#754]
**Describe the bug**

**To Reproduce**
1. Go to Solar tweaks
2. Click on 'Engine'
3. See error

I have do all the things search iin youtube how to solve it but no videos i reinstall 5 times Apply zulu off virus and threat protection but it did not solve Pleasee help!!

**Comment by WhyNoNames** [comment]
same bro

**Comment by Lestica** [comment]
samee pls help someone

**Comment by HypedDomi** [comment]
Use a VPN. If the error still occurs create a ticket in our discord Server
