### ISSUE TITLE
Get .jar format for client And Allow Other Launcher

### ISSUE THREAD

**Issue by Pekly** [Solar-Tweaks/Solar-Tweaks#755]
Why .jar For Client
Because Of Allow Other Launchers To Use This Client
Expect @PojavlauncherTeam(So Many Players Play On Pojavlauncher This needed Much, @MultiMC
This Feature Really Needed
Thank Solar Tweaks

**Comment by Mispaged** [comment]
thats not possible

**Comment by dolphin-cat** [comment]
it is possible, someone already did it
