### ISSUE TITLE
Solar Tweaks engine not working

### ISSUE THREAD

**Issue by PranavPochamcherla** [Solar-Tweaks/Solar-Tweaks#758]
**Overview**
So basically I havent used solar tweaks for bout a week or so and when i returned to it, the engine stopped working. I searched the web, yt and everywhere possible but I got no clue as to how to fix this issue. I have even tried installing dif. settings and so on but it is still not working.  I have even tried uninstalling and reinstalling it for like a billion times and it still doesnt work. I have even restarted my own computer but it changed nothing.

**To Reproduce**
1. Uninstall Solar Tweaks
2.  Uninstall all remains of it
3. Reinstall it
4. U will see the result

**Expected behavior**
Showing all mods we can apply for example 'websocket', 'cracked accounts' and so on.

**Actual behaviour**
A dark blank screen without a single mod.

**Screenshots**
![image](https://user-images.githubusercontent.com/106970988/209522873-962cc8ec-2373-4b74-9187-480b605348f4.png)
![image](https://user-images.githubusercontent.com/106970988/209522996-42f99029-29a9-40e4-b925-6bff1d4a4df5.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**pl help me.**

**Comment by WhyNoNames** [comment]
OS: Windows
Launcher Version: 4.2.0(latest)
Engine Version: idk lmao
Solar Stats Version : and how do i find that?

**Comment by PranavPochamcherla** [comment]
Hey guys, its working now chillax

**Comment by PranavPochamcherla** [comment]
> OS: Windows Launcher Version: 4.2.0(latest) Engine Version: idk lmao Solar Stats Version : and how do i find that? edit:same problem btw

its working for me now

**Comment by WhyNoNames** [comment]
how did u get it bro pls tell

**Comment by PranavPochamcherla** [comment]
> how did u get it bro pls tell

Man i swear idk. I posted this last night and I went to slep. Today morning it worked again. Idek what i did

**Comment by Lestica** [comment]
brooo it still doesnt work wtf did you do???

**Comment by BURGER64** [comment]
i installed solar tweaks like last year or something and the engine tab didnt work so i left it just lying on my pc, so today i was like frick it imma retry and then i remembered this issue and i checked and the engine tab is still not working
please help.

**Comment by TapeLovesOreos** [comment]
same issue
