### ISSUE TITLE
Engine

### ISSUE THREAD

**Issue by WhyNoNames** [Solar-Tweaks/Solar-Tweaks#759]
When i go to the engines section it isnt loading anything and i cant add websocket or use my cracked account because of this
![image](https://user-images.githubusercontent.com/121428695/209534676-5d9992d4-5960-42e3-809b-fd64072b9448.png)

**Comment by WhyNoNames** [comment]
i found another guy who posted the same thing lol

**Comment by BURGER64** [comment]
i installed solar tweaks like last year or something and the engine tab didnt work so i left it just lying on my pc, so today i was like frick it imma retry and then i remembered this issue and i checked and the engine tab is still not working
please help.
