### ISSUE TITLE
1.19.2 Crash

### ISSUE THREAD

**Issue by Enochisgood** [Solar-Tweaks/Solar-Tweaks#760]
1.19.2 crashes on my pc whenever I open it , it shows the mojang studios loading screan but immediateely says "saving world" after  then crashes immediately

**Comment by Enochisgood** [comment]
But if this hasn't happend to anyone I guess my PC is just potato xD .  Anyway if you have any solutions please comment down below what you think will help

**Comment by emz-cool** [comment]
I had an similar issue when loading 1.19.2 but it didn’t say saving world it just closed

**Comment by Enochisgood** [comment]
Is it still crashing @emz-cool  ?
if not please tell me how you stoped it.

**Comment by theghoulish76** [comment]
If you look at past bug reports by other users, devs have said that it's a bug for 1.16+ and that it will be fixed in the next update. And it also happens to me. It gets stuck on the MOJANG loading screen and doesn't load.

**Comment by theghoulish76** [comment]
Huh. I tried to look back and find those bug reports to send a screenshot but I can't seem to find them.

**Comment by MoTastisch** [comment]
+1 Happens to me also

**Comment by ShadowPiercer** [comment]
+1 also happend to me

**Comment by Enochisgood** [comment]
Ty for the information

**Comment by emz-cool** [comment]
so long time till patch? how often do they update

**Comment by WholeLight** [comment]
**+1** Always happens to me

**Comment by LegendaryITA** [comment]
1.16+ versions don't work

**Comment by HypedDomi** [comment]
To unclutter issues, we will close this issue. Please use
- https://github.com/Solar-Tweaks/Solar-Tweaks/issues/808
for more infos about the problem
