### ISSUE TITLE
Minecraft Infinite Loading

### ISSUE THREAD

**Issue by LegendaryITA** [Solar-Tweaks/Solar-Tweaks#761]
**Describe the bug**
Minecraft doesn't load

**To Reproduce**
1. Select 1.19.2
2. Launch it
3. Wait Minecraft "loading"

**Expected behavior**
Minecraft main menu

**Actual behaviour**
Infinite loading

**Screenshots**
(https://gyazo.com/0f4165871b8d157375a218a439d1d740)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Launcher Version: v4.2.0
 - Engine Version: v.2.0
 - Solar Stats Version (if applicable)

**Comment by Enochisgood** [comment]
Hmmm...... well i have no solution for you but i suggest you delete all your solar tweaks files in %appdata%

**Comment by Enochisgood** [comment]
Well mine just says "Saving world" and then crashed anyway soo... welp

**Comment by HypedDomi** [comment]
To unclutter issues, we will close this issue. Please use
- https://github.com/Solar-Tweaks/Solar-Tweaks/issues/808
for more infos about the problem
