### ISSUE TITLE
Solar Tweaks does not open

### ISSUE THREAD

**Issue by ShadowPiercer** [Solar-Tweaks/Solar-Tweaks#763]
Please help, My solar tweaks is not booting up. I play 1.8.9 and it does not load. I have everything configured correctly, I am on Windows 11.

**Comment by HypedDomi** [comment]
We're not that active in GitHub. You get quicker support in our discord.

To your issue:
- Does the issue still occur?
- If yes, can you please send us your logs?

**Comment by HypedDomi** [comment]
Closed due to inactivity
