### ISSUE TITLE
open and crash

### ISSUE THREAD

**Issue by Xsharpness** [Solar-Tweaks/Solar-Tweaks#768]
open and then crash appear mojan logo and it says saving world athen crash

**Comment by Loopy322** [comment]
i cant open it

**Comment by BarrelPro100** [comment]
i can't open the last version, here the crash code CRASH-8880b3ad-d5c4-4e03-a18f-e2246864dc61

**Comment by xXWaterLOLXx** [comment]
CRASH-e699a7cf-47d6-4a9e-81a9-5328361b8a3d

**Comment by HypedDomi** [comment]
To unclutter issues, we will close this issue. Please use
- https://github.com/Solar-Tweaks/Solar-Tweaks/issues/808
for more infos about the problem
