### ISSUE TITLE
stuck on "finding lc assets" (already have tried every way to fix it)

### ISSUE THREAD

**Issue by Dennisssmenc** [Solar-Tweaks/Solar-Tweaks#769]
Alright so basically I cant use solar tweaks due to it being stuck on lc assets and ive tried these fixes:

1.restart it by using ctrl-r 

2.launching lunar client then launching solar tweaks afterwards

3.redownloaded both solar tweaks and lunar client to see if it would work

in short i cant find a single way to fix this problem maybe a new update for solar tweaks is due.

**Comment by HypedDomi** [comment]
Closed due to inactivity. When you're error still occur, try updating (launcher and client) and feel free to open a ticket in our discord server since we answer faster on discord
