### ISSUE TITLE
Solar booting Lunar

### ISSUE THREAD

**Issue by vindognz** [Solar-Tweaks/Solar-Tweaks#782]

**Comment by vindognz** [comment]
Later I found a log file (The second half is due to me force crashing my game).

[1.8.9-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10369275/1.8.9-latest.log)

**Comment by TBHGodPro** [comment]
Solar **Tweaks** is a modification of **Lunar Client**
