### ISSUE TITLE
Random FPS Drops after you spawn/respawn, also not launching in version 4.1.0.

### ISSUE THREAD

**Issue by KyleHW** [Solar-Tweaks/Solar-Tweaks#784]
I have experienced a lot of fps drops everytime I spawn or respawn in hypixel bedwars. There are multiple times that I had fps drops in other servers too. Also, 4.1.0 doesn't launch. I use macOS monterey.

**Expected behavior**
I thought I could launch the 4.1.0.

**Actual behaviour**
There are fps drops for around 5 seconds everytime I spawn or respawn. Sometimes it happens occasionally in the games too. Also, I cannot launch 4.1.0.

**Screenshots**
4.1.0
<img width="1290" alt="Screen Shot 2023-01-09 at 10 18 26 am" src="https://user-images.githubusercontent.com/122243451/211231793-59ed7a2a-4141-4015-9c71-21c6c65bc353.png">

**Environment (please complete the following information):**
Solar Tweaks 4.2.0 as 4.1.0 doesn't work for mac as it crashes everytime I launch it. I use macOS.

**Additional context**
JVM Arguments.
-Xverify:none -Xss2M -XX:+UnlockExperimentalVMOptions -XX:+AlwaysActAsServerClassMachine -XX:MaxTenuringThreshold=1 -XX:SurvivorRatio=32 -XX:G1HeapRegionSize=8M -XX:GCTimeLimit=50 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:-UsePerfData -XX:+PerfDisableSharedMem -XX:+UseLargePages -XX:+AlwaysPreTouch -XX:+EliminateLocks -XX:+AggressiveHeap -XX:+EagerJVMCI
I applied Zulu.

**Comment by HypedDomi** [comment]
We're not that active in GitHub. You get quicker support in our discord.

To your issue:
- Does the issue still occur?
- If yes, can you please send us your logs?
- Try updating the launcher. If the launcher does still not launch go to our discord and create a ticket. i will assist you then with a manual install

**Comment by HypedDomi** [comment]
Closed due to inactivity
