### ISSUE TITLE
Lunar Tweaks 1.19.2 CRASH-50338558-25af-44cd-83dd-55ce37aaa123

### ISSUE THREAD

**Issue by KokoTheOldDog** [Solar-Tweaks/Solar-Tweaks#785]
Trying to launch 1.19.2 

Getting to Mojang logo and it lags and crashes 

Seems it's not support them okay

**Comment by HypedDomi** [comment]
To unclutter issues, we will close this issue. Please use
- https://github.com/Solar-Tweaks/Solar-Tweaks/issues/808
for more infos about the problem
