### ISSUE TITLE
Solar Tweak Crashing

### ISSUE THREAD

**Issue by Tsering491** [Solar-Tweaks/Solar-Tweaks#792]
**Describe the bug**
Solar Tweaks crashes on launch

**To Reproduce**
1. Go to Solar Tweaks
2. Click on "Launch 1.8.9"
3. See error(Crash)

**Expected behavior**
Solar Tweaks opening with no issues

**Actual behaviour**
Client crashes without anything launching

**Screenshots**
![image](https://user-images.githubusercontent.com/61964895/212524391-742b8023-111c-44a8-869f-109f1f596d33.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Launcher Version: 4.2.0
 - Engine Version: -
 - Solar Stats Version: -

**Additional context**
CRASH-8ae32e44-f150-4fee-9a3e-f44a8c7382a0

**Comment by Tsering491** [comment]
anybody help?

**Comment by HypedDomi** [comment]
We're not that active in GitHub. You get quicker support in our discord.


To your issue:
- Does the issue still occur?
- If yes, can you please send us your logs?

**Comment by SP7Spartan** [comment]
Can i get an invite to the discord? I can't seem to find it.

**Comment by HypedDomi** [comment]
https://discord.gg/solarsocket

**Comment by HypedDomi** [comment]
Closed due to inactivity
