### ISSUE TITLE
Crashing on apple silicon

### ISSUE THREAD

**Issue by Inthreal** [Solar-Tweaks/Solar-Tweaks#793]
**Describe the bug**
The bug is lunar client 1.19.2 crashing on apple silicon

**To Reproduce**
1. Go to Lunar Tweaks
2. Click on Versions
3. Scroll down to 1.19.2
4. Then launch the client

**Expected behavior**
The client will start up into lunar client.

**Actual behaviour**
The client will launch up into the blank lunar client screen for a few seconds, go into loading then a "Saving world" will appear over the red mojang loading screen and it will crash.

**Screenshots**

**System**
-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Mac OS X (aarch64) version 13.0.1
	Java Version: 17.0.3, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 401705288 bytes (383 MiB) / 5100273664 bytes (4864 MiB) up to 5100273664 bytes (4864 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M2
	Identifier: Apple Inc. Family 0xda33d83d Model 0 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M2
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 18432.00
	Virtual memory used (MB): 11233.36
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 1171.25
	JVM Flags: 4 total; -XX:+DisableAttachMechanism -Xmx4864m -Xmn4864m -Xms4864m
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Apple M2 GL version 4.1 Metal - 83, Apple
	Window size: 2800x1536
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'solartweaksv2.0-lunarv1_19_2'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Apple M2
	OptiFine Version: OptiFine_1.19.2_HD_U_H9
	OptiFine Build: 20220820-230904
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.1 Metal - 83
	OpenGlRenderer: Apple M2
	OpenGlVendor: Apple
	CpuCount: 8

**Additional context**

[crash-2023-01-15_16.40.20-client.txt](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10421703/crash-2023-01-15_16.40.20-client.txt)
[1.19.2-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10421708/1.19.2-latest.log)

**Comment by NotSwasthiiik** [comment]
same issue

**Comment by ItzKushh** [comment]
yeah not working same pls help

**Comment by HypedDomi** [comment]
It's a known Problem. 1.16+ doesn't work and will be hopefully fixed soon:tm:
https://github.com/orgs/Solar-Tweaks/discussions/788

**Comment by HypedDomi** [comment]
To unclutter issues, we will close this issue. Please use
- https://github.com/Solar-Tweaks/Solar-Tweaks/issues/808
for more infos about the problem
