### ISSUE TITLE
Lag Spikes

### ISSUE THREAD

**Issue by DiePommess** [Solar-Tweaks/Solar-Tweaks#794]
Describe the bug
Every time my memory usage gets to around 90%, i get a lag for around 1 second.

To Reproduce
1. Launch the game
2. Wait for the Ram usage to hit 90%

Expected behavior
In Lunar the ram drops down at around 75%, so it should drop before it even hits 90%

Actual behaviour
The usage hits 90% and as it clears itself, my screen freezes for a second. 

Screenshots

Environment (please complete the following information):
 - OS: Windows 11
 - Launcher Version: 4.2.0
 - Engine Version: --
 - Solar Stats Version: --

Additional context

**Comment by redefault** [comment]
Use the Default jvm args preset.

**Comment by DiePommess** [comment]
I'm already using the default preset.

**Comment by DiePommess** [comment]
got it, i just reinstalled solar tweaks, but deleted the whole solartweaks section in .lunarclient. That worked for me!

**Comment by DiePommess** [comment]
sdf
