### ISSUE TITLE
Solar Tweaks 4.2.0 is not working on Linux

### ISSUE THREAD

**Issue by PedrowkaBR** [Solar-Tweaks/Solar-Tweaks#797]
When i try to open Solar Tweaks 4.2.0 that just does'nt open.

To reproduce open this on Linux, i'm on Pop Os 21.04, and it will stay in a black screen and does not load, it does not even show up to select the version, however the version 4.1.0 works perfectly. Fix it please!!

**Comment by HypedDomi** [comment]
Update to the latest Version
