### ISSUE TITLE
Nothing appears in the engine tab and solar tweaks taking long to load

### ISSUE THREAD

**Issue by TapeLovesOreos** [Solar-Tweaks/Solar-Tweaks#799]
**Describe the bug**
So i opened solar tweaks, clicked on apply  terumin then i clicked on default preset then when i go to engine tab nothing is there.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings tab
2. Click on terumin and select default preset
3. click on engine
4. nothing is there in engine

**Expected behavior**
when u apply terumin and click on defualt preset, i expect to see all the modules like fps spoof, cps text etc
**Actual behaviour**
Description of what is actually happening.
There is nothing visible
**Screenshots**
i am unable to add screenshots as i dont know how to but the engine tab is just black, no modules are there, nothing is there.
**Environment (please complete the following information):**
 - OS: Windows 10
 - Launcher Version 4.2.0
 - Engine Version 2.0 i think
 - Solar Stats Version not using

**Additional context**
please help me with this i rly want cosmetics

**Comment by HypedDomi** [comment]
Use a VPN. If the error still occurs, create a ticket on our discord server
