### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Speciallya** [Solar-Tweaks/Solar-Tweaks#8]
- [x] Cloth cloaks not working
- [x] 1.7 and possibly other versions not launching. Probably still audio bug aswell
- [x] ~~Old logo looked better~~
![image](https://user-images.githubusercontent.com/104172815/165378533-cda1c97a-346b-4317-a2bc-31721aa7ead0.png)
- [ ] Font here should be changed and solar tweaks logo would look cool in a different color.

**Comment by RichardDorian** [comment]
The bug where some versions can't be launched have been fixed! This fix will be deployed in the next update

**Comment by RichardDorian** [comment]
The "Old logo looked better" isn't a bug

**Comment by 770grappenmaker** [comment]
Could you elaborate on cloth cloaks not working? A screenshot of devtools, (optionally config.json) and /solardebug are very helpful.

**Comment by 770grappenmaker** [comment]
https://streamable.com/o5wj09 for me it is perfectly working 🤷
