### ISSUE TITLE
CRASH-d80e2feb-9c1a-4762-ae55-34de2ddeb3f4

### ISSUE THREAD

**Issue by Roger919yt** [Solar-Tweaks/Solar-Tweaks#800]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by NCGAM** [comment]
my game also crasing my crash code is this CRASH-c375055c-5d16-4ce8-9576-d4b5d92d5bbc
