### ISSUE TITLE
SUPER ANGRY BUG

### ISSUE THREAD

**Issue by FindMinecraftHotGirlSkin** [Solar-Tweaks/Solar-Tweaks#802]
I open mincraft but minecraft mutiplay hypixel i go to some multi server but its Lagging and back to my background so i found minecraft but minecraft is closed so i tried again again that happend what's wrong with this client its super angry error for me i can't play minecraft
with free loooooooooooooooooooook

**Comment by FindMinecraftHotGirlSkin** [comment]
And not this client Lunar client is like that

**Comment by FindMinecraftHotGirlSkin** [comment]
Lunar client and This client

**Comment by FindMinecraftHotGirlSkin** [comment]
so i'll play badlion client

**Comment by HypedDomi** [comment]
More infos and logs would be great. If you're using 1.16+ see this issue:
- https://github.com/Solar-Tweaks/Solar-Tweaks/issues/808

**Comment by HypedDomi** [comment]
Closed due to inactivity
