### ISSUE TITLE
Not Working On Mac

### ISSUE THREAD

**Issue by ItzKushh** [Solar-Tweaks/Solar-Tweaks#807]
It is not working when open it only shows the logo pls help! 
i am on mac m1 chip

**Comment by HypedDomi** [comment]
On which version are you?

**Comment by ItzKushh** [comment]
Hello!
my problem is actually when i open the solar tweaks it dont shows patcher pls help im on mac mc ver. 1.8.9

**Comment by HypedDomi** [comment]
The Patcher Tab got renamed to Engine

**Comment by ItzKushh** [comment]
yeah but when i click on engine it does't load up

**Comment by HypedDomi** [comment]
Try with a VPN

**Comment by ItzKushh** [comment]
and like if it does not work can u please please tell me any other lunar client thing for cracked latest version PLZ!!!

**Comment by HypedDomi** [comment]
It should work with VPN. Apparently I don't know any other Cracked Lunar

**Comment by ItzKushh** [comment]
Thanks !
