### ISSUE TITLE
Solar Tweaks crashes on 1.16 and higher

### ISSUE THREAD

**Issue by HypedDomi** [Solar-Tweaks/Solar-Tweaks#808]
We're aware of the bug and will fix it with the next release (No ETA yet).
Watch this issue for updates regarding this problem.
<img width="318" alt="image" src="https://user-images.githubusercontent.com/50876016/215748798-9b0213e4-da12-4b79-9707-fec59ff75585.png">

**Comment by Inthreal** [comment]
crashes on all versions for me lol

**Comment by HypedDomi** [comment]
Fixed
