### ISSUE TITLE
Solar tweaks crashing error

### ISSUE THREAD

**Issue by SP7Spartan** [Solar-Tweaks/Solar-Tweaks#809]
**Describe the bug**
Heres the code: CRASH-f6ad6d1d-bb11-4cef-ae63-4d9bba6883c7
The game launches but when I join a server, it crashes with a dialogue box showing the above mentioned code.

**To Reproduce**
1. Go to 'Multiplayer' in Minecraft Solar Tweaks Menu
2. Click on 'Direct connect' and enter any server
3. Wait for about 5 seconds

**Expected behavior**
The game connected to a desired server and runs properly.

**Actual behaviour**
Game closes with a dialogue box showing a crash code

**Environment (please complete the following information):**
 - OS: Windows 11
 - Launcher Version: 4.2.0
 - Engine Version:
 - Solar Stats Version: 

**Additional context**
[main.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10510009/main.log) Main.log file taken from C:\Users\User\\.lunarclient\logs\launcher

I am unable to find any crash logs but will most definitely try to attach if found

**Comment by HypedDomi** [comment]
Go to the about tab and click download logs
