### ISSUE TITLE
Does not launch mc 

### ISSUE THREAD

**Issue by Elytra22** [Solar-Tweaks/Solar-Tweaks#810]
the launcher works but whenever I try to actually launch it nothing happens i've tried for an hour of looking up possible fixes but nothing seems to work even on older versions it just says 'check LC files' but nothing happens after waiting

**Comment by HypedDomi** [comment]
Please give more infos such as version, logs, etc

Try updating lunar or enable skip checks

**Comment by Elytra22** [comment]
that worked thanks much love
