### ISSUE TITLE
None of the cosmetics and Solar Tweaks features work.

### ISSUE THREAD

**Issue by star0ninja** [Solar-Tweaks/Solar-Tweaks#815]
I've tried Solar Purge, reinstalled the launcher, changed the config and the patcher.
And yes i did change the websocket.

 Any more ideas?
![sad](https://user-images.githubusercontent.com/56049067/215356601-1f0a0c8a-86d7-445c-8851-dd24f03cc114.PNG)

**Comment by HypedDomi** [comment]
Which Websocket do you use? Maybe you're using the old Websocket or have a spelling error

**Comment by DuckysClips** [comment]
wss://socket.solartweaks.com
i use this one but i still dont have the items

**Comment by HypedDomi** [comment]
Closed due to inactivity
