### ISSUE TITLE
I am a cracked mc player, but my engine is not opening so i can't play on cracked lunar/solar tweaks I hope it will be fixed in the future updates

### ISSUE THREAD

**Issue by IH8F8** [Solar-Tweaks/Solar-Tweaks#818]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by IH8F8** [comment]
it's windows 10 note that

**Comment by HypedDomi** [comment]
You're supposed to put the info in the comment and not in the title. More Info would be great, like Launcher Version, Logs, etc

**Comment by HypedDomi** [comment]
Closed due to inactivity
