### ISSUE TITLE
can someone help me with this error?

### ISSUE THREAD

**Issue by Duccxxc** [Solar-Tweaks/Solar-Tweaks#819]
I get the error CRASH-97030383-6e73-49ef-87d3-acd42b4cffc2 can anyone help?
![Screenshot 2023-01-30 184236](https://user-images.githubusercontent.com/123977885/215540961-8ed340ce-96b8-4aee-8ab5-56602c3d72e7.png)

**Comment by HypedDomi** [comment]
Which version?

**Comment by Duccxxc** [comment]
> Which version?

1.19.2

**Comment by HypedDomi** [comment]
See https://github.com/Solar-Tweaks/Solar-Tweaks/issues/808
