### ISSUE TITLE
Crash on every Version

### ISSUE THREAD

**Issue by HypedDomi** [Solar-Tweaks/Solar-Tweaks#821]
crashes on all versions for me lol

_Originally posted by @Inthreal in https://github.com/Solar-Tweaks/Solar-Tweaks/issues/808#issuecomment-1409713977_

**Comment by HypedDomi** [comment]
@Inthreal Can you provide more Info like Launcher Version, Logs, etc

**Comment by Inthreal** [comment]
do you want logs for 1.8.9 crash?

**Comment by HypedDomi** [comment]
Yes. And your Launcher Version

**Comment by HypedDomi** [comment]
Closed due to inactivity
