### ISSUE TITLE
Im a cracked player and theres nothing in the Engines List

### ISSUE THREAD

**Issue by PlsHelpDracoSolarTweak** [Solar-Tweaks/Solar-Tweaks#823]
**Describe the bug**
Im a cracked user and I cant use Engines as there is NOTHING there.

**To Reproduce**
1. Go to 'Solar Tweaks"
2. Click on 'Engine

**Expected behavior**
There should be mods and feautures

**Actual behaviour**
Nothing is showing, just blank

**Screenshots**
[sssss.docx](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10548923/sssss.docx)

**Environment (please complete the following information):**
 - windows
 - Launcher Version 4.2
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

I just cant use it as no mods are showing
[1.18.2-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10548933/1.18.2-latest.log)

**Comment by HypedDomi** [comment]
Closed due to inactivity
