### ISSUE TITLE
crash 9c86083d-a093-4f16-8253-a33de4a1faf

### ISSUE THREAD

**Issue by abdullahiftikhar-code** [Solar-Tweaks/Solar-Tweaks#825]
I have been getting this crash whenever I try to open solar tweaks Lunar runs fine but only solar tweaks is buggy

**Comment by HypedDomi** [comment]
Add more Info like Launcher Version, MC Version, Logs, etc.

**Comment by abdullahiftikhar-code** [comment]
> Add more Info like Launcher Version, MC Version, Logs, etc.

The version in 1.8.9 launcher version in 4.20 and logs is this
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10568066/launcher-latest.log)

**Comment by HypedDomi** [comment]
Can you send the `1.8.9-latest.log` file?

**Comment by abdullahiftikhar-code** [comment]
> Can you send the `1.8.9-latest.log` file?

There was no such file in the logs folder

**Comment by HypedDomi** [comment]
You use normal Lunar and not LunarQT or something right?

**Comment by abdullahiftikhar-code** [comment]
> You use normal Lunar and not LunarQT or something right?

Yes I use normal Lunar Client

**Comment by abdullahiftikhar-code** [comment]
What if I use another version of solar tweaks if yes then which one would you recommend

**Comment by HypedDomi** [comment]
Older Versions are probably not working

**Comment by HypedDomi** [comment]
Closed due to inactivity
