### ISSUE TITLE
it crashes every time on startup. i deleted it and reinstalled it

### ISSUE THREAD

**Issue by DuckysClips** [Solar-Tweaks/Solar-Tweaks#826]
**Describe the bug**

**To Reproduce**
1. Go to 'launch the game'
2. Click on 'launch'
3. Scroll down to 'nothing, it just crashes'
without lunar installed "CRASH-3ced2189-1b0d-45b5-adf0-e85633b4e02"
with lunar installed "CRASH-fe5d4270-6259-442c-8791-f14cb51df5c7"
**Expected behavior**
to be able to launch and be able to have all the items and be able to play minecraft like the video i watched said
**crash**
Description of what is actually happening.
crash
**Screenshots**
![image](https://user-images.githubusercontent.com/118301353/216256282-6b828e5f-7206-448f-a1bc-f71a9dbd3f09.png)
![image1](https://user-images.githubusercontent.com/118301353/216256286-fb2ae392-7329-4626-ab06-aef4af47c765.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows]Windows 10
 - Launcher Version [eg. 4.0.1] 4.2.0
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable) idk

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)
https://www.youtube.com/watch?v=aKAxsc6GpEc
video i watched
( i cant find logs, somone help me out plz )

**Comment by HypedDomi** [comment]
Which Minecraft Version are you trying to start? You can find your logs when you go to About and then Download Logs

**Comment by DuckysClips** [comment]
i am trying 1.19.2 
its for a server im playing on
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10566219/launcher-latest.log)
here is the newest log. i tried one last time and it crashed again.

**Comment by HypedDomi** [comment]
1.19 is broken #808

**Comment by DuckysClips** [comment]
I tried it on 1.8.9 and it crashes

**Comment by HypedDomi** [comment]
Launch Lunar in 1.8.9 then try Solar Tweaks. I look in the logs in a bit

**Comment by HypedDomi** [comment]
Can you send the `1.8.9-latest.log`? You can go to the About Tab then click `Open ST Folder`, and then in the logs folder

**Comment by DuckysClips** [comment]
i got it to work on 1.8.9 but now i dont have any items

**Comment by DuckysClips** [comment]
![image](https://user-images.githubusercontent.com/118301353/216386092-6a28f61c-cfb3-4e9d-bff3-dbb6d8e9d502.png)

**Comment by DuckysClips** [comment]
wss://socket.solartweaks.com
this is the web socket i use

**Comment by HypedDomi** [comment]
Try this:
https://user-images.githubusercontent.com/50876016/216482686-64b3b96b-3ec1-4a4d-81ee-dc2930c84f4c.mp4

**Comment by Sleff1** [comment]
> i got it to work on 1.8.9 but now i dont have any items

How???? im also strugling and i can't fix it

**Comment by HypedDomi** [comment]
Closed due to inactivity
