### ISSUE TITLE
Cracked accounts aren't working

### ISSUE THREAD

**Issue by trollfacenan** [Solar-Tweaks/Solar-Tweaks#828]
**Describe the bug**
Title.

**To Reproduce**
1. Go to 'Engine'
2. Enable cracked accounts
3. Launch game
4. See error (Doesn't work for me atleast)

**Expected behavior**
The game should not ask to migrate the account with having cracked account enabled.

**Actual behaviour**
It requires for me to migrate an account (I have cracked accounts feature enabled, version 1.8.9 forge)

**Screenshots**

**Environment**
 - OS: Windows 11
 - Launcher Version 4.2.0
 - Engine Version v2.0
 - Solar Stats Version: I don't know what is that

**Additional context**
![image](https://user-images.githubusercontent.com/102139586/216275811-44ebbefa-0b6f-4291-8273-9542ea3d1e56.png)
![image](https://user-images.githubusercontent.com/102139586/216276086-7371008d-c622-4f11-8cb1-8f2422b2de56.png)

**Comment by abdullahiftikhar-code** [comment]
go into singleplayer make a single player world press escape and then go into multiplayer and then join a cracked server

**Comment by trollfacenan** [comment]
> go into singleplayer make a single player world press escape and then go into multiplayer and then join a cracked server

asks me to migrate the account even in singleplayer

**Comment by HypedDomi** [comment]
Update Lunar. You're Outdated

**Comment by trollfacenan** [comment]
> Update Lunar. You're Outdated

wym?? I'm literally on the latest ver.

**Comment by HypedDomi** [comment]
Oh they updated again. mb

**Comment by HypedDomi** [comment]
What is your Cracked Name? And can you send the `1.8.9-latest.log` file?

**Comment by trollfacenan** [comment]
> What is your Cracked Name? And can you send the `1.8.9-latest.log` file?

Can you tell me where is the log stored?
Name - riceistasty

**Comment by trollfacenan** [comment]
In AppData\Roaming\.minecraft\logs, I have only latest.log and not 1.8.9-latest.log

**Comment by HypedDomi** [comment]
> In AppData\Roaming.minecraft\logs, I have only latest.log and not 1.8.9-latest.log

Go in Solar Tweaks Launcher to About the click `Download Logs`

**Comment by trollfacenan** [comment]
what

**Comment by trollfacenan** [comment]
file still doesnt exist

**Comment by HypedDomi** [comment]
> what

https://user-images.githubusercontent.com/50876016/216647367-ee4d8f61-acf7-4d0c-908a-3162aa1ccc89.mov

**Comment by trollfacenan** [comment]
> > what
> 
> Screen.Recording.2023-02-03.at.16.51.43.mov

that's what I did already, but there is only launcher-latest.log

**Comment by trollfacenan** [comment]
Oh and also, it's 1.8.9 forge

**Comment by trollfacenan** [comment]
Okay, sending it lol

**Comment by trollfacenan** [comment]
[1.8.9-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10580517/1.8.9-latest.log)

**Comment by trollfacenan** [comment]
@HypedDomi ^^

**Comment by trollfacenan** [comment]
> > what
> 
> Screen.Recording.2023-02-03.at.16.51.43.mov

hello??

**Comment by HypedDomi** [comment]
I’ll look into it later

**Comment by trollfacenan** [comment]
![image](https://user-images.githubusercontent.com/102139586/216650697-fd339f59-ed5a-4fa8-a368-64cb2a3430fe.png)
unrecognized symbols moment

**Comment by HypedDomi** [comment]
Your Username is Russian. That's why it can't read your config. Change your Username or make a new local account with a readable username
