### ISSUE TITLE
Make it able to choose the specific jre not just folder location

### ISSUE THREAD

**Issue by buh93** [Solar-Tweaks/Solar-Tweaks#833]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
Please allow the custom JRE location to not just be a folder select but the option to actually choose what runs it- for example, "javaw" instead of "java"
**Describe alternatives you've considered**
no alternatives 

**Additional context**
![image](https://user-images.githubusercontent.com/67728403/216748063-53271603-45e9-45b9-b937-02f9c1227bba.png)

**Comment by HypedDomi** [comment]
Java handles it itself. There's no difference if you launch with java or javaw since you don't have a console window
![image](https://user-images.githubusercontent.com/50876016/216782611-7594c064-b9ad-47d7-b094-115968ccbb7e.png)

**Comment by buh93** [comment]
Helps with cheat injections- I know Entropy doesn’t work with solar but works with lunar because of that issue Sent from Collin's iPhoneOn Feb 4, 2023, at 10:04 AM, Dominik ***@***.***> wrote:﻿
Java handles it itself. There's no difference if you launch with java or javaw since you don't have a console window
