### ISSUE TITLE
FPS drops and Crashing 

### ISSUE THREAD

**Issue by JoshL77** [Solar-Tweaks/Solar-Tweaks#834]
I love Solar Tweaks but I get so many fps drops (to 0 fps) and crash. Im completely fine when using Lunar Client (not LCQT)

This experience happened when I was in 1.8.9 with Zulu JRE 

The logs file has my user name, so can I send them to you privately somehow?

Thank you :)

Settings ss are here:
![1](https://user-images.githubusercontent.com/97576203/216754343-d0238ff6-a7e5-4b03-b60d-5f9c0b20da31.png)
![2](https://user-images.githubusercontent.com/97576203/216754346-b73566d8-0765-45a2-9c4c-5ec139083cb6.png)
![3](https://user-images.githubusercontent.com/97576203/216754348-92021297-4c93-40aa-94dd-c5c143466bea.png)
![4](https://user-images.githubusercontent.com/97576203/216754350-911d2787-4aee-434f-abe6-5aa77f6ebdd4.png)
![6](https://user-images.githubusercontent.com/97576203/216754359-0f26b0a2-55ed-4cd6-9640-ee0a63c5d0b6.png)

**Comment by HypedDomi** [comment]
1. You already exposed your Username so you can send the logs here too
2. Try a different JRE and use different Arguments

**Comment by JoshL77** [comment]
> 1. You already exposed your Username so you can send the logs here too
> 2. Try a different JRE and use different Arguments

1. o...welp 
2. ok let me try that first

**Comment by JoshL77** [comment]
> > 1. You already exposed your Username so you can send the logs here too
> > 2. Try a different JRE and use different Arguments
> 
> 1. o...welp
> 2. ok let me try that first

graalvm works great here, thanks
