### ISSUE TITLE
Solar Tweaks 32-bits

### ISSUE THREAD

**Issue by xyfv** [Solar-Tweaks/Solar-Tweaks#835]
**Is your feature request related to a problem? Please describe.**
yep, the problem is bc i have a currently very old computer with an x86 structure and i want to try Solar Tweaks

**Describe the solution you'd like**
Make it possible to use Solar Tweaks on 32-bit computers like the Lunar Client

**Describe alternatives you've considered**
I haven't considered any alternatives due to it being a unique problem.

**Additional context**
Think about adding and including 32-bit users, because that's a big chunk of users who don't have a very good computer and would like to use Solar Tweaks to boost their FPS.
     When I was going to install Solar Tweaks I was sure I could install it because Lunar Client can be played with 32 bits

![image](https://user-images.githubusercontent.com/90474374/216773626-f3cb7492-480c-49d9-9247-12b80461abf0.png)

**Comment by HypedDomi** [comment]
Just install 64 Bit
