### ISSUE TITLE
Game doesn't launch.

### ISSUE THREAD

**Issue by USERNAMEGK** [Solar-Tweaks/Solar-Tweaks#836]
After pressing the launch button the game just won't launch. After enabling debug mode it showes up notepad with "*'C:\Users\(my username)' is not recognized as an internal or external command,
operable program or batch file."

it always worked, it started doing this recently.

**Comment by HypedDomi** [comment]
Disable Debug Mode and set your Args to this: `-XX:+DisableAttachMechanism`

**Comment by HypedDomi** [comment]
Closed due to inactivity
