### ISSUE TITLE
Launches then crashes

### ISSUE THREAD

**Issue by GamingIQ1** [Solar-Tweaks/Solar-Tweaks#837]
**Describe the bug**
Launches then crashes

**To Reproduce**
1. Go to 'Solar Tweaks'
2. Click on 'Launch 1.8.9'
3. See the error

**Expected behavior**
I expected it to launch so I could play

**Actual behaviour**
I launch it it takes 30 secs to 1 minute to launch and when it does its open for 5 seconds then crashes

**Screenshots**

**Environment (please complete the following information):**
 - OS: MACOS
 - Launcher Version: 4.2.0 
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by HypedDomi** [comment]
Can you send us your logs?

**Comment by GamingIQ1** [comment]
[logs.zip](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10609947/logs.zip)

**Comment by GamingIQ1** [comment]
i think thats it

**Comment by HypedDomi** [comment]
Update to the latest Version
