### ISSUE TITLE
integrated gpu launch fail

### ISSUE THREAD

**Issue by RENBOII** [Solar-Tweaks/Solar-Tweaks#838]
**You cant seem to launch the game or it wont launch after the solar tweaks window closes**
when you try to launch the game after making the jar program of the game into high performance settings in windows graphic settings, it doesnt launch after you apply it.. it only works when you use the default gpu (Intel) but doesnt work with the intergrated (Nvidea). it doesnt show up any error it just simply wont launch..

**To Reproduce**
1. Go to 'minecraft jar file directory'
2. Copy the file directory
3. Go to ' windows "graphics setting"'
4. select browse and choose the jar file which minecraft uses ex:- java, javaw
5. click on high performance
6. save and run the game

**Expected behavior**
when you do it, it should say that the game is launching and it should say the game is running before it closes, but it wont even if you wait for a long time.

**Environment (please complete the following information):**
 - OS: Windows 10 1809 build 
 - Launcher Version. 2.0
 - Engine Version [eg. 1.6] ()
 - Solar Stats Version (if applicable)

[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10610573/launcher-latest.log)
this is the latest log after the game wont launch

**Comment by HypedDomi** [comment]
@RENBOII Can i close this? You made a ticket on Discord

**Comment by HypedDomi** [comment]
Closed due to inactivity
