### ISSUE TITLE
Solar Tweaks Not Launching

### ISSUE THREAD

**Issue by ImmortalSwarit** [Solar-Tweaks/Solar-Tweaks#839]
So I'm trying to use Solar Tweaks, and it goes through the entire process. It opens the Minecraft, where it says that the lunar client has loaded, but when the mojang studios screen appeared, it hanged for about 5 seconds and then it said that the client had crashed. It also gave an error id: CRASH-400fce1c-d7b5-4bd2-a214-d27d339296da
I did things like downloaded the JRE and applied it but its not working.

**Comment by ImmortalSwarit** [comment]
now its saying - CRASH-41627ce4-693f-4989-b668-b6e97c5a4a0a upon opening it again.

**Comment by ImmortalSwarit** [comment]
can someone please help - CRASH-12e25080-e53f-409b-8ebd-d79a94c9f355

**Comment by HypedDomi** [comment]
#808

**Comment by HypedDomi** [comment]
Closed due to inactivity
