### ISSUE TITLE
This bug appear when i launch solar tweaks 1.19.2 with sodium. code: CRASH-a8041e2f-3046-4fa9-85cd-610e32d5eda5

### ISSUE THREAD

**Issue by supermonkey9985** [Solar-Tweaks/Solar-Tweaks#841]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by HypedDomi** [comment]
#808
