### ISSUE TITLE
minecraft 1.8.9 does not launch   and stuck at Starting JVM in the launcher pls help

### ISSUE THREAD

**Issue by EditingMitten39** [Solar-Tweaks/Solar-Tweaks#844]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by HypedDomi** [comment]
Update Lunar

**Comment by HypedDomi** [comment]
Closed due to inactivity
