### ISSUE TITLE
Fps drop to 0 , comes back to original fps then does the same thing again after some time

### ISSUE THREAD

**Issue by Razvanlululu** [Solar-Tweaks/Solar-Tweaks#846]
description
This bug happens when im playing generally , in any occasion the bug happe,s,i have the best settings for perfomance and everything.

To Reproduce
just to play in general

Expected behavior
I expected to play minecraft smoothly and no glitches

Actual behaviour
fps drops for no reason

Environment
 - OS: [Window 11]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [ ]
 - Solar Stats Version ( )

I hope this gets fixed cuz at the end of the day the bug keeps happening each 5mins while playing and its getting annoying now.

**Comment by HypedDomi** [comment]
Try default Arguments. If the error still occurs add more info

**Comment by HypedDomi** [comment]
Also update to the latest version. If the error still occurs, reopen the issue
