### ISSUE TITLE
when i launch the client it appears that pack pack.mcmeta is missing

### ISSUE THREAD

**Issue by nicoSyrr** [Solar-Tweaks/Solar-Tweaks#849]
**Expected behavior**
it should have icon and sound

**Actual behaviour**
minecraft doesnt have icon and sound
**Screenshots**
![image](https://user-images.githubusercontent.com/125300792/218533949-4367dd6a-dec6-4c44-ba00-d42136e44821.png)

**Environment 
 - Windows
 - Launcher Version [4.3.0]

**Comment by wcaleniekubaa** [comment]
It doesnt affect the gameplay
it is just a thing that appears in resource pack screen

**Comment by nicoSyrr** [comment]
it indeed affect the gameplay, i dont have any sound, it doesnt have any icon

**Comment by wcaleniekubaa** [comment]
try launching 1.8.9 before

**Comment by HypedDomi** [comment]
@nicoSyrr did it work?

**Comment by nicoSyrr** [comment]
nope

**Comment by HypedDomi** [comment]
Do you have the same problem on lunar?

**Comment by nicoSyrr** [comment]
no

**Comment by nicoSyrr** [comment]
its not onlt 1.7, its on all versions of solar tweaks

**Comment by redefault** [comment]
Update to 4.3.1 and also dont forget to launch the same version on lunar before solar tweaks.

**Comment by HypedDomi** [comment]
When the error still occurs, reopen the issue
