### ISSUE TITLE
Launching error

### ISSUE THREAD

**Issue by s41dzz** [Solar-Tweaks/Solar-Tweaks#850]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

i dont understand what to do with the format 
my solar tweaks version is 4.20 i know theres a new version but it didnt work even when the new update wasnt out so, it wont launch, its stuck on checking lc assets, and when i checked the skip checking files option in the settings, i got an error "extraArchivery" i dont know if im right but it was something "extra" so yeah i wanna play lunar pls help

**Comment by HypedDomi** [comment]
Add more info

**Comment by s41dzz** [comment]
what info do you need

**Comment by HypedDomi** [comment]
Logs, Launcher Version, MC Version, Engine Version

**Comment by HypedDomi** [comment]
Closed due to inactivity
