### ISSUE TITLE
The game will freeze for 1~2 seconds in less than a minute.

### ISSUE THREAD

**Issue by fireHaoHao** [Solar-Tweaks/Solar-Tweaks#852]
**Describe the bug**
The game will freeze for 1~2 seconds in less than a minute.
**To Reproduce**
Happens whenever in-game, no matter which server.

**Expected behavior**
Plays smoothly without any game lag.
**Actual behaviour**
Description of what is actually happening.
The game freezes for 1~2 seconds every minute. It doesn’t happen when I use the original Lunar Client, and it doesn’t happen before 4.1.0. But after I updated to 4.2.0, this bug started to happen. I Originally thought that 4.3.0 would be fixed, so I started waiting for 4.3.0 from 4.2.0, but it seems that 4.3.0 will still be stuck.
**Screenshots**
The photo is too difficult to present, so I uploaded it to YouTube, here is the link
[https://www.youtube.com/watch?v=_FEnU7np-dY](https://www.youtube.com/watch?v=_FEnU7np-dY)
**Environment (please complete the following information):**
 - OS: [Windows]
 - Launcher Version [4.3.0]
 - Engine Version [ ] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

Please fix this, the constant lag is really annoying, especially in Speed bridging and PVP. THX

**Comment by HypedDomi** [comment]
Try default presets
