### ISSUE TITLE
The hurt cam multiplier mod is bugged and it doesn't seem to do anything. The main reason i play on solar tweaks is blc crashes my pc alot. No hurt cam shake makes my game smooth. Pls fix asap

### ISSUE THREAD

**Issue by BradDanger** [Solar-Tweaks/Solar-Tweaks#854]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by HypedDomi** [comment]
Did you change the multiplier?

**Comment by HypedDomi** [comment]
Closed due to inactivity
