### ISSUE TITLE
Hurt cam not working at all

### ISSUE THREAD

**Issue by Rank11011** [Solar-Tweaks/Solar-Tweaks#855]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by HypedDomi** [comment]
What exactly is not working? Provide more info

**Comment by HypedDomi** [comment]
Closed due to inactivity

**Comment by Fantasy924** [comment]
is this fixed?
