### ISSUE TITLE
Solar Engine not work

### ISSUE THREAD

**Issue by Artem-xe** [Solar-Tweaks/Solar-Tweaks#856]
it isn't working somewhy fps spoof not working and everthing

**Comment by HypedDomi** [comment]
What is your multiplier?

**Comment by Artem-xe** [comment]
1

**Comment by Artem-xe** [comment]
And cosmetics not working

**Comment by HypedDomi** [comment]
> 1

Yeah it does work. It just multiplies it by 1 which is the same result. Change your multiplier

**Comment by HypedDomi** [comment]
> And cosmetics not working

Cosmetics wont work on cracked Accounts

**Comment by Artem-xe** [comment]
Im not on cracked account Im acutlly on premium account. comsetics must work on premium account but somewhy it doesn't work

**Comment by HypedDomi** [comment]
Did you put the right websocket link?

**Comment by Artem-xe** [comment]
Yes

**Comment by Artem-xe** [comment]
![image](https://user-images.githubusercontent.com/70347130/219392241-7db25750-7b05-4bdd-9f83-32521e7e3e5e.png)

**Comment by Artem-xe** [comment]
Maybe solar tweeks wont work anymore.

**Comment by HypedDomi** [comment]
Send your logs

**Comment by Artem-xe** [comment]
How to view logs

**Comment by Artem-xe** [comment]
[INFO] [home] Fetched Lunar Client Blog Posts [object Object],[object Object],[object Object]
[INFO] [settings] Setting up settings at file path C:\Users\Артем\AppData\Roaming\solartweaks\settings.json...
[INFO] [settings] Settings Setup at C:\Users\Артем\AppData\Roaming\solartweaks\settings.json
[DEBUG] [Engine] Verifying Config Exists...
[DEBUG] [Engine] Fetching Updater Index
[DEBUG] [Engine] Fetched Config Example: [object Object]
[DEBUG] [Engine] Fetched Metadata: [object Object]
[INFO] [updater] Checking for updates...
[ERROR] [discord] Error: Could not connect
[INFO] [LunarChecker] Checking for Lunar Client...
[INFO] [LunarChecker] Platform: win32
[INFO] [LunarChecker] Checking for Lunar Client in C:\Users\Артем\AppData\Local\Programs\lunarclient\Lunar Client.exe
[INFO] [LunarChecker] Lunar Client found
[INFO] [updater] Launcher up to date
[INFO] [settings] Fetched available JREs: [object Object]
[INFO] [launcher] Fetching metadata...
[DEBUG] [launcher] Fetched metadata [object Object]
[INFO] [launcher] Checking .lunarclient directory
[DEBUG] [launcher] Checking .lunarclient subdirectories
[DEBUG] [launcher] licenses subdirectory already exists, skipping...
[INFO] [launcher] Checking licenses...
[DEBUG] [launcher] offline subdirectory already exists, skipping...
[DEBUG] [launcher] Checking license 1/48
[DEBUG] [launcher] Checking license 2/48
[DEBUG] [launcher] Checking license 3/48
[DEBUG] [launcher] Checking license 4/48
[DEBUG] [launcher] Checking license 5/48
[DEBUG] [launcher] Checking license 6/48
[DEBUG] [launcher] Checking license 7/48
[DEBUG] [launcher] Checking license 8/48
[DEBUG] [launcher] Checking license 9/48
[DEBUG] [launcher] Checking license 10/48
[DEBUG] [launcher] Checking license 11/48
[DEBUG] [launcher] Checking license 12/48
[DEBUG] [launcher] Checking license 13/48
[DEBUG] [launcher] Checking license 14/48
[DEBUG] [launcher] Checking license 15/48
[DEBUG] [launcher] Checking license 16/48
[DEBUG] [launcher] Checking license 17/48
[DEBUG] [launcher] Checking license 18/48
[DEBUG] [launcher] Checking license 19/48
[DEBUG] [launcher] Checking license 20/48
[DEBUG] [launcher] Checking license 21/48
[DEBUG] [launcher] Checking license 22/48
[DEBUG] [launcher] Checking license 23/48
[DEBUG] [launcher] Checking license 25/48
[DEBUG] [launcher] Checking license 26/48
[DEBUG] [launcher] Checking license 27/48
[DEBUG] [launcher] Checking license 28/48
[DEBUG] [launcher] Checking license 29/48
[DEBUG] [launcher] Checking license 30/48
[DEBUG] [launcher] Checking license 31/48
[DEBUG] [launcher] Checking license 32/48
[DEBUG] [launcher] Checking license 24/48
[DEBUG] [launcher] Checking license 33/48
[DEBUG] [launcher] Checking license 34/48
[DEBUG] [launcher] Checking license 35/48
[DEBUG] [launcher] Checking license 36/48
[DEBUG] [launcher] Checking license 37/48
[DEBUG] [launcher] Checking license 38/48
[DEBUG] [launcher] Checking license 39/48
[DEBUG] [launcher] Checking license 40/48
[DEBUG] [launcher] Checking license 41/48
[DEBUG] [launcher] Checking license 42/48
[DEBUG] [launcher] Checking license 43/48
[DEBUG] [launcher] Checking license 44/48
[DEBUG] [launcher] Checking license 45/48
[DEBUG] [launcher] Checking license 46/48
[DEBUG] [launcher] Checking license 47/48
[DEBUG] [launcher] Checking license 48/48
[INFO] [launcher] Checking Game Files (MC 1.8.9)...
[DEBUG] [launcher] Checking game file 1/9
[DEBUG] [downloader] Checking hash of C:\Users\Артем\.lunarclient\offline\multiver\v1_8-0.1.0-SNAPSHOT-all.jar...
[DEBUG] [downloader] Hash matches for C:\Users\Артем\.lunarclient\offline\multiver\v1_8-0.1.0-SNAPSHOT-all.jar
[DEBUG] [launcher] Checking game file 2/9
[DEBUG] [downloader] Checking hash of C:\Users\Артем\.lunarclient\offline\multiver\optifine-0.1.0-SNAPSHOT-all.jar...
[DEBUG] [downloader] Hash matches for C:\Users\Артем\.lunarclient\offline\multiver\optifine-0.1.0-SNAPSHOT-all.jar
[DEBUG] [downloader] Checking hash of C:\Users\Артем\.lunarclient\offline\multiver\OptiFine_v1_8.jar...
[DEBUG] [launcher] Checking game file 3/9
[DEBUG] [downloader] Hash matches for C:\Users\Артем\.lunarclient\offline\multiver\OptiFine_v1_8.jar
[DEBUG] [launcher] Checking game file 4/9
[DEBUG] [downloader] Checking hash of C:\Users\Артем\.lunarclient\offline\multiver\common-0.1.0-SNAPSHOT-all.jar...
[DEBUG] [downloader] Hash matches for C:\Users\Артем\.lunarclient\offline\multiver\common-0.1.0-SNAPSHOT-all.jar
[DEBUG] [launcher] Checking game file 5/9
[DEBUG] [downloader] Checking hash of C:\Users\Артем\.lunarclient\offline\multiver\genesis-0.1.0-SNAPSHOT-all.jar...
[DEBUG] [downloader] Hash matches for C:\Users\Артем\.lunarclient\offline\multiver\genesis-0.1.0-SNAPSHOT-all.jar
[DEBUG] [downloader] Checking hash of C:\Users\Артем\.lunarclient\offline\multiver\lunar-lang.jar...
[DEBUG] [launcher] Checking game file 6/9
[DEBUG] [downloader] Hash matches for C:\Users\Артем\.lunarclient\offline\multiver\lunar-lang.jar
[DEBUG] [downloader] Checking hash of C:\Users\Артем\.lunarclient\offline\multiver\lunar-emote.jar...
[DEBUG] [launcher] Checking game file 7/9
[DEBUG] [downloader] Hash matches for C:\Users\Артем\.lunarclient\offline\multiver\lunar-emote.jar
[DEBUG] [launcher] Checking game file 8/9
[DEBUG] [downloader] Checking hash of C:\Users\Артем\.lunarclient\offline\multiver\lunar.jar...
[DEBUG] [downloader] Hash matches for C:\Users\Артем\.lunarclient\offline\multiver\lunar.jar
[DEBUG] [launcher] Checking game file 9/9
[DEBUG] [downloader] Checking hash of C:\Users\Артем\.lunarclient\offline\multiver\client-natives-win-x86-v1_8.zip...
[DEBUG] [downloader] Hash matches for C:\Users\Артем\.lunarclient\offline\multiver\client-natives-win-x86-v1_8.zip
[INFO] [launcher] Checking natives...
[DEBUG] [launcher] Natives already extracted
[INFO] [downloader] Downloading https://textures.lunarclientcdn.com/index/314ba4fd5fe0f0e6fee743debebab6521a0c5b24...
[INFO] [downloader] Downloaded https://textures.lunarclientcdn.com/index/314ba4fd5fe0f0e6fee743debebab6521a0c5b24
[DEBUG] [downloader] Saving to C:\Users\Артем\.lunarclient\launcher-cache\texturesIndex.txt...
[DEBUG] [downloader] Checking hash of C:\Users\Артем\.lunarclient\launcher-cache\texturesIndex.txt...
[DEBUG] [downloader] Hash matches for C:\Users\Артем\.lunarclient\launcher-cache\texturesIndex.txt
[INFO] [launcher] Checking 4707 Total Assets
[INFO] [launcher] Checking 2500 Assets
[INFO] [launcher] Checking 2207 Assets
[INFO] [launcher] Completed Checking Assets
[INFO] [launcher] Checking engine...
[DEBUG] [Engine] Verifying Config Exists...
[DEBUG] [Engine] Fetching Updater Index
[DEBUG] [Engine] Fetched Config Example: [object Object]
[DEBUG] [Engine] Fetched Metadata: [object Object]
[DEBUG] [launcher] Launching game with args

 --add-modules
jdk.naming.dns
--add-exports
jdk.naming.dns/com.sun.jndi.dns=java.naming
-Djna.boot.library.path=C:\Users\Артем\.lunarclient\offline\multiver\natives
-Dlog4j2.formatMsgNoLookups=true
--add-opens
java.base/java.io=ALL-UNNAMED
-javaagent:C:\Users\Артем\.lunarclient\solartweaks\solar-engine.jar=C:\Users\Артем\.lunarclient\solartweaks\config.json
-XX:+DisableAttachMechanism
-Xmx4096m
-Xmn4096m
-Xms4096m
-Djava.library.path=C:\Users\Артем\.lunarclient\offline\multiver\natives
-Dsolar.launchType=launcher
-cp
v1_8-0.1.0-SNAPSHOT-all.jar;optifine-0.1.0-SNAPSHOT-all.jar;common-0.1.0-SNAPSHOT-all.jar;genesis-0.1.0-SNAPSHOT-all.jar;lunar-lang.jar;lunar-emote.jar;lunar.jar
com.moonsworth.lunar.genesis.Genesis
--version
1.8.9
--accessToken
0
--assetIndex
1.8
--userProperties
{}
--gameDir
C:\Users\Артем\AppData\Roaming\.minecraft
--assetsDir
C:\Users\Артем\AppData\Roaming\.minecraft\assets
--texturesDir
C:\Users\Артем\.lunarclient\textures
--width
854
--height
480
--ichorClassPath
v1_8-0.1.0-SNAPSHOT-all.jar,optifine-0.1.0-SNAPSHOT-all.jar,common-0.1.0-SNAPSHOT-all.jar,genesis-0.1.0-SNAPSHOT-all.jar,lunar-lang.jar,lunar-emote.jar,lunar.jar
--ichorExternalFiles
OptiFine_v1_8.jar
--workingDirectory
.
--classpathDir
C:\Users\Артем\.lunarclient\offline\multiver
--installationId
5a61faa4-1322-4cb2-8448-8effe2d3a17a
--hwid
de1155efaf7123f202a1e55683bb933adf615e61a83907bfeb44449e4526d878
[DEBUG] [launcher] Created Minecraft Logger for version 1.8.9. Log file path: C:\Users\Артем\.lunarclient\solartweaks\logs\1.8.9-latest.log

**Comment by Artem-xe** [comment]
Police will report you

**Comment by HypedDomi** [comment]
> Police will report you

What?

**Comment by HypedDomi** [comment]
Anyway. Your name is russian. Thats why it wont work. Change your Username or make a new folder

**Comment by Artem-xe** [comment]
Im not a russian and im polish man.

**Comment by Artem-xe** [comment]
My nickname isn't russia

**Comment by Artem-xe** [comment]
Thats A joke man?

**Comment by HypedDomi** [comment]
Its not. Due to your Username it cant load the config.

**Comment by Artem-xe** [comment]
my nickname is backwards on minecraft.

**Comment by HypedDomi** [comment]
I dont mean ypur mc username. Your Windows Username is conflicting
