### ISSUE TITLE
[Enhancement] Ability to login without the Lunar Client launcher

### ISSUE THREAD

**Issue by he3als** [Solar-Tweaks/Solar-Tweaks#857]
**Is your feature request related to a problem? Please describe.**
Solar Tweaks currently is not a complete replacement for the Lunar Client launcher, as you still need the official launcher open to login with your Microsoft account.

**Describe the solution you'd like**
A built in replacement for this embedded sign in view in Solar Tweaks, so that you do not have to depend on the official launcher.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by 770grappenmaker** [comment]
@TBHGodPro were you working on this?

**Comment by TBHGodPro** [comment]
This feature has existed since 4.2.0 iirc, maybe earlier.

Are you sure you are on the newest version?

**Comment by he3als** [comment]
I am on the latest version.

![image](https://user-images.githubusercontent.com/65787561/221686791-6806635e-310e-40db-8c60-1727760fe259.png)

**Comment by 770grappenmaker** [comment]
Enable Keep Launcher Open

**Comment by he3als** [comment]
Oh, I didn't realise, very sorry. Maybe a note about not being able to sign in with the 'Close Launcher' option would be good?
