### ISSUE TITLE
Launcher not actually updating

### ISSUE THREAD

**Issue by SevereDev** [Solar-Tweaks/Solar-Tweaks#858]
**Describe the bug**

Every time I open up the launcher, it asks me to update. Even though I've already clicked update more than 10 times, it still asks me to update every time I launch.

**To Reproduce**

Open the launcher

**Expected behavior**

The new 4.3.0 launcher

**Actual behavior**
Description of what is actually happening.

4.2.0 launcher asking me to update even though it was already updated

**Environment (please complete the following information):**
 - OS: Windows
 - Launcher Version [eg. 4.0.2]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Comment by HypedDomi** [comment]
Uninstall it. You have it installed 2 times
