### ISSUE TITLE
Allow Cracked accounts not working

### ISSUE THREAD

**Issue by NoNameMila** [Solar-Tweaks/Solar-Tweaks#861]
Im removed all premium accounts and its not working

**Comment by HypedDomi** [comment]
Dont click the Account thing. Just click Multiplayer

**Comment by AungS8430** [comment]
It is not working for me as well, I launch the client and clicked on Multiplayer but it shows login page.

**Comment by HypedDomi** [comment]
Update Lunar

**Comment by AungS8430** [comment]
I literally install both Lunar and Solar Tweaks today.

**Comment by HypedDomi** [comment]
Is your Username russian?

**Comment by AungS8430** [comment]
no

**Comment by HypedDomi** [comment]
Can you send your logs

**Comment by AungS8430** [comment]
wait a min

**Comment by AungS8430** [comment]
i tried launching it again, and somehow it worked, thank you
