### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Shadwbtw** [Solar-Tweaks/Solar-Tweaks#862]
**Describe the bug**
I launch the game and its just a lunar client without the tweaks

**Environment (please complete the following information):**
 - OS: [Windows]
 - Launcher Version [Latest]

**Comment by HypedDomi** [comment]
Can you send your Logs

**Comment by Shadwbtw** [comment]
how do i do that?

**Comment by HypedDomi** [comment]
1. Open SolarTweaks
2. Go to the About Tab
3. Click `Open ST directory`
4. Send the logs folder

**Comment by Shadwbtw** [comment]
i started the game and it worked for some reason so yeah
