### ISSUE TITLE
CRASH-f9295b75-efae-47f4-a6b4-37a913873511

### ISSUE THREAD

**Issue by ayoindo67** [Solar-Tweaks/Solar-Tweaks#863]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by HypedDomi** [comment]
Please fill out the form. We can't help without Info

**Comment by HypedDomi** [comment]
Closed due to inactivity
