### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by Sai5810** [Solar-Tweaks/Solar-Tweaks#867]
I get no game audio, from menus to attack sounds. It works perfectly fine on lunar. I check the sound mixer and mc sound settings, it's not an issue on my end. 
**Environment (please complete the following information):**
 - OS: Windows
 - Launcher Version 4.3

Launcher Settings
![image](https://user-images.githubusercontent.com/69466160/219832942-16dc5b8c-ee0d-492c-8519-fe2930e584bf.png)

**Comment by redefault** [comment]
a bug with 1.7 currently.
if its with any other versions please tell us.

**Comment by Yumasko** [comment]
> a bug with 1.7 currently. if its with any other versions please tell us.

Experiencing this issue on 1.19.3 too

**Comment by HypedDomi** [comment]
Should be fixed with the next release.
