### ISSUE TITLE
Not launching

### ISSUE THREAD

**Issue by tomanskas** [Solar-Tweaks/Solar-Tweaks#870]
**Describe the bug**
when I try to launch the game it says "starting JVM" but then just turn back green and nothing launches.

**To Reproduce**
1. Go to 'solar tweaks'
2. Click on 'launch 1.8.9'
3. and nothing launches

**Expected behavior**
well i want the game to launch thats about it

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - Windows 10
 - Launcher Version 4.3.0
 - Engine Version 
 - Solar Stats Version

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by tomanskas** [comment]
[1.8.9-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10774795/1.8.9-latest.log)
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10774796/launcher-latest.log)

**Comment by kimovoid** [comment]
how did you fix this? my friend is having the same issue with the same error in the log
