### ISSUE TITLE
big lag spikes

### ISSUE THREAD

**Issue by GamingIQ1** [Solar-Tweaks/Solar-Tweaks#872]
**Describe the bug**

**To Reproduce**
1. Go to 'solar tweaks'
2. Click on 'launch 1.8.9'

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Macos
 - Launcher Version: 4.3.0
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
I don't think I need to add my logs its just a really annoying bug that u need to fix please

**Comment by HypedDomi** [comment]
Change your JVM Args. Just use a preset

**Comment by GamingIQ1** [comment]
thank u!
