### ISSUE TITLE
'assetIndex' is wrong for 1.7.10

### ISSUE THREAD

**Issue by he3als** [Solar-Tweaks/Solar-Tweaks#873]
**Describe the bug**
Solar Tweaks is launching the game with `--assetIndex 1.7`, which causes there to be no sound. Comparing to Lunar Client's launch arguments, it is now `--assetIndex 1.7.10`.

![librewolf_j4ffEC18rE](https://user-images.githubusercontent.com/65787561/219940908-beca0204-3f98-4870-bc4c-71489cbc6b6c.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Launcher Version: 4.3.0

**Comment by he3als** [comment]
As a note, I tested using `--assetIndex 1.7.10` and it fixed the issue

**Comment by heyitsleo** [comment]
I see, Thank you for reporting this.

**Comment by heyitsleo** [comment]
> As a note, I tested using `--assetIndex 1.7.10` and it fixed the issue

Can you tell us where you changed it? Which SRC and what file?

**Comment by he3als** [comment]
I didn't fix the JS, because I don't know JS. I just ran the command line for Solar with that argument fixed in Command Prompt.

https://github.com/Solar-Tweaks/Solar-Tweaks/blob/main/src/javascript/minecraft.js#L565

**Comment by heyitsleo** [comment]
> I didn't fix the JS, because I don't know JS. I just ran the command line for Solar with that argument fixed in Command Prompt.
> 
> https://github.com/Solar-Tweaks/Solar-Tweaks/blob/main/src/javascript/minecraft.js#L565

We've fixed the issue, thank you for reporting this issue! 😁
