### ISSUE TITLE
[Enhancement] Remove Lunar News in launcher

### ISSUE THREAD

**Issue by GamingIQ1** [Solar-Tweaks/Solar-Tweaks#881]
**Describe the solution you'd like**
I know your tweaking lunar client but can you like remove the lunar client news at the bottom and replace them with I don't know an update thing and when you click it, it sends you to their website and read the changelog

**Describe alternatives you've considered**

**Additional context**
<img width="1412" alt="Screenshot 2023-02-21 at 11 19 02 PM" src="https://user-images.githubusercontent.com/113652511/220530233-0b8f5ec6-6bfc-4c5c-a2af-d5ce12dd702f.png">

**Comment by 770grappenmaker** [comment]
Optionally?

**Comment by TBHGodPro** [comment]
We won't be adding this, the way our launcher works is:

- Any blog posts we want there will be there
- Any empty spaces will be filled with official Lunar blogposts

This is to improve the UI and make sure that there are no empty spaces
