### ISSUE TITLE
Add wrapper command like on MultiMC

### ISSUE THREAD

**Issue by danknil** [Solar-Tweaks/Solar-Tweaks#882]
**Is your feature request related to a problem? Please describe.**
For recording minecraft gameplay i often using [obs-vkcapture](https://github.com/nowrep/obs-vkcapture) which isn't possible with lunar & solar tweaks because it needs to wrap a program (e.g. `obs-gamecapture <program here>`). MultiMC and forks has functionality for that, called wrapper command.

**Describe the solution you'd like**
Add wrapper command functionality like on multimc

**Describe alternatives you've considered**
add button to enable obs-vkcapture with lunar

**Additional context**
example of feature in prism launcher:
![image](https://user-images.githubusercontent.com/65212334/220552444-16bc288c-a3b0-4f96-b9d8-35546a2f2b84.png)

**Comment by 770grappenmaker** [comment]
@TBHGodPro

**Comment by TBHGodPro** [comment]
@770grappenmaker @HypedDomi  Im not exactly sure how this would work, do either of you have experience with this and how to do it? If so I'll try to implement it.

**Comment by TBHGodPro** [comment]
> > @770grappenmaker @HypedDomi  Im not exactly sure how this would work, do either of you have experience with this and how to do it? If so I'll try to implement it.
> 
> If you set wrapper command to `abc`, full command will be `abc javaw ...therest`, thats all, just a "prefix"

Well the issue is, how would I impl that into the `spawn()` func, since the first arg (the command) is currently a file path, so would I put "abc ${javaPath} ...args"?

**Comment by 770grappenmaker** [comment]
That will not work, you should set it as the command name, and set the first argv to java

**Comment by TBHGodPro** [comment]
> That will not work, you should set it as the command name, and set the first argv to java

Well it currently executes the java path directly to allow multiple java vms, so instead of `java` or `javaw`, it runs the java file path. So if I do `abc "${filePath}" ...args` (quotes in case filePath has spaces), it should work no?
