### ISSUE TITLE
Solar doesn't launch

### ISSUE THREAD

**Issue by Sai5810** [Solar-Tweaks/Solar-Tweaks#885]
**Describe the bug**
I hit the launch button, and the launcher closes, but Minecraft never launches.

**Screenshots**
![image](https://user-images.githubusercontent.com/69466160/221058670-28709d46-b435-4046-8a51-90c78ca73e1f.png)
The last screen I see until the launcher closes and nothing ever opens.

**Environment (please complete the following information):**
 - OS: Windows
 - Launcher Version 4.3.1

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)
![image](https://user-images.githubusercontent.com/69466160/221058785-cb05923a-4e24-42f6-8450-133176d61c7f.png)
![image](https://user-images.githubusercontent.com/69466160/221058796-ce5cfe79-0d82-44f9-93eb-68da87a5dcc2.png)

**Comment by HypedDomi** [comment]
Please send your logs:

1. Open SolarTweaks
2. Go to the About Tab
3. Click `Open ST directory`
4. Send the logs folder

**Comment by Sai5810** [comment]
[1.7.10-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10829346/1.7.10-latest.log)
@HypedDomi theres some error with optifine

**Comment by HypedDomi** [comment]
> [1.7.10-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10829346/1.7.10-latest.log)
> @HypedDomi theres some error with optifine

The file is empty

**Comment by Sai5810** [comment]
> 

how do i fix this? i'm launching fine on 1.8

**Comment by HypedDomi** [comment]
Compress the logs folder to a zip and send the zip

**Comment by Sai5810** [comment]
> 
[logs.zip](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10831606/logs.zip)

**Comment by HypedDomi** [comment]
We released a new Engine. Launch SolarTweaks, it'll update to the latest engine version. See if this solved your issue

**Comment by Sai5810** [comment]
> We released a new Engine. Launch SolarTweaks, it'll update to the latest engine version. See if this solved your issue

fixed ty
