### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by qdlmfao** [Solar-Tweaks/Solar-Tweaks#886]
**Describe the bug**
Whenever i start solar when i get to the "Launching Minecraft" (like when lunar opens) it crashes
Also none of the other versions work.

**To Reproduce**

**Expected behavior**
to launch the game and play

**Actual behaviour**
crashes

**Screenshots**
https://cdn.discordapp.com/attachments/1077884270296711279/1078476479060525116/image.png

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - Launcher Version 4.31]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
CRASH-c0350f5a-b02c-4b6c-8812-170d51025546

**Comment by ParvaGamer** [comment]
same thing happening with me

**Comment by HypedDomi** [comment]
Disable Cracked Accounts until we fix it
