### ISSUE TITLE
[Debug Mode] Do not instantly close the window on crash

### ISSUE THREAD

**Issue by he3als** [Solar-Tweaks/Solar-Tweaks#888]
**Is your feature request related to a problem? Please describe.**
You can not see any crash messages, as the window just instantly closes when Java stops.

**Describe the solution you'd like**
For Command Prompt or something similar to run the Java command instead, so that you can use `pause` at the end of it to not make the window close on exit.

**Comment by HypedDomi** [comment]
The process dies, that's why the console window gets terminated too. But you can check the logs for the crash. The console are just the logs in real time

**Comment by he3als** [comment]
> The process dies, that's why the console window gets terminated too. But you can check the logs for the crash. The console are just the logs in real time

I know, but you can prevent this by running it in a shell with `pause` at the end or something similar. Sometimes the log is not written, and text editors like Notepad do not auto-refresh the log, so it's a bit annoying to do.

**Comment by HypedDomi** [comment]
We don't use Shell commands. So we can't add `pause`. So this would be not possible

**Comment by HypedDomi** [comment]
> text editors like Notepad do not auto-refresh the log
You can use NotePad++. It can auto refresh

**Comment by he3als** [comment]
> > text editors like Notepad do not auto-refresh the log
> 
> You can use NotePad++. It can auto refresh

Yeah, but the default file associations for logs is Notepad.

> We don't use Shell commands. So we can't add `pause`. So this would be not possible

You could run the Java command through a shell though, so then you can add `pause` to the end.

**Comment by HypedDomi** [comment]
> Yeah, but the default file associations for logs is Notepad.

You know that you can change that right?

**Comment by he3als** [comment]
Yes, but it's a bit inconvenient by default. It's just a bit easier to have an actually real-time log window that will not close on crash.

**Comment by 770grappenmaker** [comment]
Well the issue is that it would then only work on windows, and you can just use `tail -f` as an alternative.
