### ISSUE TITLE
(1.8.9) Stuck report

### ISSUE THREAD

**Issue by mrmasterlmao** [Solar-Tweaks/Solar-Tweaks#890]
1.8.9 solar tweaks Stuck at the "Starting Minecraft" screen and not loading any further
After waiting for about an hour it has still not worked and is still stuck..
Just making this to confirm that is this only with me or with other people also
(I have downloaded zulu on the files)

**Comment by HypedDomi** [comment]
Try these steps:
- Use a different JRE
- Use a JVM Args Preset
- Update Lunar (Just launch Lunar on the version you want to play)

If nothing works, send your logs:
1. Open SolarTweaks
2. Go to the About Tab
3. Click `Open ST directory`
4. Send the logs folder
