### ISSUE TITLE
SolarTweaks crashing on launch

### ISSUE THREAD

**Issue by HypedDomi** [Solar-Tweaks/Solar-Tweaks#891]
SolarTweaks crashes on launch when you have Cracked Accounts enabled. Disable it in the meantime

We're aware of the bug and working on a fix. (No ETA yet).
Watch this issue for updates regarding this problem.
<img width="318" alt="image" src="https://user-images.githubusercontent.com/50876016/215748798-9b0213e4-da12-4b79-9707-fec59ff75585.png">

**Comment by HypedDomi** [comment]
We might have a fix. If you want to try it follow these steps:

1. Download the [engine](https://cdn.discordapp.com/attachments/970513983142494238/1078710268797911080/solar-engine.jar)
2. Go to your SolarTweaks folder (`C:\Users\YOUR-USER\.lunarclient\solartweaks`)
3. Replace the old file with the new file
4. Start SolarTweaks and launch minecraft as always

**Comment by PlayerZwatcher** [comment]
it work for me when i change that file

**Comment by Himesh4061** [comment]
it worked for me as well by changing that file
btw my problem looks like this 
![Screenshot (10)](https://user-images.githubusercontent.com/126310327/221340427-a743cf5e-6ef1-4bd1-a405-c6711ac65f04.png)

**Comment by Emi7029130** [comment]
CRASH-5227596c-4214-4a46-86a3-4b73544be9f5

**Comment by HypedDomi** [comment]
> CRASH-5227596c-4214-4a46-86a3-4b73544be9f5
> How to solve it?

Read the 2nd message from me

**Comment by Emi7029130** [comment]
don't work

**Comment by a1dqn7** [comment]
> SolarTweaks crashes on launch when you have Cracked Accounts enabled. Disable it in the meantime
> 
> We're aware of the bug and working on a fix. (No ETA yet). Watch this issue for updates regarding this problem. <img alt="image" width="318" src="https://user-images.githubusercontent.com/50876016/2157487

**Comment by a1dqn7** [comment]
bro pls help its not working

**Comment by a1dqn7** [comment]
> it work for me when i change that file

bro how to change the  file

**Comment by KingKnightop** [comment]
![Screenshot (341)](https://user-images.githubusercontent.com/126347014/221370046-3f300854-658c-481c-9edf-2f9c86bd0bcb.png)
ummm help pls

**Comment by HypedDomi** [comment]
We released a new Engine Version to fix those issues. Make sure to disable Skip checks

**Comment by Emi7029130** [comment]
where is the new version of engine?

**Comment by HypedDomi** [comment]
It'll download automatically
