### ISSUE TITLE
Solar Tweaks Crashing on Launch

### ISSUE THREAD

**Issue by Tanmay0830** [Solar-Tweaks/Solar-Tweaks#894]
**Describe the bug**
When I launch solar tweaks any version on cracked it crashes but when I turn of cracked then it works.

**To Reproduce**
1. Go to 'Solar Tweaks'
2. Click on 'Engine'
3. Click on 'Allow cracked'
4. Click on 'Launch'
5. See error

**Expected behavior**
To launch and work normally.

**Actual behaviour**
When I launch solar tweaks it says Launcher Crashed 'CRASH-8413758f-847a-49b0-84b3-a3efc31bb567'

**Screenshots**
...................

**Environment (please complete the following information):**
 - OS: Windows 11
 - Launcher Version: 4.3.1
 - Engine Version [eg. 1.6]:......................
 - Solar Stats Version (if applicable)

**Additional context**
Yesterday when I downloaded and launcher solar tweaks and enabled "allow cracked" it worked normally, but today when I open it then it crashes but when I disable "allow cracked" then it doesn't crashes but I can't play without cracked.

**Comment by HypedDomi** [comment]
#891
