### ISSUE TITLE
Minecraft is not responding with launch from Solar tweaks(1.8.9)

### ISSUE THREAD

**Issue by Onamato** [Solar-Tweaks/Solar-Tweaks#895]
The moment I launch minecraft and after launch it will not respond further, hopefully I will receive a quick fix

**Comment by Onamato** [comment]
The moment I launch minecraft and after launch it will not respond further, hopefully I will receive a quick fix

**Comment by HypedDomi** [comment]
Do you have cracked accounts enabled?

**Comment by Onamato** [comment]
Yes

**Comment by Onamato** [comment]
Cracked account are not supported anymore??

**Comment by HypedDomi** [comment]
They are. But its broken atm. Please see the pinned issue (#891)

**Comment by Onamato** [comment]
How much of time will it be taking to get the issue fixed?

**Comment by HypedDomi** [comment]
You can test this [build](https://cdn.discordapp.com/attachments/970513983142494238/1078710268797911080/solar-engine.jar) and check if it works for you. Just download the file and replace it with the old solar-engine. 

Please tell us then if it works

**Comment by Onamato** [comment]
Will you guys be able to give me some steps to follow

**Comment by HypedDomi** [comment]
Sure.
1. Download the file
2. Go to your SolarTweaks folder (`C:\Users\YOUR-USER\.lunarclient\solartweaks`)
3. Replace the old file with the new file
4. Start SolarTweaks and launch minecraft as always
