### ISSUE TITLE
Solar Tweaks software not starting

### ISSUE THREAD

**Issue by Adrirgamer** [Solar-Tweaks/Solar-Tweaks#898]
I just installed Solar Tweaks v4.3.1, but i cannot launch it.
When i double click on solar tweaks, it just stays on the icon as shown in the screenshot
Can someone help me ?
Im on windows 10
![Capture2JPG](https://user-images.githubusercontent.com/101261072/221273558-7d0a6ea2-6411-4334-a3ed-fac2e3688eef.JPG)

**Comment by HypedDomi** [comment]
Press CTRL Shift I then go to Console and screenshot

**Comment by 770grappenmaker** [comment]
Are you in India?
