### ISSUE TITLE
my minecraft not responding

### ISSUE THREAD

**Issue by ASGspacejet07** [Solar-Tweaks/Solar-Tweaks#899]
![image](https://user-images.githubusercontent.com/126286318/221275743-5fb66665-37c7-4563-94c3-5aaea753bc37.png)
idk what happend to my solar tweaks but my launcher is not responding plz help me and i gave u a screenshot.and one more screenshotwhen i when to debug mode
![image](https://user-images.githubusercontent.com/126286318/221278956-b7d479f2-b5d1-4d42-953b-da889fa693e3.png)

**Comment by HypedDomi** [comment]
Try updating Lunar

**Comment by Lakkyboy** [comment]
> 

it's my same problem and every time i launch lunar it update lc assets

**Comment by ASGspacejet07** [comment]
its uptodate

**Comment by ASGspacejet07** [comment]
plz   help

**Comment by mrmasterlmao** [comment]
Cracked accounts are not functioning for now

**Comment by ASGspacejet07** [comment]
man now its work idk how bur minecraft god help but one thing im crack player and why my cosmetics not showing and how to put skin

**Comment by HypedDomi** [comment]
You can't use cosmetics and skins with cracked accs
