### ISSUE TITLE
i think solar  is not working on windows insider built can you make it work pls 

### ISSUE THREAD

**Issue by EditingMitten39** [Solar-Tweaks/Solar-Tweaks#902]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by EditingMitten39** [comment]
.

**Comment by HypedDomi** [comment]
It works on Windows Insiders. Send your logs
1. Open SolarTweaks
2. Go to the About Tab
3. Click `Open ST directory`
4. Send the logs folder

**Comment by EditingMitten39** [comment]
ok

**Comment by EditingMitten39** [comment]
[launcher-old.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10832690/launcher-old.log)
[launcher-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10832691/launcher-latest.log)
[1.19.3-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10832692/1.19.3-latest.log)
[1.8.9-latest.log](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10832693/1.8.9-latest.log)

**Comment by HypedDomi** [comment]
You dont have Lunar installed. Install it. You need it
