### ISSUE TITLE
i just found 2 glitches...

### ISSUE THREAD

**Issue by GamingIQ1** [Solar-Tweaks/Solar-Tweaks#903]
**Describe the bug**
removing shop button makes the friend tab unusable and I cant move my head with raw mouse input

**To Reproduce**
1. Go to ' engine'
2. Click on 'raw mouse input and remove shop'

**Expected behavior**
I expected my game to feel much better

**Actual behaviour**
i technically cant play the game

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by HypedDomi** [comment]
Remove Store Button is working fine: 

<img width="720" alt="image" src="https://user-images.githubusercontent.com/50876016/221346192-7c67611d-0d64-46cd-a1c7-9f87bd82a4e8.png">

**Comment by HypedDomi** [comment]
Try relaunching your Game. That should fix Raw Input

**Comment by 770grappenmaker** [comment]
or /reloadmice

**Comment by GamingIQ1** [comment]
> Try relaunching your Game. That should fix Raw Input

nope didn't work

**Comment by GamingIQ1** [comment]
> or /reloadmice

still didnt work

**Comment by GamingIQ1** [comment]
hold on lemme make the raw mouse input more clear, I think I didn't tell you the actual issue, when I enable raw mouse input I can't move my head, I can move my cursor (in inventory etc) but not in-game

**Comment by HypedDomi** [comment]
But you use a mouse and not a trackpad, right?

**Comment by GamingIQ1** [comment]
> But you use a mouse and not a trackpad, right?

ye I use a roccat kone pro

**Comment by 770grappenmaker** [comment]
I mean solar doesn't do the mouse handling, an input library does the usb stuff for us, so I don't know what the issue can be

**Comment by 770grappenmaker** [comment]
Maybe your mouse uses an exotic protocol instead of a generic mouse protocol? Does your mouse work without its drivers?

**Comment by lmaoxd123xd** [comment]
it's the raw mouse input mod that's actually messing with the game

**Comment by 770grappenmaker** [comment]
> it's the raw mouse input mod that's actually messing with the game

Yes, I know, but that's the point: Raw mouse input polls from your USB directly and bypasses drivers, therefore making it raw mouse input
