### ISSUE TITLE
not opening mc

### ISSUE THREAD

**Issue by Adarsha194Gaming** [Solar-Tweaks/Solar-Tweaks#904]
**whenever I try to open minecraft it just crashes leaving a code behind and it only happens in solar tweaks**
I can't understand what the bug is but the thing is it just crashes when i open and leaves a code 466af8c1 9262 4403 a140 8d93316a12c5.

**To Reproduce**

**Expected behavior**
i expected it should work with cracked account 
**Actual behaviour**
but it only launch without cracked account
**Screenshots**
[](url)
![image](https://user-images.githubusercontent.com/126307167/221335233-0f38a928-23a9-41dd-9a40-fe32e7225892.png)

**Environment (please complete the following information):**
 - OS: [Windows]
 - Launcher Version [eg. 4.2.0]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by HypedDomi** [comment]
#891
