### ISSUE TITLE
Add proximity chat

### ISSUE THREAD

**Issue by urnoob** [Solar-Tweaks/Solar-Tweaks#909]
**Is your feature request related to a problem? Please describe.**
Some of my friends are not allowed to get discord and instead of loading up discord or getting it for the first time, you turn on the option before you join and launch the game and just come across
 a friend.
**Describe the solution you'd like**
When you are close to someone you can talk to them with a mic in Minecraft, have a little settings section in-game for it, and have a button to turn on your mic.

**Describe alternatives you've considered
For different types of servers, do not make it so that the server owner needs to add scripts for proximity chat.

**Additional context**

**Comment by HypedDomi** [comment]
![image](https://user-images.githubusercontent.com/50876016/221425389-caef2312-62d8-46da-81e2-fc086ef2a6fb.png)

**Comment by 770grappenmaker** [comment]
Wow this is just built in wtf
