### ISSUE TITLE
Solar socket cosmetics and emotes not working

### ISSUE THREAD

**Issue by Tanmay0830** [Solar-Tweaks/Solar-Tweaks#917]
**Describe the bug**
When paste 'wss://socket.solartweaks.com' in websocket and enable it and launch the game, the cosmetics and emotes doesn't show.

**Expected behavior**
I expected that the emotes and cosmetics will show when I launch it.

**Actual behaviour**
When I launch the game it doesn't show any emotes or cosmetics.

**Screenshots**
..............

**Environment (please complete the following information):**
 - OS: Windows 11
 - Launcher Version : 4.3.1
 - Engine Version: ............
 - Solar Stats Version: ............

**Comment by HypedDomi** [comment]
Won't work on cracked Accounts

**Comment by 770grappenmaker** [comment]
Plus unrelated to this project
