### ISSUE TITLE
Lag Spikes (again)

### ISSUE THREAD

**Issue by GamingIQ1** [Solar-Tweaks/Solar-Tweaks#922]
**Describe the bug**
so i got unbanned from hypickle and eversince I started playing I've been getting HUGE lag spikes

**To Reproduce**
1. Go to 'Solar Tweaks'
2. Click on 'Launch 1.8.9'

**Expected behavior**
I expected it to be smooth

**Actual behaviour**
I'm getting lag spikes for 1,5 and sometimes 10 SECONDS

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS
 - Launcher Version [4.3.1
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
so I know I've made an issue bout this but that was on a cracked server (which lags less ig) and before u say "use a preset" I've enabled the Zulu preset but nothings working here's my logs incase:
[logs.zip](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10834584/logs.zip)

**Comment by HypedDomi** [comment]
Try different Presets/JRE's

**Comment by 770grappenmaker** [comment]
use default args, use graal, allocate 4gb, make sure to set your gpu in nvidia panel if on laptop, disable cape system if you want
