### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Pulpasek** [Solar-Tweaks/Solar-Tweaks#929]
When I turn on lunar client there is sound, but when I turn on solar tweaks there is no sound. I don't know why, but it's probably a bug.

Mc version: 1.19.3
Win 11
Newest version solar tweaks launcher

**Comment by HypedDomi** [comment]
That's a known bug. We haven't found a fix yet for this.

**Comment by ATreeShine** [comment]
Reload your texture pack it will fix the issue

**Comment by Pulpasek** [comment]
> Reload your texture pack it will fix the issue
Didnt't work, I just need to wait for fix
