### ISSUE TITLE
solar is not launching cmd and notepad popup 

### ISSUE THREAD

**Issue by EditingMitten39** [Solar-Tweaks/Solar-Tweaks#930]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
Description of what is actually happening.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by EditingMitten39** [comment]
pls help me 
😭 i still can't launch solar pls help

**Comment by HypedDomi** [comment]
Disable Debug Mode

**Comment by EditingMitten39** [comment]
idk its not launching
😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭
i do everything

**Comment by EditingMitten39** [comment]
nothing happened

**Comment by EditingMitten39** [comment]
i am uninstalling solar its not working
