### ISSUE TITLE
client won't open

### ISSUE THREAD

**Issue by MCG-123** [Solar-Tweaks/Solar-Tweaks#932]
The game loads normally with the logo, blurry background, and loading bar. But after that, the game turns black and crashes

**Comment by HypedDomi** [comment]
Send your logs
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4

**Comment by ATreeShine** [comment]
Try to change your JRE or redownload it
