### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by demonite87x** [Solar-Tweaks/Solar-Tweaks#933]
Game crashing and gives this error code
CRASH-f6298b95-da25-435b-9bc5-b30317e2ce1b

When i click launch it did launch and did say "Game is running" but after waiting for the game to launch it crashes and gives the code above, when i launch it in debug mode it always says "Starting JVM"

 - OS: Windows 10
 - Launcher Version: 4.3.2

Log: [crash-2023-03-01_20.29.55-client.txt](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10861529/crash-2023-03-01_20.29.55-client.txt)

**Comment by HypedDomi** [comment]
Update your Graphic drivers:
https://www.drivereasy.com/knowledge/error-org-lwjgl-lwjglexception-pixel-format-not-accelerated/
