### ISSUE TITLE
Stuck on "Launching Starting JVM"

### ISSUE THREAD

**Issue by clownpierx** [Solar-Tweaks/Solar-Tweaks#934]
JVM
When i try to play the game, everything is right at first but when it gets to Launching starting JVM, it stucks and sometimes it disappears and the play button appears again.

**To Reproduce**
1. Go to 'Solar Tweaks'
2. Click on 'Play'
3. See error "Launching JVM" (stuck)

**Expected behavior**
Game will launch

**Actual behaviour**
Stucks on launching JVM

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows
 - Launcher Version 4.3.2
 - Engine Version N.A
 - Solar Stats Version N.A

**Comment by ATreeShine** [comment]
Try to change your JRE or redownload it and try again

**Comment by clownpierx** [comment]
Ok thanks for your help! It worked😄.

**Comment by clownpierx** [comment]
Awesome, thanks!
