### ISSUE TITLE
Bug 1.8

### ISSUE THREAD

**Issue by JohnnyArtur** [Solar-Tweaks/Solar-Tweaks#935]
**Describe the bug**

**To Reproduce**
1. Go to 1.8 version
2. Launch
3. And the sound doesnt work

**Expected behavior**
Sound works.

**Actual behaviour**
Sound doesnt work.

**Screenshots**
Not gonna work.

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports) 
I can not do the download of logs(not downloading)

**Comment by GA1AXY5** [comment]
The same thing is happening to me in 1.19.2. The only way that i was able to fix it was through a resource pack from a 3rd party

**Comment by TBHGodPro** [comment]
Delete the `natives` folder in your `.lunarclient/offline/multiver`

**Comment by lmaoxd123xd** [comment]
found the issue... ever notice that the og pack says "missing mcmeta.pack"? for some reason solar tweaks when installed independently does not include that file in the game file... so all you need to do is download lunar client, launch it once and close it... now the mcmeta.pack is installed in the file and the audio issue is fixed

**Comment by TBHGodPro** [comment]
@lmaoxd123xd Can you explain this some more?

**Comment by 770grappenmaker** [comment]
> @lmaoxd123xd Can you explain this some more?

You messed up :+1:
