### ISSUE TITLE
Minecraft doesnt launch

### ISSUE THREAD

**Issue by iitzfrlx** [Solar-Tweaks/Solar-Tweaks#937]
**Describe the bug**
minecraft doesnt open when i launch

**To Reproduce**
1. Launch 1.8.9
2. Wait for it to open
3. Nothing happens

**Expected behavior**
For minecraft to open at least in the taskmanager

**Actual behaviour**
minecraft doesnt open

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: Windows 10 pro
 - Launcher Version 4.3.2

**Comment by HypedDomi** [comment]
Do you have Lunar installed? And send your Logs please:
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4
