### ISSUE TITLE
2 critical bugs that would ruin the experience with solar tweaks for new users (solutions included + msgs for the devs)

### ISSUE THREAD

**Issue by lmaoxd123xd** [Solar-Tweaks/Solar-Tweaks#942]
**Describe the bug**
1) raw mouse input mod in engine prevents player from looking around
2) missing pack.mcmeta in the game file

**To Reproduce**
1. open solar tweaks
2. enable raw mouse input
3. launch the game
4. can't look around after a few mins of playing and no sound without having launched lunar client once

**Expected behavior**
has sound and not having the inability to look around

**Actual behaviour**
can't look around after playing for a few secs, and no sound if having not launched lunar client at least once

**Screenshots**
none

**Environment (please complete the following information):**
 - OS: windows 11
 - Launcher Version 4.3.2
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
how to fix:
bug #1: disable raw mouse input in the engine section in the solar tweaks launcher
bug #2: install lunar client and launch lunar once, then the bug is fixed
just wanna say that this should be patched bcz it's been really frustrating for a new user like myself to find the bug and experiment to fix it (the actual solutions that i found were not available anywhere in the bug section, i had to experiment for days)
anyway solar tweaks it's a good client with many quality-of-life mods (e.g no hurt cam), however there are some minor bugs that should be fixed

**Comment by HypedDomi** [comment]
You need to launch Lunar first. After that the pack.mcmeta Error should be gone. For Raw Mouse Input can @770grappenmaker hopefully help

**Comment by lmaoxd123xd** [comment]
> You need to launch Lunar first. After that the pack.mcmeta Error should be gone. For Raw Mouse Input can @770grappenmaker hopefully help

yea i already said that...

**Comment by 770grappenmaker** [comment]
I've had only one other person commenting that their mouse doesn't work with raw mouse input, for most people it works really nicely. The issue might be that JInput doesn't care much about drivers, most of the time it will use a generic usb protocol.

**Comment by lmaoxd123xd** [comment]
> 

ok

**Comment by 770grappenmaker** [comment]
Would you mind shooting me a DM on discord (NotEvenJoking#8399) and providing logs?

**Comment by lmaoxd123xd** [comment]
> Would you mind shooting me a DM on discord (NotEvenJoking#8399) and providing logs?

uhhh im kinda busy rn but ill prob do it later... what are logs anyway?

**Comment by 770grappenmaker** [comment]
1. Open Solar Tweaks and enable Keep Launcher open
 2. Try to reproduce the error
 3. Go to the About tab and click Download Logs then click Open ST directory
 4. Drag and drop the logs.zip file into discord
https://cdn.discordapp.com/attachments/866624451398205470/1080122216324268192/SolarTweaks_-_Logs.mp4

**Comment by lmaoxd123xd** [comment]
ok

**Comment by lmaoxd123xd** [comment]
> 1. Open Solar Tweaks and **enable** `Keep Launcher open`
> 2. Try to reproduce the error
> 3. Go to the About tab and click `Download Logs` then click `Open ST directory`
> 4. Drag and drop the `logs.zip` file into discord
> 
>  SolarTweaks_-_Logs.mp4

heyy how can i dm u :v im not too familiar w/ discord :v

**Comment by lmaoxd123xd** [comment]
> 1. Open Solar Tweaks and **enable** `Keep Launcher open`
> 2. Try to reproduce the error
> 3. Go to the About tab and click `Download Logs` then click `Open ST directory`
> 4. Drag and drop the `logs.zip` file into discord
> 
>  SolarTweaks_-_Logs.mp4

it says that you're not accepting friend requests so idk how to dm u rn... the search bar doesn't seem to work that well

**Comment by HypedDomi** [comment]
You can join our server and create a ticket
discord.gg/solarsocket
