### ISSUE TITLE
cracked accounts are not working

### ISSUE THREAD

**Issue by jdcdanguk** [Solar-Tweaks/Solar-Tweaks#944]
Cracked account are not working. Please help

**Comment by HypedDomi** [comment]
Send your logs
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4

**Comment by jdcdanguk** [comment]
> Send your logs
> 
> 1. Open Solar Tweaks and **enable** `Keep Launcher open`
> 2. Try to reproduce the error
> 3. Go to the About tab and click `Download Logs` then click `Open ST directory`
> 4. Drag and drop the `logs.zip` file into discord
> 
>  SolarTweaks_-_Logs.mp4

I cant. Everytime I check the launcher the is no logs.zip thing. Please help
I want to make a video about this client but I cant

**Comment by HypedDomi** [comment]
You need to press Download Logs first

**Comment by Artem-xe** [comment]
jdcdanguk still having an issuse LOL AND BUGS

**Comment by HypedDomi** [comment]
> jdcdanguk still having an issuse LOL AND BUGS

Then send your logs
