### ISSUE TITLE
Fps Dropouts

### ISSUE THREAD

**Issue by oninqlan** [Solar-Tweaks/Solar-Tweaks#945]
**Describe the bug**
I get around every minute an fps dropout.

**To Reproduce**
For me its just playing the game.

**Expected behavior**
Do not have these dropouts.

**Actual behaviour**
In "Describe the bug" mentioned.

**Screenshots**
I recorded some gameplay to show the problem better. Sadly the recordings are too big so here are the mediafire links: 

1. Singleplayer: https://www.mediafire.com/file/0ucpb0wae2xyb0s/Singleplayer.mp4/file
2. Multiplayer: https://www.mediafire.com/file/mhgbqnr2mw0ene6/Multiplayer.mp4/file

**Environment (please complete the following information):**
 - OS: Windows 10
 - Launcher Version [eg. 4.3.3]
 - Engine Version: ?
 - Solar Stats Version: I don't know

**Additional context**
It is not happening on Lunar Client or Vanilla Minecraft and on an other Windows PC it also happens with SSolar Tweaks.

I hope you can help me because appart from that I really like the Client :)

**Comment by 770grappenmaker** [comment]
This appears to be a GC issue, please set your jvm arguments to solely `-XX:+DisableAttachMechanism`

**Comment by oninqlan** [comment]
Thanks for your support! But how do I do, what you described?

**Comment by oninqlan** [comment]
> This appears to be a GC issue, please set your jvm arguments to solely `-XX:+DisableAttachMechanism`

Thanks for your support! But how do I do, what you described?

**Comment by HypedDomi** [comment]
Open your Launcher then click Settings and scroll down to JVM Args

**Comment by oninqlan** [comment]
Thx I found it right now too 👍
