### ISSUE TITLE
1.8 bug

### ISSUE THREAD

**Issue by JohnnyArtur** [Solar-Tweaks/Solar-Tweaks#948]
**Describe the bug**

**To Reproduce**
1. Go to 1.8
2. Launch the game
3. Play a little
4. Game crashes

**Expected behavior**
Game doesnt crash.

**Actual behaviour**
Game crashing.

**Screenshots**
There is not possible.

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)
(I cant download it)

**Comment by HypedDomi** [comment]
Send your Logs
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4
