### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by VenOmBoyXOG** [Solar-Tweaks/Solar-Tweaks#950]
**Describe the bug**
I try opening the game but it doesnt work

**To Reproduce**
1. Go to 'Home'
2. Click on 'Launch [version]'
3. Wait for load
PS: This might be just because I am using an outdated version

**Expected behavior**
Me to press play and for the game to launch, so I can play Minecraft.

**Actual behaviour**
I am launching Minecraft through Solar Tweaks with my preferred settings, and when it is almost done (I think), it gets stuck on Launching... Checking game...

 - OS: Windows 11
 - Launcher Version: 4.2.0
 - Engine Version: No Idea

**Comment by HypedDomi** [comment]
Probably. Update to the latest version

**Comment by VenOmBoyXOG** [comment]
its not updating :P

**Comment by HypedDomi** [comment]
Uninstall Solar Tweaks and install then the latest Version

**Comment by VenOmBoyXOG** [comment]
I did it, and now it works! Thanks!

**Comment by qualk** [comment]
@VenOmBoyXOG pls close the issue if it is resolved :)

Feel free to join the [Discord server](https://discord.gg/solarsocket) for additional support, or if you want to hang out with the community!
