### ISSUE TITLE
Error in Launcher 

### ISSUE THREAD

**Issue by Juniorb182004** [Solar-Tweaks/Solar-Tweaks#956]
**Describe the bug**

**To Reproduce**
1. Go to 'Home'
2. Click on 'Launch[version]'
3. Wait for load

**Expected behavior**
I was waiting for it to start like always

**Actual behaviour**
when it is running the version it skips me "Error. Cannot read property 'subversions' of undefined
**Screenshots**

![error in solar tweaks](https://user-images.githubusercontent.com/127162391/223293639-f8cf846e-9a24-43fd-9fb4-90f364b1a4f8.jpg)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Launcher Version 4.3.3
 - Engine Version no idea
 - Solar Stats Version (if applicable)

**Comment by qualk** [comment]
Try uninstalling Solar Tweaks, then running [SolarPurge.bat](https://cdn.discordapp.com/attachments/979553959624728596/1028683669419855912/SolarPurge.bat) and run it as Administrator. Then, reinstall Solar Tweaks using the latest release ([4.3.3](https://github.com/Solar-Tweaks/Solar-Tweaks/releases/download/v4.3.3/Solar-Tweaks-Setup-4.3.3.exe). Then you can relaunch Solar Tweaks, re-apply your settings and it should resolve your issues.

Feel free to join the [Discord server](https://discord.gg/solarsocket) for additional support, or if you want to hang out with the community!
