### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Thensi72** [Solar-Tweaks/Solar-Tweaks#958]
**Describe the bug**
No sound ingame

**To Reproduce**
1. Launch the game
2. Click on any button
3. Notice it doesnt make a sound

**Expected behavior**
For it to make a sound

**Actual behaviour**
No sound

**Screenshots**
N/A

**Environment (please complete the following information):**
Windows 10
4.3.3
idk what this is
not enabled

**Additional context**
no i dont have any

**Comment by qualk** [comment]
Make sure your launch directory matches in both Lunar Client and Solar Tweaks, then launch Lunar Client on the version you want sound on.

![image](https://user-images.githubusercontent.com/68494669/223337198-fe25df84-68e6-49cd-8e29-71392d082931.png)


If the above does not work, do the following:

- Go to to your .lunarclient folder
- Go to `offline/multiver`
- Delete the `natives` directory
﻿
Feel free to join the [Discord server](https://discord.gg/solarsocket) for additional support, or if you want to hang out with the community!

**Comment by Thensi72** [comment]
ty it works

**Comment by qualk** [comment]
> ty it works

All good man, have a good day, and an even better time using Solar Tweaks! If you encounter any additional problems, feel free to ask for help in the [Discord](https://discord.gg/solarsocket), or open another GitHub issue and ping me at @qualk.
