### ISSUE TITLE
[Enhancement] Skins for cracked Players

### ISSUE THREAD

**Issue by Thensi72** [Solar-Tweaks/Solar-Tweaks#963]
**Is your feature request related to a problem? Please describe.**
well kinda that skin changer doesnt work for cracked

**Describe the solution you'd like**
a way for cracked players to have a custom skin

**Describe alternatives you've considered**
maybe a skin changer for cracked players or an option on the allow cracked acconuts thing

**Additional context**
nah i dont have any

**Comment by Speedisop** [comment]
i also need skin in cracked

**Comment by SmokeV4** [comment]
You could try using a resource pack that changes the default alex,steve skins

**Comment by Thensi72** [comment]
> You could try using a resource pack that changes the default alex,steve skins

that makes everyones skin like that though i only want it for me

**Comment by HypedDomi** [comment]
https://github.com/Solar-Tweaks/Solar-Engine/releases/tag/v2.1.5
