### ISSUE TITLE
Not loading cosmetics or showing that you're in lunar

### ISSUE THREAD

**Issue by linksally** [Solar-Tweaks/Solar-Tweaks#965]
**Describe the bug**
title
**To Reproduce**
1. open solar tweaks
2. load in to a world

**Expected behavior**
loading that ur using lunar and showing cosmetics

**Actual behaviour**
not loading that you are using lunar and showing cosmetics

**Screenshots**
![image_2023-03-09_091552602](https://user-images.githubusercontent.com/127417638/224068399-f529f459-3564-460d-9ec6-9e211fc49eeb.png)
![Screenshot_20230309_091514](https://user-images.githubusercontent.com/127417638/224068469-b12136af-96b0-4133-b7e5-74b4cae5818f.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Launcher Version 4.3.3

**Additional context**
nothing

**Comment by redefault** [comment]
this is not a launcher issue  but ok restart game and it should be fixed
