### ISSUE TITLE
Sound Bug

### ISSUE THREAD

**Issue by ThanosTheGamer** [Solar-Tweaks/Solar-Tweaks#970]
Hi, when i start solar tweaks everything works fine, except one thing, i don't hear minecraft sounds...i'm in 1.8 any solution?

**Comment by HypedDomi** [comment]
Make sure you're on the latest Launcher Version, which is v4.3.3. When it still don't work, try updating Lunar by launching 1.8.

**Comment by HypedDomi** [comment]
When nothing of the above helps, send your logs:
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4
