### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by teanea** [Solar-Tweaks/Solar-Tweaks#973]
Solartweaks wont load any fake/real cosmetics or emotes, you can't even open the emote wheel, this started happening 2 days ago, every few minutes you will get a notification saying authentication error and you cant do anything about it, this does not happen on lunar client, only solar tweaks

**Comment by HypedDomi** [comment]
Can you send your Logs? 
1. Open Solar Tweaks and **enable** `Keep Launcher open`
2. Try to reproduce the error
3. Go to the About tab and click `Download Logs` then click `Open ST directory`
4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4

**Comment by teanea** [comment]
> Member

I found the problem, however I hope it still gets fixed, I had to disable websocket for it to work again

**Comment by HypedDomi** [comment]
It works for everyone else. Thats why i asked you to send the logs. Make sure youre on the latest Lunar version

**Comment by teanea** [comment]
> It works for everyone else. Thats why i asked you to send the logs. Make sure youre on the latest Lunar version

You still want me to send them?

**Comment by HypedDomi** [comment]
When you want cosmetics then yes

**Comment by teanea** [comment]
> When you want 
[Uploading logs.zip…]()
cosmetics then yes

**Comment by HypedDomi** [comment]
The logs are too long. Only launch your Game and try to make the error then upload the new logs

**Comment by teanea** [comment]
> The logs are too long. Only launch your Game and try to reproduce the error, then upload the new logs

Ill just wait for it to get fixed. The issue is happening on Linux and Windows

**Comment by HypedDomi** [comment]
Well, we can't fix it because it is fixed. It's only an issue on your end

**Comment by HypedDomi** [comment]
Well we cant do anything without knowing where the problem is. And it works for like 95% perfectly fine
