### ISSUE TITLE
Hurtcam not working at all in 1.19.2 sodium

### ISSUE THREAD

**Issue by Fantasy924** [Solar-Tweaks/Solar-Tweaks#974]
**Hurt cam not working**
hurtcam is not working even when i restart and put the multiplier to 0
**To Reproduce**
1. Go to 'open solartweaks'
2. Click on 'engine'
3. Scroll down to 'HurtCamera Multiplier set it to 0'

**Expected behavior**
No Hurt Cam 

**Actual behaviour**
theres still hurt cam even to is set to 0
**Screenshots**
![image](https://user-images.githubusercontent.com/127634149/224534416-dca67926-fcb4-4839-a30d-cab7ff5e642d.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Launcher Version [eg. 4.0.1]
 - Engine Version [eg. 1.6] (If you can't find this, leave blank)
 - Solar Stats Version (if applicable)

**Additional context**
Also attach logs (if you have them) (launcher, game, jvm/minecraft crash reports)

**Comment by HypedDomi** [comment]
Works only for 1.8 (maybe for 1.12)

**Comment by Fantasy924** [comment]
oof no fix???

**Comment by HypedDomi** [comment]
It isnt supposed to work on 1.19
