### ISSUE TITLE
Cannot read property 'extraArguments' of undefined.

### ISSUE THREAD

**Issue by sean-7777** [Solar-Tweaks/Solar-Tweaks#975]
**Describe the bug**
When you press play on version 1.8.9, it displays:
```
Error
Cannot read property 'extraArguments' of undefined
```

**To Reproduce**
1. Update to version 4.3.3
Edit: This happens in 4.2.0 too.
3. Select version 1.8.9 Optifine

**Expected behavior**
The game should launch.

**Actual behaviour**
The client errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/67909939/224580476-33be57c5-73a3-471a-9332-8720e1c5f34b.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Launcher Version: 4.3.3
 - Engine Version: ?
 - Solar Stats Version: ?

**Additional context**
I'm also having this problem with the app: [Solar Tweaks Discussions](https://github.com/orgs/Solar-Tweaks/discussions/972)

**Comment by HypedDomi** [comment]
Go to `%appdata%\solartweaks` and delete the config.json
