### ISSUE TITLE
Trying to build Solar-Tweaks with npm

### ISSUE THREAD

**Issue by SkyplayYT** [Solar-Tweaks/Solar-Tweaks#977]
So, I tried to build the Solar-Tweaks to test something. The problem is, that I can't build it. Every time I try it, I get this error:
![image](https://user-images.githubusercontent.com/103359249/224753864-64c620bb-e1ed-4b2a-8529-5de343825f1a.png)

Am I making some mistakes or am I using the wrong npm version? I did everything that the _Building from Source_ says. I also tried some other npm versions.

I also got this error. The problem is, that I have VS2022 installed and Desktop development with C++ is also installed.
![image](https://user-images.githubusercontent.com/103359249/224759056-bc5788f8-9eb8-4e83-b2aa-ccf2b152a14d.png)

**Comment by HypedDomi** [comment]
Try NodeJS 16 and then do npm i

**Comment by SkyplayYT** [comment]
Now I got this:
![image](https://user-images.githubusercontent.com/103359249/225008604-7b4f9f64-b62d-45c6-8c86-c2f5ee7782f4.png)

**Comment by HypedDomi** [comment]
Yeah now it works.
