### ISSUE TITLE
Cracked Skins

### ISSUE THREAD

**Issue by sethyLOLs** [Solar-Tweaks/Solar-Tweaks#981]
Hi! I want cracked skins or at least a skin changer.

**Comment by HypedDomi** [comment]
Duplicate:
- https://github.com/Solar-Tweaks/Solar-Tweaks/issues/963

**Comment by CompeyDev** [comment]
I doubt this would be rather complicated to implement as similar APIs already exist. I'd create a PR if that's welcome.

**Comment by 770grappenmaker** [comment]
> I doubt this would be rather complicated to implement as similar APIs already exist. I'd create a PR if that's welcome. 

You would have to PR to Solar Engine, all contributions of course are welcome

**Comment by CompeyDev** [comment]
Yeah apologies, don't think I'll be able to get this done, pretty busy with life atm...

**Comment by RevaldoVeryCool** [comment]
maybe you guys can try to use the ely.by authlib-injector?

**Comment by 770grappenmaker** [comment]
> maybe you guys can try to use the ely.by authlib-injector?

Will probably not work on lunar, plus it is required that you also apply that on the server where you would want to display the skin, so no, that would not work.

**Comment by CompeyDev** [comment]
> maybe you guys can try to use the ely.by authlib-injector?

I was thinking of the same thing, lmao.

**Comment by Thensi72** [comment]
> > maybe you guys can try to use the ely.by authlib-injector?
> 
> Will probably not work on lunar, plus it is required that you also apply that on the server where you would want to display the skin, so no, that would not work.

you dont need it on the server it can be just clientside

**Comment by HypedDomi** [comment]
You can just use a Texture Pack then

**Comment by CompeyDev** [comment]
> > > maybe you guys can try to use the ely.by authlib-injector?
> > 
> > 
> > Will probably not work on lunar, plus it is required that you also apply that on the server where you would want to display the skin, so no, that would not work.
> 
> you dont need it on the server it can be just clientside

In this case other players in multiplayer instances would not be able to see your skin, only you would.

**Comment by CompeyDev** [comment]
I wonder how TL does this, because I am pretty sure they've created some sort of an implementation using ely.by, which works flawlessly.
