### ISSUE TITLE
Minecraft not launching properly. 

### ISSUE THREAD

**Issue by ImmortalRhino63** [Solar-Tweaks/Solar-Tweaks#994]
Hi,
When launching minecraft from solar tweaks the window (with minecraft) pops up but then proceeds to give an error. I have reinstalled solar tweaks with new versions but the problem doesnt go away. 

>I press launch
>minecraft window comes up like usual
>then says not rensponding
>then crashes 

 - OS: [Windows 11]
 - Launcher Version [eg. 4.3.3]
 
![image](https://user-images.githubusercontent.com/128328127/226212514-3d175b23-b154-4604-9227-b903ddc37734.png)

CRASH-64ca62e6-a38f-4ba6-ae4f-de78946a4c46

![image](https://user-images.githubusercontent.com/128328127/226212748-35f6274d-4265-4343-b41b-fe6f1f8e9c29.png)

i am on cracked btw

**Comment by HypedDomi** [comment]
Try these steps:
1. Update Lunar
2. Try a different JRE or different JVM Args
3. Send your logs:
	1. Open Solar Tweaks and **enable** `Keep Launcher open`
	2. Try to reproduce the error
	3. Go to the About tab and click `Download Logs` then click `Open ST directory`
	4. Drag and drop the `logs.zip` file into discord

https://user-images.githubusercontent.com/50876016/222073117-44d61000-002f-4168-99de-5f889b46a082.mp4

**Comment by ImmortalRhino63** [comment]
thanks!

**Comment by koks187** [comment]
If i try to start 1.8 i get an Error called

Check Natives Error: TypeError: Cannot read property 'artifacts' of undefined
    at Jt (app://./js/app.b5ebebce.js:1:46400)
    at async Bt (app://./js/app.b5ebebce.js:1:52705)
    at async Proxy.launchGame (app://./js/app.b5ebebce.js:1:54488)

can annyone help me?
