### ISSUE TITLE
Check Natives Error

### ISSUE THREAD

**Issue by HypedDomi** [Solar-Tweaks/Solar-Tweaks#999]
If i try to start 1.8 i get an Error called

Check Natives Error: TypeError: Cannot read property 'artifacts' of undefined
    at Jt (app://./js/app.b5ebebce.js:1:46400)
    at async Bt (app://./js/app.b5ebebce.js:1:52705)
    at async Proxy.launchGame (app://./js/app.b5ebebce.js:1:54488)

can annyone help me?

_Originally posted by @koks187 in https://github.com/Solar-Tweaks/Solar-Tweaks/issues/994#issuecomment-1477853731_

**Comment by COOLIQYT** [comment]
Check Natives Error: TypeError: Cannot read property 'artifacts' of undefined
    at Jt (app://./js/app.b5ebebce.js:1:46400)
    at async Bt (app://./js/app.b5ebebce.js:1:52705)
    at async Proxy.launchGame (app://./js/app.b5ebebce.js:1:54488) 

can anyone help me??

**Comment by HypedDomi** [comment]
@COOLIQYT Try this:

**Windows:**
Download [SolarPurge.bat](https://cdn.discordapp.com/attachments/979553959624728596/1028683669419855912/SolarPurge.bat) and run it as Administrator.
Then, reinstall Solar Tweaks using [this setup](https://github.com/Solar-Tweaks/Solar-Tweaks/releases/download/v4.3.3/Solar-Tweaks-Setup-4.3.3.exe)

**MacOS:**
Open up terminal, and run `rm -rf ~/Library/Application Support/solartweaks`

Then you can relaunch Solar Tweaks, and it should resolve your issues.
